# BoostFL label-flipping robustness (BoT-IoT)

## 1. Imports

In [1]:
import os
import json
import math
import warnings

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset, Subset

import flwr as fl
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score, confusion_matrix,
)

warnings.filterwarnings("ignore")

## 2. Configuration

In [2]:
CSV_PATH = r"../../../data/Bot-IoT.csv"
TARGET_MULTICLASS = "category"
NORMAL_CLASS = "Normal"
DROP_COLS = ['attack', 'category', 'subcategory ', 'pkSeqID', 'saddr', 'daddr', 'soui', 'doui', 'sco', 'dco', 'smac', 'dmac']

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

NUM_CLIENTS = 10
NUM_PARTITIONS = 10
BATCH_SIZE = 32
EPOCHS = 5
EPSILON = 1e-8
LEARNING_RATE = 0.001
MAX_ALPHA = 10.0
MIN_ALPHA = 0.1
learning_rate_server = 1.0

ENABLE_ALPHA_FILTERING = True

BINARY = False
IID = True
DIRICHLET_ALPHA = 1.0

BASE_SEED = 123
NUM_ROUNDS = 15

GPU_PER_CLIENT = 0.5 if torch.cuda.is_available() else 0.0
CPUS_PER_CLIENT = max(1, (os.cpu_count() or 2) // 2)

ENABLE_LABEL_FLIP = False
MALICIOUS_FRAC = 0.0
FLIP_PROB = 0.0
FLIP_MODE = "random"
SOURCE_CLASS = 0
TARGET_CLASS = 1
POISON_SEED = 123
MALICIOUS_CLIENTS = set()

Using device: cuda

## 3. Data loading

In [3]:
def load_dataset(file_path, target_multiclass, normal_class, binary,
                 drop_cols, test_size=0.3, random_state=42):
    df = pd.read_csv(file_path)
    df = df.drop_duplicates()

    df = df.dropna(subset=[target_multiclass])
    numeric_cols = df.select_dtypes(include=[np.number]).columns
    categorical_cols = df.select_dtypes(exclude=[np.number]).columns
    for col in numeric_cols:
        if df[col].isnull().any():
            df[col] = df[col].fillna(df[col].median())
    for col in categorical_cols:
        if df[col].isnull().any():
            mode_val = df[col].mode()
            df[col] = df[col].fillna(mode_val[0] if not mode_val.empty else "Unknown")

    y_multi = df[target_multiclass].astype(str).str.strip()
    if binary:
        y = np.where(y_multi.str.lower() == normal_class.lower(), "Benign", "Attack")
        y = pd.Series(y, index=df.index)
    else:
        y = y_multi

    X = df.drop(columns=drop_cols, errors="ignore").copy()

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=test_size, random_state=random_state, stratify=y)

    non_numeric_cols = list(
        set(X_train.select_dtypes(exclude=[np.number]).columns.tolist())
        | set(X_test.select_dtypes(exclude=[np.number]).columns.tolist()))
    feature_encoders = {}
    for col in non_numeric_cols:
        le_col = LabelEncoder()
        le_col.fit(X_train[col].astype(str))
        feature_encoders[col] = le_col
        mapping = {cls: idx for idx, cls in enumerate(le_col.classes_)}
        X_train[col] = le_col.transform(X_train[col].astype(str))
        X_test[col] = X_test[col].astype(str).map(mapping).fillna(-1).astype(int)

    def safe_numeric(df_):
        df_ = df_.apply(lambda c: c.map(lambda v: str(v).strip() if isinstance(v, str) else v))
        df_ = df_.apply(pd.to_numeric, errors="coerce")
        return df_.replace([np.inf, -np.inf], np.nan).fillna(0)

    X_train = safe_numeric(X_train)
    X_test = safe_numeric(X_test)

    global INPUT_DIM
    INPUT_DIM = X_train.shape[1]

    y_train = pd.Series(np.asarray(y_train)).astype(str).str.strip()
    y_test = pd.Series(np.asarray(y_test)).astype(str).str.strip()
    label_encoder = LabelEncoder()
    y_train_enc = label_encoder.fit_transform(y_train.values)
    y_test_enc = label_encoder.transform(y_test.values)
    class_names = label_encoder.classes_
    num_classes = len(class_names)

    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train.values.astype(np.float64))
    X_test_scaled = scaler.transform(X_test.values.astype(np.float64))

    train_dataset = TensorDataset(torch.from_numpy(X_train_scaled).float(),
                                  torch.from_numpy(y_train_enc).long())
    test_dataset = TensorDataset(torch.from_numpy(X_test_scaled).float(),
                                 torch.from_numpy(y_test_enc).long())
    print(f"Classes ({num_classes}): {list(class_names)}")
    print(f"Features: {INPUT_DIM} | Train: {len(train_dataset)} | Test: {len(test_dataset)}")
    return (train_dataset, test_dataset, class_names, num_classes,
            scaler, label_encoder, feature_encoders)


(
    train_dataset, test_dataset, class_names, NUM_CLASSES,
    scaler, label_encoder, feature_encoders,
) = load_dataset(CSV_PATH, TARGET_MULTICLASS, NORMAL_CLASS, BINARY, DROP_COLS)

Classes (4): ['DDoS/DoS', 'Normal', 'Reconnaissance', 'Theft']
Features: 23 | Train: 35791 | Test: 15339

## 4. Evaluation history

In [4]:
eval_loss_history = []
eval_accuracy_history = []
eval_precision_history = []
eval_recall_history = []
eval_f1_history = []
eval_grad_divergence_history = []
eval_rounds = []

## 5. Partitioning (IID and Non-IID)

In [5]:
def partition_dataset_iid(dataset, num_partitions):
    labels = np.array([dataset[i][1] for i in range(len(dataset))])
    indices_by_class = [[] for _ in range(NUM_CLASSES)]
    for idx, label in enumerate(labels):
        indices_by_class[label].append(idx)
    partitions = [[] for _ in range(num_partitions)]
    for c in range(NUM_CLASSES):
        indices = indices_by_class[c]
        np.random.shuffle(indices)
        per = len(indices) // num_partitions
        rem = len(indices) % num_partitions
        start = 0
        for p in range(num_partitions):
            extra = 1 if p < rem else 0
            end = start + per + extra
            partitions[p].extend(indices[start:end])
            start = end
    for p in range(num_partitions):
        np.random.shuffle(partitions[p])
    return partitions


def partition_dataset_dirichlet(dataset, num_partitions, dirichlet_alpha):
    labels = np.array([dataset[i][1] for i in range(len(dataset))])
    indices_by_class = [[] for _ in range(NUM_CLASSES)]
    for idx, label in enumerate(labels):
        indices_by_class[label].append(idx)
    partitions = [[] for _ in range(num_partitions)]
    for c in range(NUM_CLASSES):
        indices = indices_by_class[c]
        np.random.shuffle(indices)
        proportions = np.random.dirichlet([dirichlet_alpha] * num_partitions)
        counts = (proportions * len(indices)).astype(int)
        diff = len(indices) - counts.sum()
        if diff > 0:
            for k in np.argsort(proportions)[-diff:]:
                counts[k] += 1
        elif diff < 0:
            for k in np.argsort(proportions)[:abs(diff)]:
                if counts[k] > 0:
                    counts[k] -= 1
        start = 0
        for p in range(num_partitions):
            end = start + counts[p]
            partitions[p].extend(indices[start:end])
            start = end
    for p in range(num_partitions):
        np.random.shuffle(partitions[p])
    return partitions


def partition_dataset(dataset, num_partitions):
    if IID:
        return partition_dataset_iid(dataset, num_partitions)
    return partition_dataset_dirichlet(dataset, num_partitions, DIRICHLET_ALPHA)


train_partitions = partition_dataset(train_dataset, NUM_PARTITIONS)
print(f"Created {len(train_partitions)} partitions ({'IID' if IID else 'Non-IID'})")

Created 10 partitions (IID)

## 6. Model, ensemble, and residual loss

In [6]:
class model(nn.Module):
    def __init__(self, INPUT_DIM, num_classes=NUM_CLASSES):
        super().__init__()
        self.fc1 = nn.Linear(INPUT_DIM, 50)
        self.fc2 = nn.Linear(50, 25)
        self.fc3 = nn.Linear(25, num_classes)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        return self.fc3(x)


class BoostFLEnsemble:
    def __init__(self, f0, device):
        self.f0 = f0.to(device)
        self.base_learners = []
        self.alphas = []
        self.device = device

    def add_learner(self, model_params, alpha):
        new_learner = model(INPUT_DIM, NUM_CLASSES).to(self.device)
        state_dict = new_learner.state_dict()
        new_state_dict = {
            k: torch.tensor(v).to(self.device) if isinstance(v, np.ndarray) else v.to(self.device)
            for k, v in zip(state_dict.keys(), model_params)}
        new_learner.load_state_dict(new_state_dict)
        new_learner.eval()
        self.base_learners.append(new_learner)
        self.alphas.append(alpha)

    def predict(self, x):
        with torch.no_grad():
            out = self.f0.unsqueeze(0).expand(x.size(0), -1).clone()
            if self.base_learners and self.alphas:
                total_alpha = sum(self.alphas)
                if total_alpha > EPSILON:
                    weighted_sum = torch.zeros_like(out)
                    for m, alpha in zip(self.base_learners, self.alphas):
                        m.eval()
                        weighted_sum += (alpha / total_alpha) * m(x)
                    out = out + weighted_sum
            return out

    def get_ensemble_info(self):
        return {"num_learners": len(self.base_learners),
                "alphas": self.alphas,
                "total_alpha": sum(self.alphas) if self.alphas else 0}


class ResidualLoss(nn.Module):
    def forward(self, predictions, residuals):
        return F.smooth_l1_loss(predictions, residuals)


class ClientEnsemble:
    def __init__(self, base_learners, alphas, f0):
        self.base_learners = base_learners
        self.alphas = alphas
        self.f0 = f0

    def predict(self, x):
        with torch.no_grad():
            out = self.f0.unsqueeze(0).expand(x.size(0), -1).clone()
            if self.base_learners and self.alphas:
                total_alpha = sum(self.alphas)
                if total_alpha > EPSILON:
                    weighted_sum = torch.zeros_like(out)
                    for m, alpha in zip(self.base_learners, self.alphas):
                        m.eval()
                        weighted_sum += (alpha / total_alpha) * m(x)
                    out = out + weighted_sum
            return out

## 7. Label-flipping wrapper

In [7]:
class LabelFlippedDataset(torch.utils.data.Dataset):
    def __init__(self, base_dataset, num_classes, flip_prob=1.0, mode="random",
                 source_class=0, target_class=1, seed=0):
        self.base = base_dataset
        self.num_classes = int(num_classes)
        self.flip_prob = float(flip_prob)
        self.mode = str(mode)
        self.source_class = int(source_class)
        self.target_class = int(target_class)
        self.rng = np.random.RandomState(seed)

    def __len__(self):
        return len(self.base)

    def _flip_label(self, y):
        if self.mode == "targeted":
            return self.target_class if y == self.source_class else y
        new_y = y
        while new_y == y:
            new_y = int(self.rng.randint(0, self.num_classes))
        return new_y

    def __getitem__(self, idx):
        x, y = self.base[idx]
        y_int = int(y.item()) if torch.is_tensor(y) else int(y)
        if self.rng.rand() < self.flip_prob:
            y_int = self._flip_label(y_int)
        return x, torch.tensor(y_int, dtype=torch.long)

## 8. Flower client

In [ ]:
def client_fn(cid):
    cid_int = int(cid)
    partition_indices = train_partitions[cid_int]
    base_client_subset = Subset(train_dataset, partition_indices)

    is_malicious = (ENABLE_LABEL_FLIP and (cid_int in MALICIOUS_CLIENTS))
    if is_malicious:
        client_dataset = LabelFlippedDataset(
            base_dataset=base_client_subset, num_classes=NUM_CLASSES,
            flip_prob=FLIP_PROB, mode=FLIP_MODE,
            source_class=SOURCE_CLASS, target_class=TARGET_CLASS,
            seed=POISON_SEED + cid_int)
    else:
        client_dataset = base_client_subset

    train_dataloader = DataLoader(client_dataset, batch_size=BATCH_SIZE, shuffle=True)

    f_t = model(INPUT_DIM, NUM_CLASSES).to(device)
    f0 = torch.randn(NUM_CLASSES, device=device) * 0.01
    residual_loss_fn = ResidualLoss()
    classification_loss_fn = nn.CrossEntropyLoss()
    learners = []
    alphas = []

    class FlowerClient(fl.client.NumPyClient):
        def __init__(self):
            self.learners = learners
            self.alphas = alphas
            self.f0 = f0
            self.f_t = f_t
            self.device = device
            self.train_dataset = client_dataset
            self.residual_loss_fn = residual_loss_fn
            self.classification_loss_fn = classification_loss_fn
            self.is_malicious = is_malicious

        def get_parameters(self, config=None):
            return [val.cpu().numpy() for val in self.f_t.state_dict().values()]

        def fit(self, parameters, config):
            state_dict = self.f_t.state_dict()
            new_state_dict = {k: torch.tensor(v).to(self.device)
                              for k, v in zip(state_dict.keys(), parameters)}
            self.f_t.load_state_dict(new_state_dict)
            self.f_t.train()

            optimizer = optim.Adam(self.f_t.parameters(), lr=LEARNING_RATE, weight_decay=1e-4)
            ensemble = ClientEnsemble(self.learners, self.alphas, self.f0)

            total_residual_loss = 0.0
            for epoch in range(EPOCHS):
                epoch_residual_loss = 0.0
                num_batches = 0
                for x_batch, y_batch in train_dataloader:
                    x_batch = x_batch.to(self.device)
                    y_batch = y_batch.to(self.device)
                    with torch.no_grad():
                        ensemble_logits = ensemble.predict(x_batch)
                        ensemble_probs = torch.softmax(ensemble_logits, dim=1)
                        y_one_hot = torch.zeros(y_batch.size(0), NUM_CLASSES, device=self.device)
                        y_one_hot.scatter_(1, y_batch.unsqueeze(1), 1)
                        residuals = y_one_hot - ensemble_probs
                    optimizer.zero_grad()
                    weak_learner_logits = self.f_t(x_batch)
                    #weak_learner_probs = torch.softmax(weak_learner_logits, dim=1)
                    loss = self.residual_loss_fn(weak_learner_logits, residuals)
                    loss.backward()
                    #torch.nn.utils.clip_grad_norm_(self.f_t.parameters(), max_norm=5.0)
                    optimizer.step()
                    epoch_residual_loss += loss.item()
                    num_batches += 1
                total_residual_loss += epoch_residual_loss

            avg_residual_loss = (total_residual_loss / (EPOCHS * len(train_dataloader))
                                 if len(train_dataloader) > 0 else 1.0)
            avg_residual_loss = max(avg_residual_loss, EPSILON)
            avg_residual_loss = min(avg_residual_loss, 10.0)
            alpha_t = 1.0 / (1.0 + avg_residual_loss)
            alpha_t = max(MIN_ALPHA, min(MAX_ALPHA, alpha_t))

            new_learner = model(INPUT_DIM, NUM_CLASSES).to(device)
            new_learner.load_state_dict(self.f_t.state_dict())
            self.learners.append(new_learner)
            self.alphas.append(alpha_t)

            global_params = [torch.tensor(p).to(self.device) for p in parameters]
            local_params = list(self.f_t.state_dict().values())
            grad_divergence = sum((lp - gp).norm().item()
                                  for lp, gp in zip(local_params, global_params))

            return [val.cpu().numpy() for val in self.f_t.state_dict().values()], \
                len(self.train_dataset), {
                    "grad_divergence": grad_divergence,
                    "residual_loss": avg_residual_loss,
                    "alpha": alpha_t,
                    "is_malicious": int(is_malicious),
                }

        def evaluate(self, parameters, config):
            return 0.0, len(self.train_dataset), {"loss": 0.0}

    return FlowerClient().to_client()

## 9. Boosting strategy with alpha filtering

In [9]:
class BoostingStrategy(fl.server.strategy.FedAvg):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.current_global_params = None
        self.round_count = 0
        self.global_f0 = torch.randn(NUM_CLASSES, device=device) * 0.01
        self.global_ensemble = BoostFLEnsemble(self.global_f0, device)
        self.test_dataloader = DataLoader(test_dataset, batch_size=128, shuffle=False)
        self.classification_loss_fn = nn.CrossEntropyLoss()
        self.global_learners_history = []
        self.global_alphas_history = []
        self.mal_alpha_rounds = []
        self.mal_alpha_lists = []
        self.mal_alpha_means = []
        self.benign_alpha_lists = []
        self.benign_alpha_means = []
        self.num_filtered_per_round = []
        self.num_filtered_malicious_per_round = []
        self.alpha_threshold_per_round = []

    def initialize_parameters(self, client_manager):
        initial_model = model(INPUT_DIM, NUM_CLASSES).to(device)
        initial_params = [val.cpu().numpy() for val in initial_model.state_dict().values()]
        self.current_global_params = fl.common.ndarrays_to_parameters(initial_params)
        return self.current_global_params

    def evaluate_ensemble(self):
        y_true, y_pred = [], []
        total_loss = 0.0
        total_samples = 0
        with torch.no_grad():
            for x_batch, y_batch in self.test_dataloader:
                x_batch, y_batch = x_batch.to(device), y_batch.to(device)
                ensemble_logits = self.global_ensemble.predict(x_batch)
                loss = self.classification_loss_fn(ensemble_logits, y_batch)
                total_loss += loss.item() * y_batch.size(0)
                total_samples += y_batch.size(0)
                _, preds = torch.max(ensemble_logits, 1)
                y_true.extend(y_batch.cpu().numpy())
                y_pred.extend(preds.cpu().numpy())
        return {
            "loss": total_loss / total_samples if total_samples > 0 else 0.0,
            "accuracy": accuracy_score(y_true, y_pred) if y_true else 0.0,
            "precision": precision_score(y_true, y_pred, average="macro", zero_division=0) if y_true else 0.0,
            "recall": recall_score(y_true, y_pred, average="macro", zero_division=0) if y_true else 0.0,
            "f1_score": f1_score(y_true, y_pred, average="macro", zero_division=0) if y_true else 0.0,
        }

    def aggregate_fit(self, rnd, results, failures):
        print(f"[Round {rnd}] {len(results)} clients succeeded, {len(failures)} failed")
        self.round_count = rnd
        if not results:
            return self.current_global_params, {}

        if self.current_global_params is None:
            initial_model = model(INPUT_DIM, NUM_CLASSES).to(device)
            initial_params = [val.cpu().numpy() for val in initial_model.state_dict().values()]
            self.current_global_params = fl.common.ndarrays_to_parameters(initial_params)

        old_global_params = fl.common.parameters_to_ndarrays(self.current_global_params)
        weighted_updates = [np.zeros_like(p) for p in old_global_params]
        sum_alpha = 0.0
        num_examples_total = 0
        residual_losses = []
        alphas = []
        grad_divergences = []
        valid_results = []

        for client_res in results:
            try:
                if isinstance(client_res, tuple):
                    if len(client_res) == 3:
                        parameters, num_examples, metrics = client_res
                    elif len(client_res) == 2:
                        _, fit_res = client_res
                        parameters = fit_res.parameters
                        num_examples = fit_res.num_examples
                        metrics = fit_res.metrics
                    else:
                        continue
                else:
                    parameters = client_res.parameters
                    num_examples = getattr(client_res, "num_examples", 0)
                    metrics = getattr(client_res, "metrics", {})
                if not isinstance(metrics, dict) and hasattr(metrics, "metrics"):
                    metrics = metrics.metrics

                alpha = float(metrics.get("alpha", 1.0))
                if math.isnan(alpha) or math.isinf(alpha) or alpha <= 0:
                    alpha = 1.0
                alpha = max(MIN_ALPHA, min(MAX_ALPHA, alpha))

                if "grad_divergence" in metrics:
                    grad_div = float(metrics["grad_divergence"])
                    if not (math.isnan(grad_div) or math.isinf(grad_div)):
                        grad_divergences.append(grad_div)

                local_params = fl.common.parameters_to_ndarrays(parameters)
                if len(local_params) != len(old_global_params):
                    continue
                valid_results.append((local_params, alpha, num_examples, metrics))
            except Exception as e:
                print(f"Error processing client result: {e}")
                continue

        if not valid_results:
            return self.current_global_params, {}

        if ENABLE_ALPHA_FILTERING and len(valid_results) > 1:
            all_alphas = [alpha for _, alpha, _, _ in valid_results]
            alpha_mean = np.mean(all_alphas)
            print(f"[Alpha Filtering] Mean alpha: {alpha_mean:.4f}")
            filtered_results = []
            filtered_out_malicious = 0
            filtered_out_total = 0
            for local_params, alpha, num_examples, metrics in valid_results:
                is_mal = int(metrics.get("is_malicious", 0))
                if alpha >= alpha_mean:
                    filtered_results.append((local_params, alpha, num_examples, metrics))
                else:
                    filtered_out_total += 1
                    if is_mal == 1:
                        filtered_out_malicious += 1
                    print(f"[Alpha Filtering] Filtered client alpha={alpha:.4f} (malicious={bool(is_mal)})")
            print(f"[Alpha Filtering] Filtered {filtered_out_total} clients "
                  f"({filtered_out_malicious} malicious), kept {len(filtered_results)}")
            self.num_filtered_per_round.append(filtered_out_total)
            self.num_filtered_malicious_per_round.append(filtered_out_malicious)
            self.alpha_threshold_per_round.append(alpha_mean)
            if filtered_results:
                valid_results = filtered_results
            else:
                self.num_filtered_per_round[-1] = 0
                self.num_filtered_malicious_per_round[-1] = 0
        else:
            self.num_filtered_per_round.append(0)
            self.num_filtered_malicious_per_round.append(0)
            self.alpha_threshold_per_round.append(0.0)

        mal_alphas_round = []
        benign_alphas_round = []
        for local_params, alpha, num_examples, metrics in valid_results:
            param_diff = [lp - gp for lp, gp in zip(local_params, old_global_params)]
            for i in range(len(weighted_updates)):
                weighted_updates[i] += alpha * param_diff[i]
            sum_alpha += alpha
            num_examples_total += num_examples
            if "residual_loss" in metrics:
                loss_value = float(metrics["residual_loss"])
                if not (math.isnan(loss_value) or math.isinf(loss_value)):
                    residual_losses.append(loss_value)
            alphas.append(alpha)
            if int(metrics.get("is_malicious", 0)) == 1:
                mal_alphas_round.append(alpha)
            else:
                benign_alphas_round.append(alpha)

        if sum_alpha > EPSILON:
            for i in range(len(weighted_updates)):
                weighted_updates[i] = (weighted_updates[i] / sum_alpha) * learning_rate_server
        else:
            weighted_updates = [np.zeros_like(p) for p in old_global_params]

        new_global_params = [gp + weighted_updates[i] for i, gp in enumerate(old_global_params)]
        self.current_global_params = fl.common.ndarrays_to_parameters(new_global_params)

        mean_alpha = np.mean(alphas) if alphas else 1.0
        self.global_ensemble.add_learner(new_global_params, mean_alpha)
        self.global_learners_history.append(new_global_params)
        self.global_alphas_history.append(mean_alpha)

        ensemble_info = self.global_ensemble.get_ensemble_info()
        test_metrics = self.evaluate_ensemble()

        eval_rounds.append(rnd)
        eval_loss_history.append(test_metrics["loss"])
        eval_accuracy_history.append(test_metrics["accuracy"])
        eval_precision_history.append(test_metrics["precision"])
        eval_recall_history.append(test_metrics["recall"])
        eval_f1_history.append(test_metrics["f1_score"])

        print(f"[Round {rnd}] learners={ensemble_info['num_learners']} "
              f"acc={test_metrics['accuracy']:.4f} f1={test_metrics['f1_score']:.4f}")

        mean_residual_loss = np.mean(residual_losses) if residual_losses else 0.0
        mean_grad_div = np.mean(grad_divergences) if grad_divergences else 0.0

        self.mal_alpha_rounds.append(rnd)
        self.mal_alpha_lists.append(mal_alphas_round)
        self.mal_alpha_means.append(float(np.mean(mal_alphas_round)) if mal_alphas_round else np.nan)
        self.benign_alpha_lists.append(benign_alphas_round)
        self.benign_alpha_means.append(float(np.mean(benign_alphas_round)) if benign_alphas_round else np.nan)

        return self.current_global_params, {
            "num_examples": num_examples_total,
            "residual_loss": mean_residual_loss,
            "alpha": mean_alpha,
            "grad_divergence": mean_grad_div,
            "ensemble_size": ensemble_info["num_learners"],
            "mal_alpha_mean_round": self.mal_alpha_means[-1],
            "mal_alpha_count_round": int(len(mal_alphas_round)),
            "benign_alpha_mean_round": self.benign_alpha_means[-1],
            "num_filtered": self.num_filtered_per_round[-1],
            "num_filtered_malicious": self.num_filtered_malicious_per_round[-1],
            "alpha_threshold": self.alpha_threshold_per_round[-1],
            **test_metrics,
        }

    def aggregate_evaluate(self, rnd, results, failures):
        return 0.0, {}

## 10. Experiment runner

In [10]:
def reset_eval_histories():
    global eval_loss_history, eval_accuracy_history, eval_precision_history
    global eval_recall_history, eval_f1_history, eval_grad_divergence_history, eval_rounds
    eval_loss_history = []
    eval_accuracy_history = []
    eval_precision_history = []
    eval_recall_history = []
    eval_f1_history = []
    eval_grad_divergence_history = []
    eval_rounds = []


def set_poisoning(mal_frac, flip_prob, mode="random", seed=123, source_class=0, target_class=1):
    global ENABLE_LABEL_FLIP, MALICIOUS_FRAC, FLIP_PROB, FLIP_MODE
    global SOURCE_CLASS, TARGET_CLASS, POISON_SEED, MALICIOUS_CLIENTS
    POISON_SEED = int(seed)
    ENABLE_LABEL_FLIP = (mal_frac > 0) and (flip_prob > 0)
    MALICIOUS_FRAC = float(mal_frac)
    FLIP_PROB = float(flip_prob)
    FLIP_MODE = str(mode)
    SOURCE_CLASS = int(source_class)
    TARGET_CLASS = int(target_class)
    rng = np.random.RandomState(POISON_SEED)
    num_mal = int(NUM_CLIENTS * MALICIOUS_FRAC)
    if num_mal <= 0:
        MALICIOUS_CLIENTS = set()
    else:
        MALICIOUS_CLIENTS = set(rng.choice(np.arange(NUM_CLIENTS), size=num_mal, replace=False).tolist())
    print(f"[Poison] mal_frac={MALICIOUS_FRAC}, flip_prob={FLIP_PROB}, "
          f"malicious_clients={sorted(MALICIOUS_CLIENTS)}")


def run_one_experiment(num_rounds=15, seed=123):
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    reset_eval_histories()

    local_strategy = BoostingStrategy(
        fraction_fit=1.0,
        min_fit_clients=NUM_CLIENTS,
        min_available_clients=NUM_CLIENTS,
    )
    fl.simulation.start_simulation(
        client_fn=client_fn,
        num_clients=NUM_CLIENTS,
        config=fl.server.ServerConfig(num_rounds=num_rounds),
        strategy=local_strategy,
        client_resources={"num_cpus": CPUS_PER_CLIENT, "num_gpus": GPU_PER_CLIENT},
    )
    if len(eval_rounds) == 0:
        return None

    final = {
        "final_round": eval_rounds[-1],
        "final_loss": float(eval_loss_history[-1]),
        "final_accuracy": float(eval_accuracy_history[-1]),
        "final_precision": float(eval_precision_history[-1]),
        "final_recall": float(eval_recall_history[-1]),
        "final_f1": float(eval_f1_history[-1]),
        "ensemble_size": int(local_strategy.global_ensemble.get_ensemble_info()["num_learners"]),
        "rounds": list(eval_rounds),
        "acc_curve": list(eval_accuracy_history),
        "loss_curve": list(eval_loss_history),
    }
    mal_means = np.array(local_strategy.mal_alpha_means, dtype=float)
    benign_means = np.array(local_strategy.benign_alpha_means, dtype=float)
    mal_alpha_last_list = local_strategy.mal_alpha_lists[-1] if local_strategy.mal_alpha_lists else []
    benign_alpha_last_list = local_strategy.benign_alpha_lists[-1] if local_strategy.benign_alpha_lists else []
    final.update({
        "mal_alpha_mean_last_round": float(mal_means[~np.isnan(mal_means)][-1]) if np.any(~np.isnan(mal_means)) else np.nan,
        "benign_alpha_mean_last_round": float(benign_means[~np.isnan(benign_means)][-1]) if np.any(~np.isnan(benign_means)) else np.nan,
        "mal_alpha_mean_over_rounds": float(np.nanmean(mal_means)) if np.any(~np.isnan(mal_means)) else np.nan,
        "benign_alpha_mean_over_rounds": float(np.nanmean(benign_means)) if np.any(~np.isnan(benign_means)) else np.nan,
        "mal_alpha_list_last_round": json.dumps([float(a) for a in mal_alpha_last_list]),
        "benign_alpha_list_last_round": json.dumps([float(a) for a in benign_alpha_last_list]),
        "total_filtered": int(sum(local_strategy.num_filtered_per_round)),
        "total_filtered_malicious": int(sum(local_strategy.num_filtered_malicious_per_round)),
        "avg_filtered_per_round": float(np.mean(local_strategy.num_filtered_per_round)),
        "avg_filtered_malicious_per_round": float(np.mean(local_strategy.num_filtered_malicious_per_round)),
    })
    return final

In [12]:
mal_fracs = [0.1, 0.3, 0.5, 0.7]
flip_probs = [1.0]

results = []
curves = {}
for mf in mal_fracs:
    for fp in flip_probs:
        set_poisoning(mal_frac=mf, flip_prob=fp, mode="random", seed=BASE_SEED)
        res = run_one_experiment(num_rounds=NUM_ROUNDS, seed=BASE_SEED)
        if res is None:
            continue
        row = {
            "mode": "random",
            "mal_frac": mf,
            "flip_prob": fp,
            "final_accuracy": res["final_accuracy"],
            "final_f1": res["final_f1"],
            "final_precision": res["final_precision"],
            "final_recall": res["final_recall"],
            "final_loss": res["final_loss"],
            "ensemble_size": res["ensemble_size"],
            "mal_alpha_mean_last_round": res["mal_alpha_mean_last_round"],
            "mal_alpha_mean_over_rounds": res["mal_alpha_mean_over_rounds"],
            "benign_alpha_mean_last_round": res["benign_alpha_mean_last_round"],
            "benign_alpha_mean_over_rounds": res["benign_alpha_mean_over_rounds"],
            "total_filtered": res["total_filtered"],
            "total_filtered_malicious": res["total_filtered_malicious"],
            "avg_filtered_per_round": res["avg_filtered_per_round"],
            "avg_filtered_malicious_per_round": res["avg_filtered_malicious_per_round"],
        }
        results.append(row)
        curves[(mf, fp)] = (res["rounds"], res["acc_curve"])
        print(f"[Sweep] mal_frac={mf:.2f} acc={row['final_accuracy']:.4f} "
              f"filtered_mal={row['total_filtered_malicious']}/{row['total_filtered']}")

df_results = pd.DataFrame(results).sort_values(["mal_frac", "flip_prob"]).reset_index(drop=True)
#df_results.to_csv("boostfl_botiot_labelflip.csv", index=False)
df_results

WARNING :   DEPRECATED FEATURE: flwr.simulation.start_simulation() is deprecated.
	Instead, use the `flwr run` CLI command to start a local simulation in your Flower app, as shown for example below:

		$ flwr new  # Create a new Flower app from a template

		$ flwr run  # Run the Flower app in Simulation Mode

	Using `start_simulation()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.

INFO :      Starting Flower simulation, config: num_rounds=15, no round_timeout

[Poison] mal_frac=0.1, flip_prob=1.0, malicious_clients=[4]

2026-09-17 15:04:10,621	INFO worker.py:1771 -- Started a local Ray instance.
INFO :      Flower VCE: Ray initialized with resources: {'node:172.24.90.50': 1.0, 'accelerator_type:G': 1.0, 'node:__internal_head__': 1.0, 'CPU': 20.0, 'object_store_memory': 1742358528.0, 'memory': 3484717056.0, 'GPU': 1.0}
INFO :      Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
INFO :      Flower VCE: Resources for each Virtual Client: {'num_cpus': 10, 'num_gpus': 0.5}
INFO :      Flower VCE: Creating VirtualClientEngineActorPool with 2 actors
INFO :      [INIT]
INFO :      Using initial global parameters provided by strategy
INFO :      Starting evaluation of initial global parameters
INFO :      Evaluation returned no results (`None`)
INFO :
INFO :      [ROUND 1]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=615705) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context`
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)             This is a deprecated feature. It will be removed
(ClientAppActor pid=615705)             entirely in future versions of Flower.
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 8x across cluster]
(ClientAppActor pid=615705)             This is a deprecated feature. It will be removed [repeated 8x across cluster]
(ClientAppActor pid=615705)             entirely in future versions of Flower. [repeated 8x across cluster]
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
INFO :      aggregate_fit: received 10 results and 0 failures
INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)

[Round 1] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9820
[Alpha Filtering] Filtered client alpha=0.9208 (malicious=True)
[Alpha Filtering] Filtered 1 clients (1 malicious), kept 9
[Round 1] learners=1 acc=0.9889 f1=0.9812

(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 2]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=615705)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=615705)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
INFO :      aggregate_fit: received 10 results and 0 failures
INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)

[Round 2] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9895
[Alpha Filtering] Filtered client alpha=0.9164 (malicious=True)
[Alpha Filtering] Filtered 1 clients (1 malicious), kept 9
[Round 2] learners=2 acc=0.9922 f1=0.9870

(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 3]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 19x across cluster]
(ClientAppActor pid=615705)             This is a deprecated feature. It will be removed [repeated 19x across cluster]
(ClientAppActor pid=615705)             entirely in future versions of Flower. [repeated 19x across cluster]
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 3] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9901
[Alpha Filtering] Filtered client alpha=0.9164 (malicious=True)
[Alpha Filtering] Filtered 1 clients (1 malicious), kept 9

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 4]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 3] learners=3 acc=0.9937 f1=0.9895

(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 19x across cluster]
(ClientAppActor pid=615704)             This is a deprecated feature. It will be removed [repeated 19x across cluster]
(ClientAppActor pid=615704)             entirely in future versions of Flower. [repeated 19x across cluster]
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 4] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9904
[Alpha Filtering] Filtered client alpha=0.9168 (malicious=True)
[Alpha Filtering] Filtered 1 clients (1 malicious), kept 9

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 5]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 4] learners=4 acc=0.9941 f1=0.9908

(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=615704)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=615704)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 5] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9905
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered 1 clients (1 malicious), kept 9

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 10x across cluster]
(ClientAppActor pid=615705)             This is a deprecated feature. It will be removed [repeated 10x across cluster]
(ClientAppActor pid=615705)             entirely in future versions of Flower. [repeated 10x across cluster]
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 6]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 5] learners=5 acc=0.9940 f1=0.9907

(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 6] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9906
[Alpha Filtering] Filtered client alpha=0.9168 (malicious=True)
[Alpha Filtering] Filtered 1 clients (1 malicious), kept 9

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 19x across cluster]
(ClientAppActor pid=615705)             This is a deprecated feature. It will be removed [repeated 19x across cluster]
(ClientAppActor pid=615705)             entirely in future versions of Flower. [repeated 19x across cluster]
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 7]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 6] learners=6 acc=0.9941 f1=0.9915

(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 7] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9907
[Alpha Filtering] Filtered client alpha=0.9172 (malicious=True)
[Alpha Filtering] Filtered 1 clients (1 malicious), kept 9

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 22x across cluster]
(ClientAppActor pid=615705)             This is a deprecated feature. It will be removed [repeated 22x across cluster]
(ClientAppActor pid=615705)             entirely in future versions of Flower. [repeated 22x across cluster]
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 8]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 7] learners=7 acc=0.9943 f1=0.9917

(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 8] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9907
[Alpha Filtering] Filtered client alpha=0.9172 (malicious=True)
[Alpha Filtering] Filtered 1 clients (1 malicious), kept 9

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=615705)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=615705)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 9]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 8] learners=8 acc=0.9943 f1=0.9917

(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 9] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9908
[Alpha Filtering] Filtered client alpha=0.9173 (malicious=True)
[Alpha Filtering] Filtered 1 clients (1 malicious), kept 9

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 20x across cluster]
(ClientAppActor pid=615705)             This is a deprecated feature. It will be removed [repeated 20x across cluster]
(ClientAppActor pid=615705)             entirely in future versions of Flower. [repeated 20x across cluster]
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 10]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 9] learners=9 acc=0.9945 f1=0.9919

(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 10] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9908
[Alpha Filtering] Filtered client alpha=0.9175 (malicious=True)
[Alpha Filtering] Filtered 1 clients (1 malicious), kept 9

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 19x across cluster]
(ClientAppActor pid=615705)             This is a deprecated feature. It will be removed [repeated 19x across cluster]
(ClientAppActor pid=615705)             entirely in future versions of Flower. [repeated 19x across cluster]
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 11]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 10] learners=10 acc=0.9947 f1=0.9920

(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 11] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9908
[Alpha Filtering] Filtered client alpha=0.9173 (malicious=True)
[Alpha Filtering] Filtered 1 clients (1 malicious), kept 9

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 21x across cluster]
(ClientAppActor pid=615705)             This is a deprecated feature. It will be removed [repeated 21x across cluster]
(ClientAppActor pid=615705)             entirely in future versions of Flower. [repeated 21x across cluster]
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 12]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 11] learners=11 acc=0.9947 f1=0.9921

(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=615705)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=615705)             entirely in future versions of Flower. [repeated 18x across cluster]
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 12] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9908
[Alpha Filtering] Filtered client alpha=0.9173 (malicious=True)
[Alpha Filtering] Filtered 1 clients (1 malicious), kept 9

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 13]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 12] learners=12 acc=0.9947 f1=0.9921

(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 17x across cluster]
(ClientAppActor pid=615705)             This is a deprecated feature. It will be removed [repeated 17x across cluster]
(ClientAppActor pid=615705)             entirely in future versions of Flower. [repeated 17x across cluster]
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 13] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9909
[Alpha Filtering] Filtered client alpha=0.9175 (malicious=True)
[Alpha Filtering] Filtered 1 clients (1 malicious), kept 9

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 14]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 13] learners=13 acc=0.9948 f1=0.9922

(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=615705)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=615705)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 14] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9909
[Alpha Filtering] Filtered client alpha=0.9176 (malicious=True)
[Alpha Filtering] Filtered 1 clients (1 malicious), kept 9

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 15]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 14] learners=14 acc=0.9948 f1=0.9922

(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=615705)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=615705)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 15] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9909
[Alpha Filtering] Filtered client alpha=0.9175 (malicious=True)
[Alpha Filtering] Filtered 1 clients (1 malicious), kept 9

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)
(ClientAppActor pid=615705) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 11x across cluster]
(ClientAppActor pid=615705)             This is a deprecated feature. It will be removed [repeated 11x across cluster]
(ClientAppActor pid=615705)             entirely in future versions of Flower. [repeated 11x across cluster]
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
(ClientAppActor pid=615704)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [SUMMARY]
INFO :      Run finished 15 round(s) in 99.49s
INFO :      	History (loss, distributed):
INFO :      		round 1: 0.0
INFO :      		round 2: 0.0
INFO :      		round 3: 0.0
INFO :      		round 4: 0.0
INFO :      		round 5: 0.0
INFO :      		round 6: 0.0
INFO :      		round 7: 0.0
INFO :      		round 8: 0.0
INFO :      		round 9: 0.0
INFO :      		round 10: 0.0
INFO :      		round 11: 0.0
INFO :      		round 12: 0.0
INFO :      		round 13: 0.0
INFO :      		round 14: 0.0
INFO :      		round 15: 0.0
INFO :      	History (metrics, distributed, fit):
INFO :      	{'accuracy': [(1, 0.9888519460199492),
INFO :      	              (2, 0.9921768042245257),
INFO :      	              (3, 0.9937414433796206),
INFO :      	              (4, 0.9940674098702653),
INFO :      	              (5, 0.9940022165721364),
INFO :      	              (6, 0.9940674098702653),
INFO :      	              (7, 0.9942629897646522),
INFO :      	              (8, 0.9943281830627811),
INFO :      	              (9, 0.994523762957168),
INFO :      	              (10, 0.9946541495534259),
INFO :      	              (11, 0.9947193428515548),
INFO :      	              (12, 0.9947193428515548),
INFO :      	              (13, 0.9947845361496838),
INFO :      	              (14, 0.9948497294478128),
INFO :      	              (15, 0.9948497294478128)],
INFO :      	 'alpha': [(1, np.float64(0.9888137675435892)),
INFO :      	           (2, np.float64(0.9976184233135525)),
INFO :      	           (3, np.float64(0.9982836232220832)),
INFO :      	           (4, np.float64(0.9985571535854731)),
INFO :      	           (5, np.float64(0.9987024376839706)),
INFO :      	           (6, np.float64(0.9987941031118542)),
INFO :      	           (7, np.float64(0.9988587801469829)),
INFO :      	           (8, np.float64(0.9988998727553484)),
INFO :      	           (9, np.float64(0.9989529365009171)),
INFO :      	           (10, np.float64(0.9989608143781104)),
INFO :      	           (11, np.float64(0.9989971839645269)),
INFO :      	           (12, np.float64(0.9990012468416669)),
INFO :      	           (13, np.float64(0.9990246622885641)),
INFO :      	           (14, np.float64(0.9990360079208381)),
INFO :      	           (15, np.float64(0.9990533894893735))],
INFO :      	 'alpha_threshold': [(1, np.float64(0.9820085770420949)),
INFO :      	                     (2, np.float64(0.9894920428516869)),
INFO :      	                     (3, np.float64(0.9900947753289036)),
INFO :      	                     (4, np.float64(0.9903855789232885)),
INFO :      	                     (5, np.float64(0.9905302057388488)),
INFO :      	                     (6, np.float64(0.9905977101387642)),
INFO :      	                     (7, np.float64(0.9906940130198363)),
INFO :      	                     (8, np.float64(0.9907339842383098)),
INFO :      	                     (9, np.float64(0.9907866983730023)),
INFO :      	                     (10, np.float64(0.9908126809618288)),
INFO :      	                     (11, np.float64(0.9908254713612502)),
INFO :      	                     (12, np.float64(0.9908339596963536)),
INFO :      	                     (13, np.float64(0.9908723085902084)),
INFO :      	                     (14, np.float64(0.9908884458061475)),
INFO :      	                     (15, np.float64(0.9909014704835137))],
INFO :      	 'benign_alpha_mean_round': [(1, 0.9888137675435892),
INFO :      	                             (2, 0.9976184233135525),
INFO :      	                             (3, 0.9982836232220832),
INFO :      	                             (4, 0.9985571535854731),
INFO :      	                             (5, 0.9987024376839706),
INFO :      	                             (6, 0.9987941031118542),
INFO :      	                             (7, 0.9988587801469829),
INFO :      	                             (8, 0.9988998727553484),
INFO :      	                             (9, 0.9989529365009171),
INFO :      	                             (10, 0.9989608143781104),
INFO :      	                             (11, 0.9989971839645269),
INFO :      	                             (12, 0.9990012468416669),
INFO :      	                             (13, 0.9990246622885641),
INFO :      	                             (14, 0.9990360079208381),
INFO :      	                             (15, 0.9990533894893735)],
INFO :      	 'ensemble_size': [(1, 1),
INFO :      	                   (2, 2),
INFO :      	                   (3, 3),
INFO :      	                   (4, 4),
INFO :      	                   (5, 5),
INFO :      	                   (6, 6),
INFO :      	                   (7, 7),
INFO :      	                   (8, 8),
INFO :      	                   (9, 9),
INFO :      	                   (10, 10),
INFO :      	                   (11, 11),
INFO :      	                   (12, 12),
INFO :      	                   (13, 13),
INFO :      	                   (14, 14),
INFO :      	                   (15, 15)],
INFO :      	 'f1_score': [(1, 0.9812277072183313),
INFO :      	              (2, 0.9870135665561893),
INFO :      	              (3, 0.9894884522298075),
INFO :      	              (4, 0.9907553228110842),
INFO :      	              (5, 0.9906882632186104),
INFO :      	              (6, 0.9914654147013031),
INFO :      	              (7, 0.991657160965946),
INFO :      	              (8, 0.9917221444998653),
INFO :      	              (9, 0.9919167424865988),
INFO :      	              (10, 0.9920446325103418),
INFO :      	              (11, 0.992108594777809),
INFO :      	              (12, 0.992108594777809),
INFO :      	              (13, 0.9921734375527492),
INFO :      	              (14, 0.9922382684122525),
INFO :      	              (15, 0.9922382684122525)],
INFO :      	 'grad_divergence': [(1, np.float64(5.265092527121306)),
INFO :      	                     (2, np.float64(3.122701385617256)),
INFO :      	                     (3, np.float64(2.2438747277483344)),
INFO :      	                     (4, np.float64(1.8547550424933434)),
INFO :      	                     (5, np.float64(1.5784499181434513)),
INFO :      	                     (6, np.float64(1.4592275476083159)),
INFO :      	                     (7, np.float64(1.3965953001752496)),
INFO :      	                     (8, np.float64(1.3598991302773356)),
INFO :      	                     (9, np.float64(1.3181112282909453)),
INFO :      	                     (10, np.float64(1.2985106287524104)),
INFO :      	                     (11, np.float64(1.2596647002734245)),
INFO :      	                     (12, np.float64(1.2378772187046707)),
INFO :      	                     (13, np.float64(1.2291031615808605)),
INFO :      	                     (14, np.float64(1.2144018792547286)),
INFO :      	                     (15, np.float64(1.2025672351010144))],
INFO :      	 'loss': [(1, 0.776236709757869),
INFO :      	          (2, 0.767579597567741),
INFO :      	          (3, 0.7645774654851245),
INFO :      	          (4, 0.7633554241796991),
INFO :      	          (5, 0.7614745087788044),
INFO :      	          (6, 0.7602144456125781),
INFO :      	          (7, 0.7591241475881269),
INFO :      	          (8, 0.7582016119676258),
INFO :      	          (9, 0.7578143598094697),
INFO :      	          (10, 0.7573624814230473),
INFO :      	          (11, 0.7569974674940094),
INFO :      	          (12, 0.7567557783106313),
INFO :      	          (13, 0.7565733557015092),
INFO :      	          (14, 0.7563842408457654),
INFO :      	          (15, 0.755868181565865)],
INFO :      	 'mal_alpha_count_round': [(1, 0),
INFO :      	                           (2, 0),
INFO :      	                           (3, 0),
INFO :      	                           (4, 0),
INFO :      	                           (5, 0),
INFO :      	                           (6, 0),
INFO :      	                           (7, 0),
INFO :      	                           (8, 0),
INFO :      	                           (9, 0),
INFO :      	                           (10, 0),
INFO :      	                           (11, 0),
INFO :      	                           (12, 0),
INFO :      	                           (13, 0),
INFO :      	                           (14, 0),
INFO :      	                           (15, 0)],
INFO :      	 'mal_alpha_mean_round': [(1, nan),
INFO :      	                          (2, nan),
(ClientAppActor pid=615705)
(ClientAppActor pid=615705)

[Round 15] learners=15 acc=0.9948 f1=0.9922

INFO :      	                          (3, nan),
INFO :      	                          (4, nan),
INFO :      	                          (5, nan),
INFO :      	                          (6, nan),
INFO :      	                          (7, nan),
INFO :      	                          (8, nan),
INFO :      	                          (9, nan),
INFO :      	                          (10, nan),
INFO :      	                          (11, nan),
INFO :      	                          (12, nan),
INFO :      	                          (13, nan),
INFO :      	                          (14, nan),
INFO :      	                          (15, nan)],
INFO :      	 'num_examples': [(1, 32212),
INFO :      	                  (2, 32212),
INFO :      	                  (3, 32212),
INFO :      	                  (4, 32212),
INFO :      	                  (5, 32212),
INFO :      	                  (6, 32212),
INFO :      	                  (7, 32212),
INFO :      	                  (8, 32212),
INFO :      	                  (9, 32212),
INFO :      	                  (10, 32212),
INFO :      	                  (11, 32212),
INFO :      	                  (12, 32212),
INFO :      	                  (13, 32212),
INFO :      	                  (14, 32212),
INFO :      	                  (15, 32212)],
INFO :      	 'num_filtered': [(1, 1),
INFO :      	                  (2, 1),
INFO :      	                  (3, 1),
INFO :      	                  (4, 1),
INFO :      	                  (5, 1),
INFO :      	                  (6, 1),
INFO :      	                  (7, 1),
INFO :      	                  (8, 1),
INFO :      	                  (9, 1),
INFO :      	                  (10, 1),
INFO :      	                  (11, 1),
INFO :      	                  (12, 1),
INFO :      	                  (13, 1),
INFO :      	                  (14, 1),
INFO :      	                  (15, 1)],
INFO :      	 'num_filtered_malicious': [(1, 1),
INFO :      	                            (2, 1),
INFO :      	                            (3, 1),
INFO :      	                            (4, 1),
INFO :      	                            (5, 1),
INFO :      	                            (6, 1),
INFO :      	                            (7, 1),
INFO :      	                            (8, 1),
INFO :      	                            (9, 1),
INFO :      	                            (10, 1),
INFO :      	                            (11, 1),
INFO :      	                            (12, 1),
INFO :      	                            (13, 1),
INFO :      	                            (14, 1),
INFO :      	                            (15, 1)],
INFO :      	 'precision': [(1, 0.9759243843154444),
INFO :      	               (2, 0.9839660242524759),
INFO :      	               (3, 0.9875069366505437),
INFO :      	               (4, 0.9896299724624188),
INFO :      	               (5, 0.9896717004658284),
INFO :      	               (6, 0.9911789669287436),
INFO :      	               (7, 0.9914364187374166),
INFO :      	               (8, 0.9914794592802244),
INFO :      	               (9, 0.9916078252342884),
INFO :      	               (10, 0.9917794814144182),
INFO :      	               (11, 0.991865398784392),
INFO :      	               (12, 0.991865398784392),
INFO :      	               (13, 0.991908104602824),
INFO :      	               (14, 0.9919508233826692),
INFO :      	               (15, 0.9919508233826692)],
INFO :      	 'recall': [(1, 0.9867695907213742),
INFO :      	            (2, 0.9901356035079069),
INFO :      	            (3, 0.9915008381103052),
INFO :      	            (4, 0.9918917887448377),
INFO :      	            (5, 0.9917131591022716),
INFO :      	            (6, 0.9917548257689384),
INFO :      	            (7, 0.9918798257689384),
INFO :      	            (8, 0.9919671467609048),
INFO :      	            (9, 0.9922291097368042),
INFO :      	            (10, 0.9923124430701376),
INFO :      	            (11, 0.9923541097368043),
INFO :      	            (12, 0.9923541097368043),
INFO :      	            (13, 0.9924414307287708),
INFO :      	            (14, 0.9925287517207372),
INFO :      	            (15, 0.9925287517207372)],
INFO :      	 'residual_loss': [(1, np.float64(0.011313051210830358)),
INFO :      	                   (2, np.float64(0.0023873171949696645)),
INFO :      	                   (3, np.float64(0.0017193707936828092)),
INFO :      	                   (4, np.float64(0.0014449657765576304)),
INFO :      	                   (5, np.float64(0.0012992807823586248)),
INFO :      	                   (6, np.float64(0.0012073882247824214)),
INFO :      	                   (7, np.float64(0.0011425585030049243)),
INFO :      	                   (8, np.float64(0.0011013730198245622)),
INFO :      	                   (9, np.float64(0.001048195734277951)),
INFO :      	                   (10, np.float64(0.0010402997177935604)),
INFO :      	                   (11, np.float64(0.0010038531966283842)),
INFO :      	                   (12, np.float64(0.0009997860593063115)),
INFO :      	                   (13, np.float64(0.0009763197581609318)),
INFO :      	                   (14, np.float64(0.0009649493371203529)),
INFO :      	                   (15, np.float64(0.0009475364430799678))]}
INFO :
WARNING :   DEPRECATED FEATURE: flwr.simulation.start_simulation() is deprecated.
	Instead, use the `flwr run` CLI command to start a local simulation in your Flower app, as shown for example below:

		$ flwr new  # Create a new Flower app from a template

		$ flwr run  # Run the Flower app in Simulation Mode

	Using `start_simulation()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.

INFO :      Starting Flower simulation, config: num_rounds=15, no round_timeout
(ClientAppActor pid=615705) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 6x across cluster]
(ClientAppActor pid=615705)             This is a deprecated feature. It will be removed [repeated 6x across cluster]
(ClientAppActor pid=615705)             entirely in future versions of Flower. [repeated 6x across cluster]

[Sweep] mal_frac=0.10 acc=0.9948 filtered_mal=15/15
[Poison] mal_frac=0.3, flip_prob=1.0, malicious_clients=[0, 4, 7]

2026-09-17 15:05:53,809	INFO worker.py:1771 -- Started a local Ray instance.
INFO :      Flower VCE: Ray initialized with resources: {'node:172.24.90.50': 1.0, 'accelerator_type:G': 1.0, 'node:__internal_head__': 1.0, 'CPU': 20.0, 'memory': 3477602304.0, 'object_store_memory': 1738801152.0, 'GPU': 1.0}
INFO :      Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
INFO :      Flower VCE: Resources for each Virtual Client: {'num_cpus': 10, 'num_gpus': 0.5}
INFO :      Flower VCE: Creating VirtualClientEngineActorPool with 2 actors
INFO :      [INIT]
INFO :      Using initial global parameters provided by strategy
INFO :      Starting evaluation of initial global parameters
INFO :      Evaluation returned no results (`None`)
INFO :
INFO :      [ROUND 1]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=617773) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context`
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)             This is a deprecated feature. It will be removed
(ClientAppActor pid=617773)             entirely in future versions of Flower.
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 8x across cluster]
(ClientAppActor pid=617773)             This is a deprecated feature. It will be removed [repeated 8x across cluster]
(ClientAppActor pid=617773)             entirely in future versions of Flower. [repeated 8x across cluster]
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
INFO :      aggregate_fit: received 10 results and 0 failures
INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)

[Round 1] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9686
[Alpha Filtering] Filtered client alpha=0.9208 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9209 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9210 (malicious=True)
[Alpha Filtering] Filtered 3 clients (3 malicious), kept 7
[Round 1] learners=1 acc=0.9886 f1=0.9807

(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 2]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 19x across cluster]
(ClientAppActor pid=617773)             This is a deprecated feature. It will be removed [repeated 19x across cluster]
(ClientAppActor pid=617773)             entirely in future versions of Flower. [repeated 19x across cluster]
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
INFO :      aggregate_fit: received 10 results and 0 failures
INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)

[Round 2] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9734
[Alpha Filtering] Filtered client alpha=0.9166 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9164 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9167 (malicious=True)
[Alpha Filtering] Filtered 3 clients (3 malicious), kept 7
[Round 2] learners=2 acc=0.9916 f1=0.9871

(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 3]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=617774)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=617774)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 3] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9739
[Alpha Filtering] Filtered client alpha=0.9168 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9167 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9167 (malicious=True)
[Alpha Filtering] Filtered 3 clients (3 malicious), kept 7

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 4]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 3] learners=3 acc=0.9935 f1=0.9914

(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 17x across cluster]
(ClientAppActor pid=617773)             This is a deprecated feature. It will be removed [repeated 17x across cluster]
(ClientAppActor pid=617773)             entirely in future versions of Flower. [repeated 17x across cluster]
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 4] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9741
[Alpha Filtering] Filtered client alpha=0.9169 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9168 (malicious=True)
[Alpha Filtering] Filtered 3 clients (3 malicious), kept 7

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 9x across cluster]
(ClientAppActor pid=617773)             This is a deprecated feature. It will be removed [repeated 9x across cluster]
(ClientAppActor pid=617773)             entirely in future versions of Flower. [repeated 9x across cluster]
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 5]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 4] learners=4 acc=0.9943 f1=0.9924

(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=617773)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=617773)             entirely in future versions of Flower. [repeated 18x across cluster]
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 5] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9743
[Alpha Filtering] Filtered client alpha=0.9169 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered 3 clients (3 malicious), kept 7

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 6]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 5] learners=5 acc=0.9944 f1=0.9925

(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=617774)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=617774)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 6] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9743
[Alpha Filtering] Filtered client alpha=0.9172 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9172 (malicious=True)
[Alpha Filtering] Filtered 3 clients (3 malicious), kept 7

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 7]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 6] learners=6 acc=0.9939 f1=0.9918

(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=617774)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=617774)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 7] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9744
[Alpha Filtering] Filtered client alpha=0.9174 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9172 (malicious=True)
[Alpha Filtering] Filtered 3 clients (3 malicious), kept 7

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 8]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 7] learners=7 acc=0.9941 f1=0.9923

(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 17x across cluster]
(ClientAppActor pid=617773)             This is a deprecated feature. It will be removed [repeated 17x across cluster]
(ClientAppActor pid=617773)             entirely in future versions of Flower. [repeated 17x across cluster]
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 8] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9744
[Alpha Filtering] Filtered client alpha=0.9172 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9172 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9172 (malicious=True)
[Alpha Filtering] Filtered 3 clients (3 malicious), kept 7

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 9]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 8] learners=8 acc=0.9943 f1=0.9924

(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 14x across cluster]
(ClientAppActor pid=617773)             This is a deprecated feature. It will be removed [repeated 14x across cluster]
(ClientAppActor pid=617773)             entirely in future versions of Flower. [repeated 14x across cluster]
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 9] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9744
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered 3 clients (3 malicious), kept 7

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 10]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 9] learners=9 acc=0.9946 f1=0.9932

(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=617773)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=617773)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 10] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9745
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9172 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered 3 clients (3 malicious), kept 7

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 11]
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 20x across cluster]
(ClientAppActor pid=617773)             This is a deprecated feature. It will be removed [repeated 20x across cluster]
(ClientAppActor pid=617773)             entirely in future versions of Flower. [repeated 20x across cluster]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)

[Round 10] learners=10 acc=0.9947 f1=0.9933

(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 11] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9745
[Alpha Filtering] Filtered client alpha=0.9174 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9172 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9172 (malicious=True)
[Alpha Filtering] Filtered 3 clients (3 malicious), kept 7

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 16x across cluster]
(ClientAppActor pid=617773)             This is a deprecated feature. It will be removed [repeated 16x across cluster]
(ClientAppActor pid=617773)             entirely in future versions of Flower. [repeated 16x across cluster]
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 12]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 11] learners=11 acc=0.9947 f1=0.9933

(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 12] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9745
[Alpha Filtering] Filtered client alpha=0.9172 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered 3 clients (3 malicious), kept 7

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 20x across cluster]
(ClientAppActor pid=617773)             This is a deprecated feature. It will be removed [repeated 20x across cluster]
(ClientAppActor pid=617773)             entirely in future versions of Flower. [repeated 20x across cluster]
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 13]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 12] learners=12 acc=0.9949 f1=0.9935

(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=617773)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=617773)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 13] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9745
[Alpha Filtering] Filtered client alpha=0.9172 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9173 (malicious=True)
[Alpha Filtering] Filtered 3 clients (3 malicious), kept 7

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 14]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 13] learners=13 acc=0.9950 f1=0.9936

(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=617773)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=617773)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 14] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9746
[Alpha Filtering] Filtered client alpha=0.9173 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9174 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9172 (malicious=True)
[Alpha Filtering] Filtered 3 clients (3 malicious), kept 7

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 15]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 14] learners=14 acc=0.9950 f1=0.9934

(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=617773)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=617773)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 15] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9745
[Alpha Filtering] Filtered client alpha=0.9172 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9172 (malicious=True)
[Alpha Filtering] Filtered 3 clients (3 malicious), kept 7

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [SUMMARY]
INFO :      Run finished 15 round(s) in 100.38s
INFO :      	History (loss, distributed):
INFO :      		round 1: 0.0
INFO :      		round 2: 0.0
INFO :      		round 3: 0.0
INFO :      		round 4: 0.0
INFO :      		round 5: 0.0
INFO :      		round 6: 0.0
INFO :      		round 7: 0.0
INFO :      		round 8: 0.0
INFO :      		round 9: 0.0
INFO :      		round 10: 0.0
INFO :      		round 11: 0.0
INFO :      		round 12: 0.0
INFO :      		round 13: 0.0
INFO :      		round 14: 0.0
INFO :      		round 15: 0.0
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
(ClientAppActor pid=617773)
INFO :      	History (metrics, distributed, fit):
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
(ClientAppActor pid=617774)
INFO :      	{'accuracy': [(1, 0.9885911728274334),
INFO :      	              (2, 0.9915900645413651),
INFO :      	              (3, 0.9934806701871047),
INFO :      	              (4, 0.9942629897646522),
INFO :      	              (5, 0.9943933763609101),
INFO :      	              (6, 0.9939370232740075),
INFO :      	              (7, 0.9941326031683942),
INFO :      	              (8, 0.9942629897646522),
INFO :      	              (9, 0.994588956255297),
INFO :      	              (10, 0.9946541495534259),
INFO :      	              (11, 0.9947193428515548),
INFO :      	              (12, 0.9949149227459417),
INFO :      	              (13, 0.9949801160440707),
INFO :      	              (14, 0.9950453093421996),
INFO :      	              (15, 0.9951105026403285)],
INFO :      	 'alpha': [(1, np.float64(0.9890016715182585)),
INFO :      	           (2, np.float64(0.9977110014051863)),
INFO :      	           (3, np.float64(0.998384993807712)),
INFO :      	           (4, np.float64(0.9986414638660379)),
INFO :      	           (5, np.float64(0.9987737118496863)),
INFO :      	           (6, np.float64(0.9988683163573532)),
INFO :      	           (7, np.float64(0.998934219060856)),
INFO :      	           (8, np.float64(0.9989725353904276)),
INFO :      	           (9, np.float64(0.9990072744540643)),
INFO :      	           (10, np.float64(0.9990355727066599)),
INFO :      	           (11, np.float64(0.9990562854824806)),
INFO :      	           (12, np.float64(0.9990693188843741)),
INFO :      	           (13, np.float64(0.9990803841561752)),
INFO :      	           (14, np.float64(0.99908289189059)),
INFO :      	           (15, np.float64(0.9990985304450023))],
INFO :      	 'alpha_threshold': [(1, np.float64(0.9685667548154715)),
INFO :      	                     (2, np.float64(0.9733581382817569)),
INFO :      	                     (3, np.float64(0.9738914635865605)),
INFO :      	                     (4, np.float64(0.9741229402385491)),
INFO :      	                     (5, np.float64(0.9742562731359257)),
INFO :      	                     (6, np.float64(0.9743494250253975)),
INFO :      	                     (7, np.float64(0.9744139307637573)),
INFO :      	                     (8, np.float64(0.9744417160281733)),
INFO :      	                     (9, np.float64(0.9744229674487952)),
INFO :      	                     (10, np.float64(0.9744509174775944)),
INFO :      	                     (11, np.float64(0.9745297222446091)),
INFO :      	                     (12, np.float64(0.974479805190321)),
INFO :      	                     (13, np.float64(0.9745197453129013)),
INFO :      	                     (14, np.float64(0.9745562742695284)),
INFO :      	                     (15, np.float64(0.9745076223202039))],
INFO :      	 'benign_alpha_mean_round': [(1, 0.9890016715182585),
INFO :      	                             (2, 0.9977110014051863),
INFO :      	                             (3, 0.998384993807712),
INFO :      	                             (4, 0.9986414638660379),
INFO :      	                             (5, 0.9987737118496863),
INFO :      	                             (6, 0.9988683163573532),
INFO :      	                             (7, 0.998934219060856),
INFO :      	                             (8, 0.9989725353904276),
INFO :      	                             (9, 0.9990072744540643),
INFO :      	                             (10, 0.9990355727066599),
INFO :      	                             (11, 0.9990562854824806),
INFO :      	                             (12, 0.9990693188843741),
INFO :      	                             (13, 0.9990803841561752),
INFO :      	                             (14, 0.99908289189059),
INFO :      	                             (15, 0.9990985304450023)],
INFO :      	 'ensemble_size': [(1, 1),
INFO :      	                   (2, 2),
INFO :      	                   (3, 3),
INFO :      	                   (4, 4),
INFO :      	                   (5, 5),
INFO :      	                   (6, 6),
INFO :      	                   (7, 7),
INFO :      	                   (8, 8),
INFO :      	                   (9, 9),
INFO :      	                   (10, 10),
INFO :      	                   (11, 11),
INFO :      	                   (12, 12),
INFO :      	                   (13, 13),
INFO :      	                   (14, 14),
INFO :      	                   (15, 15)],
INFO :      	 'f1_score': [(1, 0.9807116642533323),
INFO :      	              (2, 0.9871353084015804),
INFO :      	              (3, 0.9913692267386026),
INFO :      	              (4, 0.99238115873299),
INFO :      	              (5, 0.992508828503213),
INFO :      	              (6, 0.9918148689374768),
INFO :      	              (7, 0.9922512821512748),
INFO :      	              (8, 0.9923791539228236),
INFO :      	              (9, 0.9931885907244735),
INFO :      	              (10, 0.9932534660046485),
INFO :      	              (11, 0.9933184195345539),
INFO :      	              (12, 0.9935112704837048),
INFO :      	              (13, 0.9935761068976162),
INFO :      	              (14, 0.9934007271859114),
INFO :      	              (15, 0.9937078077667514)],
INFO :      	 'grad_divergence': [(1, np.float64(4.864539618045091)),
INFO :      	                     (2, np.float64(3.3309194535017013)),
INFO :      	                     (3, np.float64(2.6207696234807374)),
INFO :      	                     (4, np.float64(2.2812988979741933)),
INFO :      	                     (5, np.float64(2.056569489464164)),
INFO :      	                     (6, np.float64(1.9360351702198386)),
INFO :      	                     (7, np.float64(1.8806406900286674)),
INFO :      	                     (8, np.float64(1.8388946993276476)),
INFO :      	                     (9, np.float64(1.8320872707292437)),
INFO :      	                     (10, np.float64(1.8281685944646597)),
INFO :      	                     (11, np.float64(1.8126601562835276)),
INFO :      	                     (12, np.float64(1.7726682530716062)),
INFO :      	                     (13, np.float64(1.7650150342844426)),
INFO :      	                     (14, np.float64(1.7929795689880847)),
INFO :      	                     (15, np.float64(1.8054009087383747))],
INFO :      	 'loss': [(1, 0.7795675221085743),
INFO :      	          (2, 0.7691884339458046),

[Round 15] learners=15 acc=0.9951 f1=0.9937

INFO :      	          (3, 0.7652598206320318),
INFO :      	          (4, 0.7634576960550044),
INFO :      	          (5, 0.7617057696673603),
INFO :      	          (6, 0.7606684242010474),
INFO :      	          (7, 0.7596235893036755),
INFO :      	          (8, 0.7585895237559577),
INFO :      	          (9, 0.7577084262411942),
INFO :      	          (10, 0.7572421187045436),
INFO :      	          (11, 0.7568538693158767),
INFO :      	          (12, 0.7569071720955044),
INFO :      	          (13, 0.7564037318987877),
INFO :      	          (14, 0.7560056485752992),
INFO :      	          (15, 0.7558704816507806)],
INFO :      	 'mal_alpha_count_round': [(1, 0),
INFO :      	                           (2, 0),
INFO :      	                           (3, 0),
INFO :      	                           (4, 0),
INFO :      	                           (5, 0),
INFO :      	                           (6, 0),
INFO :      	                           (7, 0),
INFO :      	                           (8, 0),
INFO :      	                           (9, 0),
INFO :      	                           (10, 0),
INFO :      	                           (11, 0),
INFO :      	                           (12, 0),
INFO :      	                           (13, 0),
INFO :      	                           (14, 0),
INFO :      	                           (15, 0)],
INFO :      	 'mal_alpha_mean_round': [(1, nan),
INFO :      	                          (2, nan),
INFO :      	                          (3, nan),
INFO :      	                          (4, nan),
INFO :      	                          (5, nan),
INFO :      	                          (6, nan),
INFO :      	                          (7, nan),
INFO :      	                          (8, nan),
INFO :      	                          (9, nan),
INFO :      	                          (10, nan),
INFO :      	                          (11, nan),
INFO :      	                          (12, nan),
INFO :      	                          (13, nan),
INFO :      	                          (14, nan),
INFO :      	                          (15, nan)],
INFO :      	 'num_examples': [(1, 25053),
INFO :      	                  (2, 25053),
INFO :      	                  (3, 25053),
INFO :      	                  (4, 25053),
INFO :      	                  (5, 25053),
INFO :      	                  (6, 25053),
INFO :      	                  (7, 25053),
INFO :      	                  (8, 25053),
INFO :      	                  (9, 25053),
INFO :      	                  (10, 25053),
INFO :      	                  (11, 25053),
INFO :      	                  (12, 25053),
INFO :      	                  (13, 25053),
INFO :      	                  (14, 25053),
INFO :      	                  (15, 25053)],
INFO :      	 'num_filtered': [(1, 3),
INFO :      	                  (2, 3),
INFO :      	                  (3, 3),
INFO :      	                  (4, 3),
INFO :      	                  (5, 3),
INFO :      	                  (6, 3),
INFO :      	                  (7, 3),
INFO :      	                  (8, 3),
INFO :      	                  (9, 3),
INFO :      	                  (10, 3),
INFO :      	                  (11, 3),
INFO :      	                  (12, 3),
INFO :      	                  (13, 3),
INFO :      	                  (14, 3),
INFO :      	                  (15, 3)],
INFO :      	 'num_filtered_malicious': [(1, 3),
INFO :      	                            (2, 3),
INFO :      	                            (3, 3),
INFO :      	                            (4, 3),
INFO :      	                            (5, 3),
INFO :      	                            (6, 3),
INFO :      	                            (7, 3),
INFO :      	                            (8, 3),
INFO :      	                            (9, 3),
INFO :      	                            (10, 3),
INFO :      	                            (11, 3),
INFO :      	                            (12, 3),
INFO :      	                            (13, 3),
INFO :      	                            (14, 3),
INFO :      	                            (15, 3)],
INFO :      	 'precision': [(1, 0.9759824806233919),
INFO :      	               (2, 0.984902341859724),
INFO :      	               (3, 0.9913687866383082),
INFO :      	               (4, 0.9926214098170579),
INFO :      	               (5, 0.9927920433646822),
INFO :      	               (6, 0.9920090410977281),
INFO :      	               (7, 0.9922706627923175),
INFO :      	               (8, 0.9924425759568869),
INFO :      	               (9, 0.9927944713650758),
INFO :      	               (10, 0.9928371087977749),
INFO :      	               (11, 0.9928800299188909),
INFO :      	               (12, 0.9930948403653942),
INFO :      	               (13, 0.9931374301912235),
INFO :      	               (14, 0.9927463818021912),
INFO :      	               (15, 0.9928378266331922)],
INFO :      	 'recall': [(1, 0.9856358372199736),
INFO :      	            (2, 0.9894140230664393),
INFO :      	            (3, 0.9913798257689383),
INFO :      	            (4, 0.9921537517207372),
INFO :      	            (5, 0.9922370850540705),
INFO :      	            (6, 0.9916258381103052),
INFO :      	            (7, 0.9922343815276722),
INFO :      	            (8, 0.9923177148610055),
INFO :      	            (9, 0.9935844436796724),
INFO :      	            (10, 0.9936717646716389),
INFO :      	            (11, 0.9937590856636053),
INFO :      	            (12, 0.9939297399889051),
INFO :      	            (13, 0.9940170609808716),
INFO :      	            (14, 0.9940587276475383),
INFO :      	            (15, 0.9945839377315719)],
INFO :      	 'residual_loss': [(1, np.float64(0.011120864406465054)),
INFO :      	                   (2, np.float64(0.002294266564539222)),
INFO :      	                   (3, np.float64(0.001617629096101006)),
INFO :      	                   (4, np.float64(0.0013603950956992926)),
INFO :      	                   (5, np.float64(0.0012278047059866438)),
INFO :      	                   (6, np.float64(0.0011329762743070185)),
INFO :      	                   (7, np.float64(0.0010669278915916688)),
INFO :      	                   (8, np.float64(0.001028531870031434)),
INFO :      	                   (9, np.float64(0.0009937219342330591)),
INFO :      	                   (10, np.float64(0.0009653711724208083)),
INFO :      	                   (11, np.float64(0.0009446179804016612)),
INFO :      	                   (12, np.float64(0.0009315592967572675)),
INFO :      	                   (13, np.float64(0.000920475538433326)),
INFO :      	                   (14, np.float64(0.0009179632879350924)),
INFO :      	                   (15, np.float64(0.0009022950695420411))]}
INFO :
WARNING :   DEPRECATED FEATURE: flwr.simulation.start_simulation() is deprecated.
	Instead, use the `flwr run` CLI command to start a local simulation in your Flower app, as shown for example below:

		$ flwr new  # Create a new Flower app from a template

		$ flwr run  # Run the Flower app in Simulation Mode

	Using `start_simulation()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.

INFO :      Starting Flower simulation, config: num_rounds=15, no round_timeout
(ClientAppActor pid=617774) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 15x across cluster]
(ClientAppActor pid=617774)             This is a deprecated feature. It will be removed [repeated 15x across cluster]
(ClientAppActor pid=617774)             entirely in future versions of Flower. [repeated 15x across cluster]

[Sweep] mal_frac=0.30 acc=0.9951 filtered_mal=45/45
[Poison] mal_frac=0.5, flip_prob=1.0, malicious_clients=[0, 4, 5, 7, 8]

2026-09-17 15:07:37,894	INFO worker.py:1771 -- Started a local Ray instance.
INFO :      Flower VCE: Ray initialized with resources: {'node:172.24.90.50': 1.0, 'accelerator_type:G': 1.0, 'node:__internal_head__': 1.0, 'CPU': 20.0, 'memory': 3458668955.0, 'object_store_memory': 1729334476.0, 'GPU': 1.0}
INFO :      Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
INFO :      Flower VCE: Resources for each Virtual Client: {'num_cpus': 10, 'num_gpus': 0.5}
INFO :      Flower VCE: Creating VirtualClientEngineActorPool with 2 actors
INFO :      [INIT]
INFO :      Using initial global parameters provided by strategy
INFO :      Starting evaluation of initial global parameters
INFO :      Evaluation returned no results (`None`)
INFO :
INFO :      [ROUND 1]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=619843) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context`
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)             This is a deprecated feature. It will be removed
(ClientAppActor pid=619843)             entirely in future versions of Flower.
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 7x across cluster]
(ClientAppActor pid=619843)             This is a deprecated feature. It will be removed [repeated 7x across cluster]
(ClientAppActor pid=619843)             entirely in future versions of Flower. [repeated 7x across cluster]
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
INFO :      aggregate_fit: received 10 results and 0 failures
INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)

[Round 1] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9549
[Alpha Filtering] Filtered client alpha=0.9206 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9209 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9208 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9210 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9210 (malicious=True)
[Alpha Filtering] Filtered 5 clients (5 malicious), kept 5
[Round 1] learners=1 acc=0.9884 f1=0.9810

(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 2]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 17x across cluster]
(ClientAppActor pid=619843)             This is a deprecated feature. It will be removed [repeated 17x across cluster]
(ClientAppActor pid=619843)             entirely in future versions of Flower. [repeated 17x across cluster]
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
INFO :      aggregate_fit: received 10 results and 0 failures
INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)

[Round 2] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9570
[Alpha Filtering] Filtered client alpha=0.9163 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9165 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9161 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9165 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9163 (malicious=True)
[Alpha Filtering] Filtered 5 clients (5 malicious), kept 5
[Round 2] learners=2 acc=0.9917 f1=0.9870

(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 3]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=619843)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=619843)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 3] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9575
[Alpha Filtering] Filtered client alpha=0.9165 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9167 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9166 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9168 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9166 (malicious=True)
[Alpha Filtering] Filtered 5 clients (5 malicious), kept 5

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 4]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 3] learners=3 acc=0.9937 f1=0.9914

(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 12x across cluster]
(ClientAppActor pid=619843)             This is a deprecated feature. It will be removed [repeated 12x across cluster]
(ClientAppActor pid=619843)             entirely in future versions of Flower. [repeated 12x across cluster]
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 15x across cluster]
(ClientAppActor pid=619843)             This is a deprecated feature. It will be removed [repeated 15x across cluster]
(ClientAppActor pid=619843)             entirely in future versions of Flower. [repeated 15x across cluster]
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 4] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9578
[Alpha Filtering] Filtered client alpha=0.9168 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9168 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9169 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9166 (malicious=True)
[Alpha Filtering] Filtered 5 clients (5 malicious), kept 5

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 5]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 4] learners=4 acc=0.9939 f1=0.9918

(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 19x across cluster]
(ClientAppActor pid=619843)             This is a deprecated feature. It will be removed [repeated 19x across cluster]
(ClientAppActor pid=619843)             entirely in future versions of Flower. [repeated 19x across cluster]
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 5] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9579
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9169 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9169 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9168 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9169 (malicious=True)
[Alpha Filtering] Filtered 5 clients (5 malicious), kept 5

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 6]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 5] learners=5 acc=0.9940 f1=0.9919

(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=619843)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=619843)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 6] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9580
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9168 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered 5 clients (5 malicious), kept 5

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 7]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 6] learners=6 acc=0.9943 f1=0.9921

(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=619843)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=619843)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 7] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9580
[Alpha Filtering] Filtered client alpha=0.9172 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9169 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered 5 clients (5 malicious), kept 5

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 8]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 7] learners=7 acc=0.9943 f1=0.9921

(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=619843)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=619843)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 8] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9581
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9172 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9172 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered 5 clients (5 malicious), kept 5

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 9x across cluster]
(ClientAppActor pid=619843)             This is a deprecated feature. It will be removed [repeated 9x across cluster]
(ClientAppActor pid=619843)             entirely in future versions of Flower. [repeated 9x across cluster]
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 9]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 8] learners=8 acc=0.9946 f1=0.9925

(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 17x across cluster]
(ClientAppActor pid=619843)             This is a deprecated feature. It will be removed [repeated 17x across cluster]
(ClientAppActor pid=619843)             entirely in future versions of Flower. [repeated 17x across cluster]
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 9] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9581
[Alpha Filtering] Filtered client alpha=0.9173 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9173 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9173 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered 5 clients (5 malicious), kept 5

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 10]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 9] learners=9 acc=0.9946 f1=0.9925

(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=619842)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=619842)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 10] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9581
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9172 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered 5 clients (5 malicious), kept 5

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 11]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 10] learners=10 acc=0.9946 f1=0.9925

(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=619842)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=619842)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 11] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9582
[Alpha Filtering] Filtered client alpha=0.9174 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9172 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9172 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9174 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9174 (malicious=True)
[Alpha Filtering] Filtered 5 clients (5 malicious), kept 5

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 12]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 11] learners=11 acc=0.9948 f1=0.9931

(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=619843)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=619843)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 12] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9582
[Alpha Filtering] Filtered client alpha=0.9174 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9173 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9174 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9172 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered 5 clients (5 malicious), kept 5

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 9x across cluster]
(ClientAppActor pid=619843)             This is a deprecated feature. It will be removed [repeated 9x across cluster]
(ClientAppActor pid=619843)             entirely in future versions of Flower. [repeated 9x across cluster]
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 13]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 12] learners=12 acc=0.9950 f1=0.9938

(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=619842)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=619842)             entirely in future versions of Flower. [repeated 18x across cluster]
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 13] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9581
[Alpha Filtering] Filtered client alpha=0.9173 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered 5 clients (5 malicious), kept 5

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 14]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 13] learners=13 acc=0.9951 f1=0.9939

(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 17x across cluster]
(ClientAppActor pid=619843)             This is a deprecated feature. It will be removed [repeated 17x across cluster]
(ClientAppActor pid=619843)             entirely in future versions of Flower. [repeated 17x across cluster]
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 14] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9582
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9173 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9174 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered 5 clients (5 malicious), kept 5

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 15]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 14] learners=14 acc=0.9952 f1=0.9938

(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=619843)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=619843)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 15] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9580
[Alpha Filtering] Filtered client alpha=0.9167 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9166 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9167 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9167 (malicious=True)
[Alpha Filtering] Filtered 5 clients (5 malicious), kept 5

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [SUMMARY]
INFO :      Run finished 15 round(s) in 102.33s
INFO :      	History (loss, distributed):
INFO :      		round 1: 0.0
INFO :      		round 2: 0.0
INFO :      		round 3: 0.0
INFO :      		round 4: 0.0
INFO :      		round 5: 0.0
INFO :      		round 6: 0.0
INFO :      		round 7: 0.0
INFO :      		round 8: 0.0
INFO :      		round 9: 0.0
INFO :      		round 10: 0.0
INFO :      		round 11: 0.0
INFO :      		round 12: 0.0
INFO :      		round 13: 0.0
INFO :      		round 14: 0.0
INFO :      		round 15: 0.0
INFO :      	History (metrics, distributed, fit):
INFO :      	{'accuracy': [(1, 0.9883955929330465),
INFO :      	              (2, 0.9917204511376231),
INFO :      	              (3, 0.9937414433796206),
INFO :      	              (4, 0.9939370232740075),
INFO :      	              (5, 0.9940022165721364),
INFO :      	              (6, 0.9942629897646522),
INFO :      	              (7, 0.9942629897646522),
INFO :      	              (8, 0.994588956255297),
INFO :      	              (9, 0.994588956255297),
INFO :      	              (10, 0.994588956255297),
INFO :      	              (11, 0.9947845361496838),
INFO :      	              (12, 0.9949801160440707),
INFO :      	              (13, 0.9951105026403285),
INFO :      	              (14, 0.9952408892365865),
INFO :      	              (15, 0.9953060825347154)],
INFO :      	 'alpha': [(1, np.float64(0.9888730942088249)),
INFO :      	           (2, np.float64(0.9977515468863425)),
INFO :      	           (3, np.float64(0.9984350241874054)),
INFO :      	           (4, np.float64(0.9987185295488402)),
INFO :      	           (5, np.float64(0.9988695299330661)),
INFO :      	           (6, np.float64(0.9989415724164579)),
INFO :      	           (7, np.float64(0.9990025543601992)),
INFO :      	           (8, np.float64(0.9990465328277474)),
INFO :      	           (9, np.float64(0.9990710399276335)),
INFO :      	           (10, np.float64(0.999110753766179)),
INFO :      	           (11, np.float64(0.999127898592324)),
INFO :      	           (12, np.float64(0.9991457159645046)),
INFO :      	           (13, np.float64(0.9991612734305448)),
INFO :      	           (14, np.float64(0.9991733527418759)),
INFO :      	           (15, np.float64(0.9991717062136498))],
INFO :      	 'alpha_threshold': [(1, np.float64(0.954867108366501)),
INFO :      	                     (2, np.float64(0.9570455457398159)),
INFO :      	                     (3, np.float64(0.9575399016899937)),
INFO :      	                     (4, np.float64(0.95777485549232)),
INFO :      	                     (5, np.float64(0.9578793883881082)),
INFO :      	                     (6, np.float64(0.9579761240670152)),
INFO :      	                     (7, np.float64(0.9580285927397814)),
INFO :      	                     (8, np.float64(0.9580975795310731)),
INFO :      	                     (9, np.float64(0.9581199083842702)),
INFO :      	                     (10, np.float64(0.9580873910137054)),
INFO :      	                     (11, np.float64(0.958224737679988)),
INFO :      	                     (12, np.float64(0.9582094377283322)),
INFO :      	                     (13, np.float64(0.9581409696976166)),
INFO :      	                     (14, np.float64(0.9581939466630889)),
INFO :      	                     (15, np.float64(0.9579748784861106))],
INFO :      	 'benign_alpha_mean_round': [(1, 0.9888730942088249),
INFO :      	                             (2, 0.9977515468863425),
INFO :      	                             (3, 0.9984350241874054),
INFO :      	                             (4, 0.9987185295488402),
INFO :      	                             (5, 0.9988695299330661),
INFO :      	                             (6, 0.9989415724164579),
INFO :      	                             (7, 0.9990025543601992),
INFO :      	                             (8, 0.9990465328277474),
INFO :      	                             (9, 0.9990710399276335),
INFO :      	                             (10, 0.999110753766179),
INFO :      	                             (11, 0.999127898592324),
INFO :      	                             (12, 0.9991457159645046),
INFO :      	                             (13, 0.9991612734305448),
INFO :      	                             (14, 0.9991733527418759),
INFO :      	                             (15, 0.9991717062136498)],
INFO :      	 'ensemble_size': [(1, 1),
INFO :      	                   (2, 2),
INFO :      	                   (3, 3),
INFO :      	                   (4, 4),
INFO :      	                   (5, 5),
INFO :      	                   (6, 6),
INFO :      	                   (7, 7),
INFO :      	                   (8, 8),
INFO :      	                   (9, 9),
INFO :      	                   (10, 10),
INFO :      	                   (11, 11),
INFO :      	                   (12, 12),
INFO :      	                   (13, 13),
INFO :      	                   (14, 14),
INFO :      	                   (15, 15)],
INFO :      	 'f1_score': [(1, 0.9810307839300177),
INFO :      	              (2, 0.9870374926538776),
INFO :      	              (3, 0.9913891183754951),
INFO :      	              (4, 0.9918158854172548),
INFO :      	              (5, 0.9918797663737725),
INFO :      	              (6, 0.9921354049472788),
INFO :      	              (7, 0.9921354049472788),
INFO :      	              (8, 0.9924579179382693),
INFO :      	              (9, 0.9924579179382693),
INFO :      	              (10, 0.9924579179382693),
INFO :      	              (11, 0.993112131279586),
INFO :      	              (12, 0.9937919174604032),
INFO :      	              (13, 0.9939208865107437),
INFO :      	              (14, 0.9937865980053694),
INFO :      	              (15, 0.993850651514912)],
INFO :      	 'grad_divergence': [(1, np.float64(4.4577068239450455)),
INFO :      	                     (2, np.float64(3.629727816581726)),
INFO :      	                     (3, np.float64(3.023699111305177)),
INFO :      	                     (4, np.float64(2.7164424303919077)),
INFO :      	                     (5, np.float64(2.5278791189193726)),
INFO :      	                     (6, np.float64(2.444247245416045)),
INFO :      	                     (7, np.float64(2.4140723878517747)),
INFO :      	                     (8, np.float64(2.3556498216465114)),
INFO :      	                     (9, np.float64(2.3777783840894697)),
INFO :      	                     (10, np.float64(2.367706559970975)),
INFO :      	                     (11, np.float64(2.3667284910567106)),
INFO :      	                     (12, np.float64(2.3807018591091036)),
INFO :      	                     (13, np.float64(2.3445839597843587)),
INFO :      	                     (14, np.float64(2.409886331111193)),
INFO :      	                     (15, np.float64(2.411368771456182))],
INFO :      	 'loss': [(1, 0.7739203263350296),
INFO :      	          (2, 0.7662984064492807),
INFO :      	          (3, 0.7629231280932037),
INFO :      	          (4, 0.7620598437912158),
INFO :      	          (5, 0.760984679704322),
INFO :      	          (6, 0.7606913115491891),
INFO :      	          (7, 0.7595104132445308),
INFO :      	          (8, 0.7591926363986601),
INFO :      	          (9, 0.7590629155177773),
INFO :      	          (10, 0.7591673428709671),
INFO :      	          (11, 0.75851743965729),
INFO :      	          (12, 0.7581314265638623),
INFO :      	          (13, 0.7577248094398806),
INFO :      	          (14, 0.7573171325119745),
INFO :      	          (15, 0.7568790621230279)],
INFO :      	 'mal_alpha_count_round': [(1, 0),
INFO :      	                           (2, 0),
INFO :      	                           (3, 0),
INFO :      	                           (4, 0),
INFO :      	                           (5, 0),
INFO :      	                           (6, 0),
INFO :      	                           (7, 0),
INFO :      	                           (8, 0),
INFO :      	                           (9, 0),
INFO :      	                           (10, 0),
INFO :      	                           (11, 0),
INFO :      	                           (12, 0),
INFO :      	                           (13, 0),
INFO :      	                           (14, 0),
INFO :      	                           (15, 0)],
INFO :      	 'mal_alpha_mean_round': [(1, nan),
INFO :      	                          (2, nan),
INFO :      	                          (3, nan),
INFO :      	                          (4, nan),
INFO :      	                          (5, nan),
INFO :      	                          (6, nan),
INFO :      	                          (7, nan),
INFO :      	                          (8, nan),
INFO :      	                          (9, nan),
INFO :      	                          (10, nan),
INFO :      	                          (11, nan),
INFO :      	                          (12, nan),
INFO :      	                          (13, nan),
INFO :      	                          (14, nan),
INFO :      	                          (15, nan)],
INFO :      	 'num_examples': [(1, 17895),
INFO :      	                  (2, 17895),
INFO :      	                  (3, 17895),
INFO :      	                  (4, 17895),
INFO :      	                  (5, 17895),
INFO :      	                  (6, 17895),
INFO :      	                  (7, 17895),
(ClientAppActor pid=619843)
(ClientAppActor pid=619843)
INFO :      	                  (8, 17895),
INFO :      	                  (9, 17895),
(ClientAppActor pid=619842)
(ClientAppActor pid=619842)
INFO :      	                  (10, 17895),
INFO :      	                  (11, 17895),
INFO :      	                  (12, 17895),
INFO :      	                  (13, 17895),
INFO :      	                  (14, 17895),
INFO :      	                  (15, 17895)],
INFO :      	 'num_filtered': [(1, 5),

[Round 15] learners=15 acc=0.9953 f1=0.9939

INFO :      	                  (2, 5),
INFO :      	                  (3, 5),
INFO :      	                  (4, 5),
INFO :      	                  (5, 5),
INFO :      	                  (6, 5),
INFO :      	                  (7, 5),
INFO :      	                  (8, 5),
INFO :      	                  (9, 5),
INFO :      	                  (10, 5),
INFO :      	                  (11, 5),
INFO :      	                  (12, 5),
INFO :      	                  (13, 5),
INFO :      	                  (14, 5),
INFO :      	                  (15, 5)],
INFO :      	 'num_filtered_malicious': [(1, 5),
INFO :      	                            (2, 5),
INFO :      	                            (3, 5),
INFO :      	                            (4, 5),
INFO :      	                            (5, 5),
INFO :      	                            (6, 5),
INFO :      	                            (7, 5),
INFO :      	                            (8, 5),
INFO :      	                            (9, 5),
INFO :      	                            (10, 5),
INFO :      	                            (11, 5),
INFO :      	                            (12, 5),
INFO :      	                            (13, 5),
INFO :      	                            (14, 5),
INFO :      	                            (15, 5)],
INFO :      	 'precision': [(1, 0.975375002621617),
INFO :      	               (2, 0.9842046349109024),
INFO :      	               (3, 0.9910608350428195),
INFO :      	               (4, 0.9919662690620945),
INFO :      	               (5, 0.9920519218960776),
INFO :      	               (6, 0.9923951270610871),
INFO :      	               (7, 0.9923951270610871),
INFO :      	               (8, 0.9926951552525044),
INFO :      	               (9, 0.9926951552525044),
INFO :      	               (10, 0.9926951552525044),
INFO :      	               (11, 0.9933943888502105),
INFO :      	               (12, 0.9936590263539765),
INFO :      	               (13, 0.9937880810679178),
INFO :      	               (14, 0.9934364479365266),
INFO :      	               (15, 0.9935227840405706)],
INFO :      	 'recall': [(1, 0.9869614674720744),
INFO :      	            (2, 0.9899352454918398),
INFO :      	            (3, 0.9917291097368043),
INFO :      	            (4, 0.991671492435605),
INFO :      	            (5, 0.9917131591022716),
INFO :      	            (6, 0.9918798257689384),
INFO :      	            (7, 0.9918798257689384),
INFO :      	            (8, 0.9922251220781712),
INFO :      	            (9, 0.9922251220781712),
INFO :      	            (10, 0.9922251220781712),
INFO :      	            (11, 0.9928336654955381),
INFO :      	            (12, 0.993925752330272),
INFO :      	            (13, 0.994054739988905),
INFO :      	            (14, 0.9941380733222385),
INFO :      	            (15, 0.9941797399889051)],
INFO :      	 'residual_loss': [(1, np.float64(0.011252547739142235)),
INFO :      	                   (2, np.float64(0.0022535397934864572)),
INFO :      	                   (3, np.float64(0.0015674366350529976)),
INFO :      	                   (4, np.float64(0.00128312318674099)),
INFO :      	                   (5, np.float64(0.0011317552594300652)),
INFO :      	                   (6, np.float64(0.0010595559344294867)),
INFO :      	                   (7, np.float64(0.000998449613185325)),
INFO :      	                   (8, np.float64(0.0009543841472226892)),
INFO :      	                   (9, np.float64(0.0009298298910354267)),
INFO :      	                   (10, np.float64(0.0008900423126228166)),
INFO :      	                   (11, np.float64(0.0008728666610867159)),
INFO :      	                   (12, np.float64(0.0008550198760901497)),
INFO :      	                   (13, np.float64(0.0008394357715477392)),
INFO :      	                   (14, np.float64(0.0008273357655402185)),
INFO :      	                   (15, np.float64(0.0008289867630495402))]}
INFO :
WARNING :   DEPRECATED FEATURE: flwr.simulation.start_simulation() is deprecated.
	Instead, use the `flwr run` CLI command to start a local simulation in your Flower app, as shown for example below:

		$ flwr new  # Create a new Flower app from a template

		$ flwr run  # Run the Flower app in Simulation Mode

	Using `start_simulation()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.

INFO :      Starting Flower simulation, config: num_rounds=15, no round_timeout
(ClientAppActor pid=619842) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 15x across cluster]
(ClientAppActor pid=619842)             This is a deprecated feature. It will be removed [repeated 15x across cluster]
(ClientAppActor pid=619842)             entirely in future versions of Flower. [repeated 15x across cluster]

[Sweep] mal_frac=0.50 acc=0.9953 filtered_mal=75/75
[Poison] mal_frac=0.7, flip_prob=1.0, malicious_clients=[0, 1, 3, 4, 5, 7, 8]

2026-09-17 15:09:23,996	INFO worker.py:1771 -- Started a local Ray instance.
INFO :      Flower VCE: Ray initialized with resources: {'node:172.24.90.50': 1.0, 'accelerator_type:G': 1.0, 'node:__internal_head__': 1.0, 'CPU': 20.0, 'object_store_memory': 1732069785.0, 'memory': 3464139572.0, 'GPU': 1.0}
INFO :      Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
INFO :      Flower VCE: Resources for each Virtual Client: {'num_cpus': 10, 'num_gpus': 0.5}
INFO :      Flower VCE: Creating VirtualClientEngineActorPool with 2 actors
INFO :      [INIT]
INFO :      Using initial global parameters provided by strategy
INFO :      Starting evaluation of initial global parameters
INFO :      Evaluation returned no results (`None`)
INFO :
INFO :      [ROUND 1]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=621918) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context`
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)             This is a deprecated feature. It will be removed
(ClientAppActor pid=621918)             entirely in future versions of Flower.
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 8x across cluster]
(ClientAppActor pid=621917)             This is a deprecated feature. It will be removed [repeated 8x across cluster]
(ClientAppActor pid=621917)             entirely in future versions of Flower. [repeated 8x across cluster]
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
INFO :      aggregate_fit: received 10 results and 0 failures
INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)

[Round 1] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9412
[Alpha Filtering] Filtered client alpha=0.9210 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9205 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9207 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9208 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9209 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9208 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9209 (malicious=True)
[Alpha Filtering] Filtered 7 clients (7 malicious), kept 3
[Round 1] learners=1 acc=0.9876 f1=0.9803

(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 2]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=621917)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=621917)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
INFO :      aggregate_fit: received 10 results and 0 failures
INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)

[Round 2] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9406
[Alpha Filtering] Filtered client alpha=0.9162 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9162 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9165 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9157 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9159 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9161 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9163 (malicious=True)
[Alpha Filtering] Filtered 7 clients (7 malicious), kept 3
[Round 2] learners=2 acc=0.9904 f1=0.9863

(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 3]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=621918)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=621918)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 3] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9411
[Alpha Filtering] Filtered client alpha=0.9162 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9163 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9168 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9165 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9163 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9167 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9165 (malicious=True)
[Alpha Filtering] Filtered 7 clients (7 malicious), kept 3

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 4]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 3] learners=3 acc=0.9924 f1=0.9898

(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=621917)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=621917)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 4] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9416
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9173 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered 7 clients (7 malicious), kept 3

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 9x across cluster]
(ClientAppActor pid=621918)             This is a deprecated feature. It will be removed [repeated 9x across cluster]
(ClientAppActor pid=621918)             entirely in future versions of Flower. [repeated 9x across cluster]
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 5]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 4] learners=4 acc=0.9937 f1=0.9925

(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=621918)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=621918)             entirely in future versions of Flower. [repeated 18x across cluster]
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 5] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9415
[Alpha Filtering] Filtered client alpha=0.9168 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9166 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9172 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9167 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9172 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9166 (malicious=True)
[Alpha Filtering] Filtered 7 clients (7 malicious), kept 3

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 6]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 5] learners=5 acc=0.9940 f1=0.9931

(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 17x across cluster]
(ClientAppActor pid=621917)             This is a deprecated feature. It will be removed [repeated 17x across cluster]
(ClientAppActor pid=621917)             entirely in future versions of Flower. [repeated 17x across cluster]
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 6] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9415
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9169 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9166 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9165 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9168 (malicious=True)
[Alpha Filtering] Filtered 7 clients (7 malicious), kept 3

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 7]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 6] learners=6 acc=0.9946 f1=0.9937

(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=621918)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=621918)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 7] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9417
[Alpha Filtering] Filtered client alpha=0.9172 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9172 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9172 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9169 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered 7 clients (7 malicious), kept 3

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 8]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 7] learners=7 acc=0.9950 f1=0.9941

(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=621918)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=621918)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 8] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9416
[Alpha Filtering] Filtered client alpha=0.9169 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9167 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9172 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9168 (malicious=True)
[Alpha Filtering] Filtered 7 clients (7 malicious), kept 3

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 10x across cluster]
(ClientAppActor pid=621918)             This is a deprecated feature. It will be removed [repeated 10x across cluster]
(ClientAppActor pid=621918)             entirely in future versions of Flower. [repeated 10x across cluster]
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 9]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 8] learners=8 acc=0.9952 f1=0.9943

(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 16x across cluster]
(ClientAppActor pid=621917)             This is a deprecated feature. It will be removed [repeated 16x across cluster]
(ClientAppActor pid=621917)             entirely in future versions of Flower. [repeated 16x across cluster]
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 9] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9417
[Alpha Filtering] Filtered client alpha=0.9173 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9166 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9169 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9173 (malicious=True)
[Alpha Filtering] Filtered 7 clients (7 malicious), kept 3

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 10]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 9] learners=9 acc=0.9954 f1=0.9944

(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=621917)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=621917)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 10] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9417
[Alpha Filtering] Filtered client alpha=0.9168 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9172 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9173 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered 7 clients (7 malicious), kept 3

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 11]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 10] learners=10 acc=0.9954 f1=0.9944

(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=621918)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=621918)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 11] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9415
[Alpha Filtering] Filtered client alpha=0.9167 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9169 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9168 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9166 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9169 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9168 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9168 (malicious=True)
[Alpha Filtering] Filtered 7 clients (7 malicious), kept 3

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 12]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 11] learners=11 acc=0.9952 f1=0.9943

(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=621918)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=621918)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 12] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9417
[Alpha Filtering] Filtered client alpha=0.9172 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9168 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9172 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9173 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9169 (malicious=True)
[Alpha Filtering] Filtered 7 clients (7 malicious), kept 3

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 11x across cluster]
(ClientAppActor pid=621918)             This is a deprecated feature. It will be removed [repeated 11x across cluster]
(ClientAppActor pid=621918)             entirely in future versions of Flower. [repeated 11x across cluster]
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 13]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 12] learners=12 acc=0.9952 f1=0.9942

(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 13] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9413
[Alpha Filtering] Filtered client alpha=0.9167 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9164 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9155 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9164 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9167 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9167 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9166 (malicious=True)
[Alpha Filtering] Filtered 7 clients (7 malicious), kept 3

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 17x across cluster]
(ClientAppActor pid=621918)             This is a deprecated feature. It will be removed [repeated 17x across cluster]
(ClientAppActor pid=621918)             entirely in future versions of Flower. [repeated 17x across cluster]
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 14]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 13] learners=13 acc=0.9952 f1=0.9942

(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 19x across cluster]
(ClientAppActor pid=621918)             This is a deprecated feature. It will be removed [repeated 19x across cluster]
(ClientAppActor pid=621918)             entirely in future versions of Flower. [repeated 19x across cluster]
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 14] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9417
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9169 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9171 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9170 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9167 (malicious=True)
[Alpha Filtering] Filtered 7 clients (7 malicious), kept 3

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 15]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 14] learners=14 acc=0.9953 f1=0.9943

(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 17x across cluster]
(ClientAppActor pid=621918)             This is a deprecated feature. It will be removed [repeated 17x across cluster]
(ClientAppActor pid=621918)             entirely in future versions of Flower. [repeated 17x across cluster]
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 15] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9411
[Alpha Filtering] Filtered client alpha=0.9161 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9165 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9160 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9166 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9167 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9150 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.9165 (malicious=True)
[Alpha Filtering] Filtered 7 clients (7 malicious), kept 3

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [SUMMARY]
INFO :      Run finished 15 round(s) in 104.25s
INFO :      	History (loss, distributed):
INFO :      		round 1: 0.0
INFO :      		round 2: 0.0
INFO :      		round 3: 0.0
INFO :      		round 4: 0.0
INFO :      		round 5: 0.0
INFO :      		round 6: 0.0
INFO :      		round 7: 0.0
INFO :      		round 8: 0.0
INFO :      		round 9: 0.0
INFO :      		round 10: 0.0
INFO :      		round 11: 0.0
INFO :      		round 12: 0.0
INFO :      		round 13: 0.0
INFO :      		round 14: 0.0
INFO :      		round 15: 0.0
INFO :      	History (metrics, distributed, fit):
INFO :      	{'accuracy': [(1, 0.9876132733554991),
INFO :      	              (2, 0.990416585175044),
INFO :      	              (3, 0.9923723841189126),
INFO :      	              (4, 0.9936762500814916),
INFO :      	              (5, 0.9940022165721364),
INFO :      	              (6, 0.994588956255297),
INFO :      	              (7, 0.9950453093421996),
INFO :      	              (8, 0.9952408892365865),
INFO :      	              (9, 0.9953712758328443),
INFO :      	              (10, 0.9953712758328443),
INFO :      	              (11, 0.9952408892365865),
INFO :      	              (12, 0.9951756959384576),
INFO :      	              (13, 0.9952408892365865),
INFO :      	              (14, 0.9953060825347154),
INFO :      	              (15, 0.9953712758328443)],
INFO :      	 'alpha': [(1, np.float64(0.9889075383160252)),
INFO :      	           (2, np.float64(0.9977995667192737)),
INFO :      	           (3, np.float64(0.9985219253369507)),
INFO :      	           (4, np.float64(0.998803980633214)),
INFO :      	           (5, np.float64(0.9989371385250799)),
INFO :      	           (6, np.float64(0.9990412902423346)),
INFO :      	           (7, np.float64(0.9990870502895586)),
INFO :      	           (8, np.float64(0.999139124004874)),
INFO :      	           (9, np.float64(0.9991808937641542)),
INFO :      	           (10, np.float64(0.9991944644076375)),
INFO :      	           (11, np.float64(0.9992079774378809)),
INFO :      	           (12, np.float64(0.9992409683885732)),
INFO :      	           (13, np.float64(0.9992432400589202)),
INFO :      	           (14, np.float64(0.9992537865985124)),
INFO :      	           (15, np.float64(0.9992613810181012))],
INFO :      	 'alpha_threshold': [(1, np.float64(0.9412273908856286)),
INFO :      	                     (2, np.float64(0.940636064290296)),
INFO :      	                     (3, np.float64(0.9410813929692561)),
INFO :      	                     (4, np.float64(0.9415997361239563)),
INFO :      	                     (5, np.float64(0.9415040404344035)),
INFO :      	                     (6, np.float64(0.9415061165196178)),
INFO :      	                     (7, np.float64(0.9416859923647312)),
INFO :      	                     (8, np.float64(0.9416224774997188)),
INFO :      	                     (9, np.float64(0.9416802980241832)),
INFO :      	                     (10, np.float64(0.941718149939571)),
INFO :      	                     (11, np.float64(0.9415111193121222)),
INFO :      	                     (12, np.float64(0.9417120151651595)),
INFO :      	                     (13, np.float64(0.9412715128477107)),
INFO :      	                     (14, np.float64(0.9416592377055018)),
INFO :      	                     (15, np.float64(0.9411285334989634))],
INFO :      	 'benign_alpha_mean_round': [(1, 0.9889075383160252),
INFO :      	                             (2, 0.9977995667192737),
INFO :      	                             (3, 0.9985219253369507),
INFO :      	                             (4, 0.998803980633214),
INFO :      	                             (5, 0.9989371385250799),
INFO :      	                             (6, 0.9990412902423346),
INFO :      	                             (7, 0.9990870502895586),
INFO :      	                             (8, 0.999139124004874),
INFO :      	                             (9, 0.9991808937641542),
INFO :      	                             (10, 0.9991944644076375),
INFO :      	                             (11, 0.9992079774378809),
INFO :      	                             (12, 0.9992409683885732),
INFO :      	                             (13, 0.9992432400589202),
INFO :      	                             (14, 0.9992537865985124),
INFO :      	                             (15, 0.9992613810181012)],
INFO :      	 'ensemble_size': [(1, 1),
INFO :      	                   (2, 2),
INFO :      	                   (3, 3),
INFO :      	                   (4, 4),
INFO :      	                   (5, 5),
INFO :      	                   (6, 6),
INFO :      	                   (7, 7),
INFO :      	                   (8, 8),
INFO :      	                   (9, 9),
INFO :      	                   (10, 10),
INFO :      	                   (11, 11),
INFO :      	                   (12, 12),
INFO :      	                   (13, 13),
INFO :      	                   (14, 14),
INFO :      	                   (15, 15)],
INFO :      	 'f1_score': [(1, 0.9802836371395622),
INFO :      	              (2, 0.9862647778118401),
INFO :      	              (3, 0.9898184274839767),
INFO :      	              (4, 0.9925433882470985),
INFO :      	              (5, 0.993104088632396),
INFO :      	              (6, 0.9936564642548774),
INFO :      	              (7, 0.9940816356531734),
INFO :      	              (8, 0.9942512104808262),
INFO :      	              (9, 0.994380772015163),
INFO :      	              (10, 0.994380772015163),
INFO :      	              (11, 0.9942503413549052),
INFO :      	              (12, 0.9941855862981583),
INFO :      	              (13, 0.9942495826750666),
INFO :      	              (14, 0.9943135419671585),
INFO :      	              (15, 0.994620061936915)],
INFO :      	 'grad_divergence': [(1, np.float64(4.042553091421723)),
INFO :      	                     (2, np.float64(3.923417057842016)),
INFO :      	                     (3, np.float64(3.4078211525455115)),
INFO :      	                     (4, np.float64(3.1909255696460606)),
INFO :      	                     (5, np.float64(3.0605640184134244)),
INFO :      	                     (6, np.float64(2.9826456738635896)),
INFO :      	                     (7, np.float64(2.900362833403051)),
INFO :      	                     (8, np.float64(2.9009601466357706)),
INFO :      	                     (9, np.float64(2.8969446613453327)),
INFO :      	                     (10, np.float64(2.905570901464671)),
INFO :      	                     (11, np.float64(2.9502943539991975)),
INFO :      	                     (12, np.float64(2.9305929243564606)),
INFO :      	                     (13, np.float64(2.9659522676840426)),
INFO :      	                     (14, np.float64(2.9151574354618788)),
INFO :      	                     (15, np.float64(3.046694604493678))],
INFO :      	 'loss': [(1, 0.7731652159922141),
INFO :      	          (2, 0.7675364439797857),
INFO :      	          (3, 0.7652658514687707),
INFO :      	          (4, 0.7630010057136051),
INFO :      	          (5, 0.7611391792646155),
INFO :      	          (6, 0.7603011835436675),
INFO :      	          (7, 0.7593256219851395),
INFO :      	          (8, 0.7588288583868338),
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
(ClientAppActor pid=621918)
INFO :      	          (9, 0.7582110006648051),
(ClientAppActor pid=621917)
(ClientAppActor pid=621917)
INFO :      	          (10, 0.7580552329466236),
INFO :      	          (11, 0.7578049944039157),
INFO :      	          (12, 0.75715948613808),
INFO :      	          (13, 0.7571642547855555),
INFO :      	          (14, 0.7569591629434436),
INFO :      	          (15, 0.7566452967474752)],
INFO :      	 'mal_alpha_count_round': [(1, 0),
INFO :      	                           (2, 0),
INFO :      	                           (3, 0),
INFO :      	                           (4, 0),
INFO :      	                           (5, 0),
INFO :      	                           (6, 0),
INFO :      	                           (7, 0),
INFO :      	                           (8, 0),
INFO :      	                           (9, 0),
INFO :      	                           (10, 0),
INFO :      	                           (11, 0),
INFO :      	                           (12, 0),
INFO :      	                           (13, 0),
INFO :      	                           (14, 0),
INFO :      	                           (15, 0)],
INFO :      	 'mal_alpha_mean_round': [(1, nan),
INFO :      	                          (2, nan),
INFO :      	                          (3, nan),
INFO :      	                          (4, nan),
INFO :      	                          (5, nan),
INFO :      	                          (6, nan),
INFO :      	                          (7, nan),
INFO :      	                          (8, nan),
INFO :      	                          (9, nan),

[Round 15] learners=15 acc=0.9954 f1=0.9946

INFO :      	                          (10, nan),
INFO :      	                          (11, nan),
INFO :      	                          (12, nan),
INFO :      	                          (13, nan),
INFO :      	                          (14, nan),
INFO :      	                          (15, nan)],
INFO :      	 'num_examples': [(1, 10737),
INFO :      	                  (2, 10737),
INFO :      	                  (3, 10737),
INFO :      	                  (4, 10737),
INFO :      	                  (5, 10737),
INFO :      	                  (6, 10737),
INFO :      	                  (7, 10737),
INFO :      	                  (8, 10737),
INFO :      	                  (9, 10737),
INFO :      	                  (10, 10737),
INFO :      	                  (11, 10737),
INFO :      	                  (12, 10737),
INFO :      	                  (13, 10737),
INFO :      	                  (14, 10737),
INFO :      	                  (15, 10737)],
INFO :      	 'num_filtered': [(1, 7),
INFO :      	                  (2, 7),
INFO :      	                  (3, 7),
INFO :      	                  (4, 7),
INFO :      	                  (5, 7),
INFO :      	                  (6, 7),
INFO :      	                  (7, 7),
INFO :      	                  (8, 7),
INFO :      	                  (9, 7),
INFO :      	                  (10, 7),
INFO :      	                  (11, 7),
INFO :      	                  (12, 7),
INFO :      	                  (13, 7),
INFO :      	                  (14, 7),
INFO :      	                  (15, 7)],
INFO :      	 'num_filtered_malicious': [(1, 7),
INFO :      	                            (2, 7),
INFO :      	                            (3, 7),
INFO :      	                            (4, 7),
INFO :      	                            (5, 7),
INFO :      	                            (6, 7),
INFO :      	                            (7, 7),
INFO :      	                            (8, 7),
INFO :      	                            (9, 7),
INFO :      	                            (10, 7),
INFO :      	                            (11, 7),
INFO :      	                            (12, 7),
INFO :      	                            (13, 7),
INFO :      	                            (14, 7),
INFO :      	                            (15, 7)],
INFO :      	 'precision': [(1, 0.9747751020139029),
INFO :      	               (2, 0.9828166343794112),
INFO :      	               (3, 0.9886512593430743),
INFO :      	               (4, 0.9917002443135513),
INFO :      	               (5, 0.9921677538437803),
INFO :      	               (6, 0.9928899518854684),
INFO :      	               (7, 0.9934444100567423),
INFO :      	               (8, 0.9936574205949915),
INFO :      	               (9, 0.9937430441915003),
INFO :      	               (10, 0.9937430441915003),
INFO :      	               (11, 0.9937003282563348),
INFO :      	               (12, 0.9936577104860631),
INFO :      	               (13, 0.9937436314704209),
INFO :      	               (14, 0.9938294800388505),
INFO :      	               (15, 0.9939186359426568)],
INFO :      	 'recall': [(1, 0.9860692327053071),
INFO :      	            (2, 0.989878035688603),
INFO :      	            (3, 0.9910367270380035),
INFO :      	            (4, 0.9934119992740372),
INFO :      	            (5, 0.9940582216994378),
INFO :      	            (6, 0.9944332216994377),
INFO :      	            (7, 0.9947248883661044),
INFO :      	            (8, 0.9948498883661044),
INFO :      	            (9, 0.9950245303500374),
INFO :      	            (10, 0.9950245303500374),
INFO :      	            (11, 0.9948042340408045),
INFO :      	            (12, 0.9947169130488381),
INFO :      	            (13, 0.9947585797155047),
INFO :      	            (14, 0.9948002463821715),
INFO :      	            (15, 0.9953254564662051)],
INFO :      	 'residual_loss': [(1, np.float64(0.011217386533202702)),
INFO :      	                   (2, np.float64(0.002205320707461007)),
INFO :      	                   (3, np.float64(0.00148026955827975)),
INFO :      	                   (4, np.float64(0.0011974543796744305)),
INFO :      	                   (5, np.float64(0.001063996289373054)),
INFO :      	                   (6, np.float64(0.0009596308224228692)),
INFO :      	                   (7, np.float64(0.0009137855489544087)),
INFO :      	                   (8, np.float64(0.0008616185953217479)),
INFO :      	                   (9, np.float64(0.000819778886837715)),
INFO :      	                   (10, np.float64(0.0008061861464414375)),
INFO :      	                   (11, np.float64(0.0007926513528900614)),
INFO :      	                   (12, np.float64(0.0007596086548801395)),
INFO :      	                   (13, np.float64(0.0007573341787249212)),
INFO :      	                   (14, np.float64(0.0007467714211283498)),
INFO :      	                   (15, np.float64(0.0007391652794180594))]}
INFO :

[Sweep] mal_frac=0.70 acc=0.9954 filtered_mal=105/105

,mode,mal_frac,flip_prob,final_accuracy,final_f1,final_precision,final_recall,final_loss,ensemble_size,mal_alpha_mean_last_round,mal_alpha_mean_over_rounds,benign_alpha_mean_last_round,benign_alpha_mean_over_rounds,total_filtered,total_filtered_malicious,avg_filtered_per_round,avg_filtered_malicious_per_round
0,random,0.1,1.0,0.994850,0.992238,0.991951,0.992529,0.755868,15,NaN,NaN,0.999053,0.998104,15,15,1.0,1.0
1,random,0.3,1.0,0.995111,0.993708,0.992838,0.994584,0.755870,15,NaN,NaN,0.999099,0.998181,45,45,3.0,3.0
2,random,0.5,1.0,0.995306,0.993851,0.993523,0.994180,0.756879,15,NaN,NaN,0.999172,0.998240,75,75,5.0,5.0
3,random,0.7,1.0,0.995371,0.994620,0.993919,0.995325,0.756645,15,NaN,NaN,0.999261,0.998321,105,105,7.0,7.0

(raylet) [2026-09-17 15:17:24,186 E 620806 620806] (raylet) node_manager.cc:3064: 1 Workers (tasks / actors) killed due to memory pressure (OOM), 0 Workers crashed due to other reasons at node (ID: a23039b7a791152dda7ae957487f02b00d23f741f7b43a1bdca2151a, IP: 172.24.90.50) over the last time period. To see more information about the Workers killed on this node, use `ray logs raylet.out -ip 172.24.90.50`
(raylet)
(raylet) Refer to the documentation on how to address the out of memory issue: https://docs.ray.io/en/latest/ray-core/scheduling/ray-oom-prevention.html. Consider provisioning more memory on this node or reducing task parallelism by requesting more CPUs per task. To adjust the kill threshold, set the environment variable `RAY_memory_usage_threshold` when starting Ray. To disable worker killing, set the environment variable `RAY_memory_monitor_refresh_ms` to zero.
(raylet)
(raylet) [2026-09-17 15:18:24,188 E 620806 620806] (raylet) node_manager.cc:3064: 1 Workers (tasks / actors) killed due to memory pressure (OOM), 0 Workers crashed due to other reasons at node (ID: a23039b7a791152dda7ae957487f02b00d23f741f7b43a1bdca2151a, IP: 172.24.90.50) over the last time period. To see more information about the Workers killed on this node, use `ray logs raylet.out -ip 172.24.90.50`
(raylet) Refer to the documentation on how to address the out of memory issue: https://docs.ray.io/en/latest/ray-core/scheduling/ray-oom-prevention.html. Consider provisioning more memory on this node or reducing task parallelism by requesting more CPUs per task. To adjust the kill threshold, set the environment variable `RAY_memory_usage_threshold` when starting Ray. To disable worker killing, set the environment variable `RAY_memory_monitor_refresh_ms` to zero.

## 11. Poisoning sweep

In [11]:
mal_fracs = [0.1, 0.3, 0.5, 0.7]
flip_probs = [1.0]

results = []
curves = {}
for mf in mal_fracs:
    for fp in flip_probs:
        set_poisoning(mal_frac=mf, flip_prob=fp, mode="random", seed=BASE_SEED)
        res = run_one_experiment(num_rounds=NUM_ROUNDS, seed=BASE_SEED)
        if res is None:
            continue
        row = {
            "mode": "random",
            "mal_frac": mf,
            "flip_prob": fp,
            "final_accuracy": res["final_accuracy"],
            "final_f1": res["final_f1"],
            "final_precision": res["final_precision"],
            "final_recall": res["final_recall"],
            "final_loss": res["final_loss"],
            "ensemble_size": res["ensemble_size"],
            "mal_alpha_mean_last_round": res["mal_alpha_mean_last_round"],
            "mal_alpha_mean_over_rounds": res["mal_alpha_mean_over_rounds"],
            "benign_alpha_mean_last_round": res["benign_alpha_mean_last_round"],
            "benign_alpha_mean_over_rounds": res["benign_alpha_mean_over_rounds"],
            "total_filtered": res["total_filtered"],
            "total_filtered_malicious": res["total_filtered_malicious"],
            "avg_filtered_per_round": res["avg_filtered_per_round"],
            "avg_filtered_malicious_per_round": res["avg_filtered_malicious_per_round"],
        }
        results.append(row)
        curves[(mf, fp)] = (res["rounds"], res["acc_curve"])
        print(f"[Sweep] mal_frac={mf:.2f} acc={row['final_accuracy']:.4f} "
              f"filtered_mal={row['total_filtered_malicious']}/{row['total_filtered']}")

df_results = pd.DataFrame(results).sort_values(["mal_frac", "flip_prob"]).reset_index(drop=True)
df_results.to_csv("boostfl_botiot_labelflip.csv", index=False)
df_results

[Poison] mal_frac=0.1, flip_prob=1.0, malicious_clients=[4]

WARNING :   DEPRECATED FEATURE: flwr.simulation.start_simulation() is deprecated.
	Instead, use the `flwr run` CLI command to start a local simulation in your Flower app, as shown for example below:

		$ flwr new  # Create a new Flower app from a template

		$ flwr run  # Run the Flower app in Simulation Mode

	Using `start_simulation()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.

INFO :      Starting Flower simulation, config: num_rounds=15, no round_timeout
2026-09-14 21:19:54,987	INFO worker.py:1771 -- Started a local Ray instance.
INFO :      Flower VCE: Ray initialized with resources: {'node:172.24.90.50': 1.0, 'accelerator_type:G': 1.0, 'node:__internal_head__': 1.0, 'CPU': 20.0, 'memory': 13461268071.0, 'object_store_memory': 6730634035.0, 'GPU': 1.0}
INFO :      Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
INFO :      Flower VCE: Resources for each Virtual Client: {'num_cpus': 10, 'num_gpus': 0.5}
INFO :      Flower VCE: Creating VirtualClientEngineActorPool with 2 actors
INFO :      [INIT]
INFO :      Using initial global parameters provided by strategy
INFO :      Starting evaluation of initial global parameters
INFO :      Evaluation returned no results (`None`)
INFO :
INFO :      [ROUND 1]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=333870) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context`
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)             This is a deprecated feature. It will be removed
(ClientAppActor pid=333870)             entirely in future versions of Flower.
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 6x across cluster] (Ray deduplicates logs by default. Set RAY_DEDUP_LOGS=0 to disable log deduplication, or see https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#log-deduplication for more options.)
(ClientAppActor pid=333870)             This is a deprecated feature. It will be removed [repeated 6x across cluster]
(ClientAppActor pid=333870)             entirely in future versions of Flower. [repeated 6x across cluster]
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 1] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9510
[Alpha Filtering] Filtered client alpha=0.8948 (malicious=True)
[Alpha Filtering] Filtered 1 clients (1 malicious), kept 9

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 2]
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 1] learners=1 acc=0.9896 f1=0.9829

(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=333870)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=333870)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
INFO :      aggregate_fit: received 10 results and 0 failures
INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)

[Round 2] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9595
[Alpha Filtering] Filtered client alpha=0.8823 (malicious=True)
[Alpha Filtering] Filtered 1 clients (1 malicious), kept 9
[Round 2] learners=2 acc=0.9926 f1=0.9891

(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 3]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=333870)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=333870)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 3] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9598
[Alpha Filtering] Filtered client alpha=0.8821 (malicious=True)
[Alpha Filtering] Filtered 1 clients (1 malicious), kept 9

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 10x across cluster]
(ClientAppActor pid=333870)             This is a deprecated feature. It will be removed [repeated 10x across cluster]
(ClientAppActor pid=333870)             entirely in future versions of Flower. [repeated 10x across cluster]
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 4]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 3] learners=3 acc=0.9935 f1=0.9905

(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 16x across cluster]
(ClientAppActor pid=333869)             This is a deprecated feature. It will be removed [repeated 16x across cluster]
(ClientAppActor pid=333869)             entirely in future versions of Flower. [repeated 16x across cluster]
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 4] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9600
[Alpha Filtering] Filtered client alpha=0.8832 (malicious=True)
[Alpha Filtering] Filtered 1 clients (1 malicious), kept 9

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 5]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 4] learners=4 acc=0.9943 f1=0.9913

(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=333869)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=333869)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 5] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9600
[Alpha Filtering] Filtered client alpha=0.8826 (malicious=True)
[Alpha Filtering] Filtered 1 clients (1 malicious), kept 9

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 6]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 5] learners=5 acc=0.9943 f1=0.9907

(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=333870)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=333870)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 6] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9599
[Alpha Filtering] Filtered client alpha=0.8810 (malicious=True)
[Alpha Filtering] Filtered 1 clients (1 malicious), kept 9

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 7]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 6] learners=6 acc=0.9941 f1=0.9899

(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=333870)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=333870)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 7] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9601
[Alpha Filtering] Filtered client alpha=0.8827 (malicious=True)
[Alpha Filtering] Filtered 1 clients (1 malicious), kept 9

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 10x across cluster]
(ClientAppActor pid=333870)             This is a deprecated feature. It will be removed [repeated 10x across cluster]
(ClientAppActor pid=333870)             entirely in future versions of Flower. [repeated 10x across cluster]
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 8]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 7] learners=7 acc=0.9941 f1=0.9899

(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 16x across cluster]
(ClientAppActor pid=333870)             This is a deprecated feature. It will be removed [repeated 16x across cluster]
(ClientAppActor pid=333870)             entirely in future versions of Flower. [repeated 16x across cluster]
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 8] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9601
[Alpha Filtering] Filtered client alpha=0.8832 (malicious=True)
[Alpha Filtering] Filtered 1 clients (1 malicious), kept 9

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 9]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 8] learners=8 acc=0.9941 f1=0.9899

(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=333870)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=333870)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 9] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9600
[Alpha Filtering] Filtered client alpha=0.8821 (malicious=True)
[Alpha Filtering] Filtered 1 clients (1 malicious), kept 9

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 10]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 9] learners=9 acc=0.9942 f1=0.9899

(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=333870)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=333870)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 10] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9601
[Alpha Filtering] Filtered client alpha=0.8823 (malicious=True)
[Alpha Filtering] Filtered 1 clients (1 malicious), kept 9

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 11]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 10] learners=10 acc=0.9944 f1=0.9901

(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=333870)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=333870)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 11] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9601
[Alpha Filtering] Filtered client alpha=0.8824 (malicious=True)
[Alpha Filtering] Filtered 1 clients (1 malicious), kept 9

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 11x across cluster]
(ClientAppActor pid=333870)             This is a deprecated feature. It will be removed [repeated 11x across cluster]
(ClientAppActor pid=333870)             entirely in future versions of Flower. [repeated 11x across cluster]
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 12]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 11] learners=11 acc=0.9945 f1=0.9902

(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 15x across cluster]
(ClientAppActor pid=333870)             This is a deprecated feature. It will be removed [repeated 15x across cluster]
(ClientAppActor pid=333870)             entirely in future versions of Flower. [repeated 15x across cluster]
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 12] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9602
[Alpha Filtering] Filtered client alpha=0.8829 (malicious=True)
[Alpha Filtering] Filtered 1 clients (1 malicious), kept 9

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 13]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 12] learners=12 acc=0.9945 f1=0.9902

(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=333869)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=333869)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 13] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9601
[Alpha Filtering] Filtered client alpha=0.8825 (malicious=True)
[Alpha Filtering] Filtered 1 clients (1 malicious), kept 9

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 14]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 13] learners=13 acc=0.9945 f1=0.9903

(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=333869)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=333869)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 14] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9602
[Alpha Filtering] Filtered client alpha=0.8829 (malicious=True)
[Alpha Filtering] Filtered 1 clients (1 malicious), kept 9

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 15]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 14] learners=14 acc=0.9946 f1=0.9903

(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=333869)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=333869)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 15] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9602
[Alpha Filtering] Filtered client alpha=0.8830 (malicious=True)
[Alpha Filtering] Filtered 1 clients (1 malicious), kept 9

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [SUMMARY]
INFO :      Run finished 15 round(s) in 108.99s
INFO :      	History (loss, distributed):
INFO :      		round 1: 0.0
INFO :      		round 2: 0.0
INFO :      		round 3: 0.0
INFO :      		round 4: 0.0
INFO :      		round 5: 0.0
INFO :      		round 6: 0.0
INFO :      		round 7: 0.0
INFO :      		round 8: 0.0
INFO :      		round 9: 0.0
INFO :      		round 10: 0.0
INFO :      		round 11: 0.0
INFO :      		round 12: 0.0
INFO :      		round 13: 0.0
INFO :      		round 14: 0.0
INFO :      		round 15: 0.0
INFO :      	History (metrics, distributed, fit):
INFO :      	{'accuracy': [(1, 0.9895690722993676),
INFO :      	              (2, 0.9925679640132994),
INFO :      	              (3, 0.9935458634852338),
INFO :      	              (4, 0.9943281830627811),
INFO :      	              (5, 0.9942629897646522),
INFO :      	              (6, 0.9941326031683942),
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870)
(ClientAppActor pid=333870) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 12x across cluster]
(ClientAppActor pid=333870)             This is a deprecated feature. It will be removed [repeated 12x across cluster]
(ClientAppActor pid=333870)             entirely in future versions of Flower. [repeated 12x across cluster]
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
(ClientAppActor pid=333869)
INFO :      	              (7, 0.9941326031683942),
INFO :      	              (8, 0.9941326031683942),
INFO :      	              (9, 0.9941977964665233),
INFO :      	              (10, 0.9943933763609101),
INFO :      	              (11, 0.994458569659039),
INFO :      	              (12, 0.994458569659039),
INFO :      	              (13, 0.994523762957168),
INFO :      	              (14, 0.994588956255297),
INFO :      	              (15, 0.994588956255297)],
INFO :      	 'alpha': [(1, np.float64(0.957248933619917)),
INFO :      	           (2, np.float64(0.9680384248537405)),
INFO :      	           (3, np.float64(0.9684432391071112)),
INFO :      	           (4, np.float64(0.9685653023732859)),
INFO :      	           (5, np.float64(0.9686081724669768)),
INFO :      	           (6, np.float64(0.9686520222278793)),
INFO :      	           (7, np.float64(0.9686747822850919)),
INFO :      	           (8, np.float64(0.9686858131924294)),
INFO :      	           (9, np.float64(0.9687005742590742)),
INFO :      	           (10, np.float64(0.9687114056020368)),
INFO :      	           (11, np.float64(0.9687162919059169)),
INFO :      	           (12, np.float64(0.9687356562045648)),
INFO :      	           (13, np.float64(0.9687345645600028)),
INFO :      	           (14, np.float64(0.9687345093804969)),
INFO :      	           (15, np.float64(0.9687421835260319))],
INFO :      	 'alpha_threshold': [(1, np.float64(0.9510018238585453)),
INFO :      	                     (2, np.float64(0.9594672496976525)),
INFO :      	                     (3, np.float64(0.9598069432462)),
INFO :      	                     (4, np.float64(0.9600334922573432)),
INFO :      	                     (5, np.float64(0.9600078234480062)),
INFO :      	                     (6, np.float64(0.9598874127279448)),
INFO :      	                     (7, np.float64(0.9600785828814441)),
INFO :      	                     (8, np.float64(0.9601384802012758)),
INFO :      	                     (9, np.float64(0.9600452797736934)),
INFO :      	                     (10, np.float64(0.9600730502816406)),
INFO :      	                     (11, np.float64(0.960081158191229)),
INFO :      	                     (12, np.float64(0.9601569494169482)),
INFO :      	                     (13, np.float64(0.9601120149746496)),
INFO :      	                     (14, np.float64(0.9601552848381735)),
INFO :      	                     (15, np.float64(0.9601634322972099))],
INFO :      	 'benign_alpha_mean_round': [(1, 0.957248933619917),
INFO :      	                             (2, 0.9680384248537405),
INFO :      	                             (3, 0.9684432391071112),
INFO :      	                             (4, 0.9685653023732859),
INFO :      	                             (5, 0.9686081724669768),
INFO :      	                             (6, 0.9686520222278793),
INFO :      	                             (7, 0.9686747822850919),
INFO :      	                             (8, 0.9686858131924294),
INFO :      	                             (9, 0.9687005742590742),
INFO :      	                             (10, 0.9687114056020368),
INFO :      	                             (11, 0.9687162919059169),
INFO :      	                             (12, 0.9687356562045648),
INFO :      	                             (13, 0.9687345645600028),
INFO :      	                             (14, 0.9687345093804969),
INFO :      	                             (15, 0.9687421835260319)],
INFO :      	 'ensemble_size': [(1, 1),
INFO :      	                   (2, 2),
INFO :      	                   (3, 3),
INFO :      	                   (4, 4),
INFO :      	                   (5, 5),
INFO :      	                   (6, 6),
INFO :      	                   (7, 7),
INFO :      	                   (8, 8),
INFO :      	                   (9, 9),
INFO :      	                   (10, 10),
INFO :      	                   (11, 11),
INFO :      	                   (12, 12),
INFO :      	                   (13, 13),
INFO :      	                   (14, 14),
INFO :      	                   (15, 15)],
INFO :      	 'f1_score': [(1, 0.9829489512297432),
INFO :      	              (2, 0.9891082373995791),
INFO :      	              (3, 0.9905029619381409),
INFO :      	              (4, 0.991276847608446),
INFO :      	              (5, 0.9907273233118141),
INFO :      	              (6, 0.9898758005255592),
INFO :      	              (7, 0.9898758005255592),
INFO :      	              (8, 0.9898747895032058),
INFO :      	              (9, 0.9899376123235777),
INFO :      	              (10, 0.9901284124114338),
INFO :      	              (11, 0.990192370474729),
INFO :      	              (12, 0.990192370474729),
INFO :      	              (13, 0.9902572886602601),
INFO :      	              (14, 0.9903212584599264),
INFO :      	              (15, 0.9903212584599264)],
INFO :      	 'grad_divergence': [(1, np.float64(8.769017820805312)),
INFO :      	                     (2, np.float64(4.134133177995682)),
INFO :      	                     (3, np.float64(2.5466024415567516)),
INFO :      	                     (4, np.float64(2.059367742948234)),
INFO :      	                     (5, np.float64(1.848152333498001)),
INFO :      	                     (6, np.float64(1.6893913893960417)),
INFO :      	                     (7, np.float64(1.6350189102813601)),
INFO :      	                     (8, np.float64(1.611339262779802)),
INFO :      	                     (9, np.float64(1.5591412162408234)),
INFO :      	                     (10, np.float64(1.5488672611303627)),
INFO :      	                     (11, np.float64(1.5389243137091397)),
INFO :      	                     (12, np.float64(1.4996728247962892)),
INFO :      	                     (13, np.float64(1.496996720461175)),
INFO :      	                     (14, np.float64(1.46522413790226)),
INFO :      	                     (15, np.float64(1.4375274627003818))],
INFO :      	 'loss': [(1, 0.06111533851897369),
INFO :      	          (2, 0.04975612759925301),
INFO :      	          (3, 0.044427078587878394),
INFO :      	          (4, 0.0415186952416805),
INFO :      	          (5, 0.039821654649862905),
INFO :      	          (6, 0.03865215981836829),
INFO :      	          (7, 0.03763761548033376),
INFO :      	          (8, 0.0370392996921773),
INFO :      	          (9, 0.03651595558548341),
INFO :      	          (10, 0.03622919078062645),
INFO :      	          (11, 0.03586119807738354),
INFO :      	          (12, 0.0355746685483246),
INFO :      	          (13, 0.0351785943698981),
INFO :      	          (14, 0.03497981271539613),
INFO :      	          (15, 0.0347901096430172)],
INFO :      	 'mal_alpha_count_round': [(1, 0),
INFO :      	                           (2, 0),
INFO :      	                           (3, 0),
INFO :      	                           (4, 0),
INFO :      	                           (5, 0),
INFO :      	                           (6, 0),
INFO :      	                           (7, 0),
INFO :      	                           (8, 0),
INFO :      	                           (9, 0),
INFO :      	                           (10, 0),
INFO :      	                           (11, 0),
INFO :      	                           (12, 0),
INFO :      	                           (13, 0),
INFO :      	                           (14, 0),
INFO :      	                           (15, 0)],
INFO :      	 'mal_alpha_mean_round': [(1, nan),
INFO :      	                          (2, nan),
INFO :      	                          (3, nan),
INFO :      	                          (4, nan),
INFO :      	                          (5, nan),
INFO :      	                          (6, nan),
INFO :      	                          (7, nan),
INFO :      	                          (8, nan),
INFO :      	                          (9, nan),
INFO :      	                          (10, nan),
INFO :      	                          (11, nan),
INFO :      	                          (12, nan),
INFO :      	                          (13, nan),
INFO :      	                          (14, nan),
INFO :      	                          (15, nan)],
INFO :      	 'num_examples': [(1, 32212),
INFO :      	                  (2, 32212),
INFO :      	                  (3, 32212),
INFO :      	                  (4, 32212),
INFO :      	                  (5, 32212),
INFO :      	                  (6, 32212),
INFO :      	                  (7, 32212),
INFO :      	                  (8, 32212),
INFO :      	                  (9, 32212),
INFO :      	                  (10, 32212),
INFO :      	                  (11, 32212),
INFO :      	                  (12, 32212),
INFO :      	                  (13, 32212),
INFO :      	                  (14, 32212),
INFO :      	                  (15, 32212)],
INFO :      	 'num_filtered': [(1, 1),
INFO :      	                  (2, 1),
INFO :      	                  (3, 1),
INFO :      	                  (4, 1),
INFO :      	                  (5, 1),
INFO :      	                  (6, 1),
INFO :      	                  (7, 1),
INFO :      	                  (8, 1),
INFO :      	                  (9, 1),
INFO :      	                  (10, 1),
INFO :      	                  (11, 1),
INFO :      	                  (12, 1),
INFO :      	                  (13, 1),
INFO :      	                  (14, 1),
INFO :      	                  (15, 1)],
INFO :      	 'num_filtered_malicious': [(1, 1),
INFO :      	                            (2, 1),
INFO :      	                            (3, 1),
INFO :      	                            (4, 1),
INFO :      	                            (5, 1),
INFO :      	                            (6, 1),
INFO :      	                            (7, 1),
INFO :      	                            (8, 1),
INFO :      	                            (9, 1),
INFO :      	                            (10, 1),
INFO :      	                            (11, 1),

[Round 15] learners=15 acc=0.9946 f1=0.9903

INFO :      	                            (12, 1),
INFO :      	                            (13, 1),
INFO :      	                            (14, 1),
INFO :      	                            (15, 1)],
INFO :      	 'precision': [(1, 0.9793513045781177),
INFO :      	               (2, 0.9863939029225477),
INFO :      	               (3, 0.987934562504884),
INFO :      	               (4, 0.9886634603613401),
INFO :      	               (5, 0.9885097522679843),
INFO :      	               (6, 0.987850186153941),
INFO :      	               (7, 0.987850186153941),
INFO :      	               (8, 0.9878926524522069),
INFO :      	               (9, 0.9880207762371866),
INFO :      	               (10, 0.9883212704915882),
INFO :      	               (11, 0.9884072779539904),
INFO :      	               (12, 0.9884072779539904),
INFO :      	               (13, 0.9884500356752947),
INFO :      	               (14, 0.9885360665281143),
INFO :      	               (15, 0.9885360665281143)],
INFO :      	 'recall': [(1, 0.9866530719867409),
INFO :      	            (2, 0.9918818880853075),
INFO :      	            (3, 0.9931273944785739),
INFO :      	            (4, 0.9939469747556724),
INFO :      	            (5, 0.9929838755795717),
INFO :      	            (6, 0.9919334554115045),
INFO :      	            (7, 0.9919334554115045),
INFO :      	            (8, 0.9918878010862047),
INFO :      	            (9, 0.9918838134275716),
INFO :      	            (10, 0.9919631591022717),
INFO :      	            (11, 0.9920048257689384),
INFO :      	            (12, 0.9920048257689384),
INFO :      	            (13, 0.992092146760905),
INFO :      	            (14, 0.9921338134275716),
INFO :      	            (15, 0.9921338134275716)],
INFO :      	 'residual_loss': [(1, np.float64(0.04466050415344181)),
INFO :      	                   (2, np.float64(0.03301688310586744)),
INFO :      	                   (3, np.float64(0.03258506105769248)),
INFO :      	                   (4, np.float64(0.03245493511240634)),
INFO :      	                   (5, np.float64(0.032409241085960744)),
INFO :      	                   (6, np.float64(0.03236250303064783)),
INFO :      	                   (7, np.float64(0.03233824623157345)),
INFO :      	                   (8, np.float64(0.03232649290815942)),
INFO :      	                   (9, np.float64(0.032310761618501854)),
INFO :      	                   (10, np.float64(0.0322992208731612)),
INFO :      	                   (11, np.float64(0.03229401150703548)),
INFO :      	                   (12, np.float64(0.032273378501838396)),
INFO :      	                   (13, np.float64(0.03227453896746276)),
INFO :      	                   (14, np.float64(0.032274601372727564)),
INFO :      	                   (15, np.float64(0.032266421540684646))]}
INFO :
WARNING :   DEPRECATED FEATURE: flwr.simulation.start_simulation() is deprecated.
	Instead, use the `flwr run` CLI command to start a local simulation in your Flower app, as shown for example below:

		$ flwr new  # Create a new Flower app from a template

		$ flwr run  # Run the Flower app in Simulation Mode

	Using `start_simulation()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.

INFO :      Starting Flower simulation, config: num_rounds=15, no round_timeout
(ClientAppActor pid=333869) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 5x across cluster]
(ClientAppActor pid=333869)             This is a deprecated feature. It will be removed [repeated 5x across cluster]
(ClientAppActor pid=333869)             entirely in future versions of Flower. [repeated 5x across cluster]

[Sweep] mal_frac=0.10 acc=0.9946 filtered_mal=15/15
[Poison] mal_frac=0.3, flip_prob=1.0, malicious_clients=[0, 4, 7]

2026-09-14 21:21:47,683	INFO worker.py:1771 -- Started a local Ray instance.
INFO :      Flower VCE: Ray initialized with resources: {'node:172.24.90.50': 1.0, 'accelerator_type:G': 1.0, 'node:__internal_head__': 1.0, 'CPU': 20.0, 'object_store_memory': 6643928678.0, 'memory': 13287857358.0, 'GPU': 1.0}
INFO :      Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
INFO :      Flower VCE: Resources for each Virtual Client: {'num_cpus': 10, 'num_gpus': 0.5}
INFO :      Flower VCE: Creating VirtualClientEngineActorPool with 2 actors
INFO :      [INIT]
INFO :      Using initial global parameters provided by strategy
INFO :      Starting evaluation of initial global parameters
INFO :      Evaluation returned no results (`None`)
INFO :
INFO :      [ROUND 1]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=335989) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context`
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)             This is a deprecated feature. It will be removed
(ClientAppActor pid=335989)             entirely in future versions of Flower.
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 7x across cluster]
(ClientAppActor pid=335989)             This is a deprecated feature. It will be removed [repeated 7x across cluster]
(ClientAppActor pid=335989)             entirely in future versions of Flower. [repeated 7x across cluster]
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
INFO :      aggregate_fit: received 10 results and 0 failures
INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)

[Round 1] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9384
[Alpha Filtering] Filtered client alpha=0.8947 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8948 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8947 (malicious=True)
[Alpha Filtering] Filtered 3 clients (3 malicious), kept 7
[Round 1] learners=1 acc=0.9895 f1=0.9833

INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 2]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 17x across cluster]
(ClientAppActor pid=335990)             This is a deprecated feature. It will be removed [repeated 17x across cluster]
(ClientAppActor pid=335990)             entirely in future versions of Flower. [repeated 17x across cluster]
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
INFO :      aggregate_fit: received 10 results and 0 failures
INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)

[Round 2] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9425
[Alpha Filtering] Filtered client alpha=0.8832 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8825 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8836 (malicious=True)
[Alpha Filtering] Filtered 3 clients (3 malicious), kept 7
[Round 2] learners=2 acc=0.9926 f1=0.9883

(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 3]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=335989)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=335989)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 3] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9426
[Alpha Filtering] Filtered client alpha=0.8814 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8821 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8834 (malicious=True)
[Alpha Filtering] Filtered 3 clients (3 malicious), kept 7

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 8x across cluster]
(ClientAppActor pid=335990)             This is a deprecated feature. It will be removed [repeated 8x across cluster]
(ClientAppActor pid=335990)             entirely in future versions of Flower. [repeated 8x across cluster]
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 4]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 3] learners=3 acc=0.9935 f1=0.9898

(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=335990)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=335990)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 4] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9428
[Alpha Filtering] Filtered client alpha=0.8824 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8827 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8830 (malicious=True)
[Alpha Filtering] Filtered 3 clients (3 malicious), kept 7

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 5]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 4] learners=4 acc=0.9941 f1=0.9905

(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=335989)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=335989)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 5] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9428
[Alpha Filtering] Filtered client alpha=0.8835 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8813 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8834 (malicious=True)
[Alpha Filtering] Filtered 3 clients (3 malicious), kept 7

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 6]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 5] learners=5 acc=0.9941 f1=0.9901

(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=335990)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=335990)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 6] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9425
[Alpha Filtering] Filtered client alpha=0.8824 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8812 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8812 (malicious=True)
[Alpha Filtering] Filtered 3 clients (3 malicious), kept 7

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 7]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 6] learners=6 acc=0.9941 f1=0.9899

(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=335990)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=335990)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 7] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9426
[Alpha Filtering] Filtered client alpha=0.8821 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8817 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8817 (malicious=True)
[Alpha Filtering] Filtered 3 clients (3 malicious), kept 7

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 8x across cluster]
(ClientAppActor pid=335989)             This is a deprecated feature. It will be removed [repeated 8x across cluster]
(ClientAppActor pid=335989)             entirely in future versions of Flower. [repeated 8x across cluster]
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 8]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 7] learners=7 acc=0.9941 f1=0.9899

(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=335989)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=335989)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 8] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9426
[Alpha Filtering] Filtered client alpha=0.8815 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8816 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8824 (malicious=True)
[Alpha Filtering] Filtered 3 clients (3 malicious), kept 7

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 9]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 8] learners=8 acc=0.9944 f1=0.9901

(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=335989)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=335989)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 9] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9429
[Alpha Filtering] Filtered client alpha=0.8825 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8834 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8827 (malicious=True)
[Alpha Filtering] Filtered 3 clients (3 malicious), kept 7

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 10]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 9] learners=9 acc=0.9944 f1=0.9901

(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=335990)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=335990)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 10] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9430
[Alpha Filtering] Filtered client alpha=0.8834 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8823 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8832 (malicious=True)
[Alpha Filtering] Filtered 3 clients (3 malicious), kept 7

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 11]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 10] learners=10 acc=0.9944 f1=0.9901

(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=335989)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=335989)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 11] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9428
[Alpha Filtering] Filtered client alpha=0.8827 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8836 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8810 (malicious=True)
[Alpha Filtering] Filtered 3 clients (3 malicious), kept 7

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 10x across cluster]
(ClientAppActor pid=335989)             This is a deprecated feature. It will be removed [repeated 10x across cluster]
(ClientAppActor pid=335989)             entirely in future versions of Flower. [repeated 10x across cluster]
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 12]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 11] learners=11 acc=0.9946 f1=0.9903

(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 16x across cluster]
(ClientAppActor pid=335989)             This is a deprecated feature. It will be removed [repeated 16x across cluster]
(ClientAppActor pid=335989)             entirely in future versions of Flower. [repeated 16x across cluster]
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 12] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9429
[Alpha Filtering] Filtered client alpha=0.8824 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8833 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8820 (malicious=True)
[Alpha Filtering] Filtered 3 clients (3 malicious), kept 7

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 13]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 12] learners=12 acc=0.9945 f1=0.9902

(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=335989)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=335989)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 13] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9431
[Alpha Filtering] Filtered client alpha=0.8829 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8833 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8840 (malicious=True)
[Alpha Filtering] Filtered 3 clients (3 malicious), kept 7

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 14]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 13] learners=13 acc=0.9945 f1=0.9903

(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=335989)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=335989)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 14] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9428
[Alpha Filtering] Filtered client alpha=0.8823 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8822 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8830 (malicious=True)
[Alpha Filtering] Filtered 3 clients (3 malicious), kept 7

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 15]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 14] learners=14 acc=0.9945 f1=0.9903

(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=335989)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=335989)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 15] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9430
[Alpha Filtering] Filtered client alpha=0.8841 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8817 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8827 (malicious=True)
[Alpha Filtering] Filtered 3 clients (3 malicious), kept 7

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 10x across cluster]
(ClientAppActor pid=335989)             This is a deprecated feature. It will be removed [repeated 10x across cluster]
(ClientAppActor pid=335989)             entirely in future versions of Flower. [repeated 10x across cluster]
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [SUMMARY]
INFO :      Run finished 15 round(s) in 108.96s
INFO :      	History (loss, distributed):
INFO :      		round 1: 0.0
INFO :      		round 2: 0.0
INFO :      		round 3: 0.0
INFO :      		round 4: 0.0
INFO :      		round 5: 0.0
INFO :      		round 6: 0.0
INFO :      		round 7: 0.0
INFO :      		round 8: 0.0
INFO :      		round 9: 0.0
INFO :      		round 10: 0.0
INFO :      		round 11: 0.0
INFO :      		round 12: 0.0
INFO :      		round 13: 0.0
INFO :      		round 14: 0.0
INFO :      		round 15: 0.0
INFO :      	History (metrics, distributed, fit):
INFO :      	{'accuracy': [(1, 0.9895038790012387),
INFO :      	              (2, 0.9926331573114284),
INFO :      	              (3, 0.9934806701871047),
INFO :      	              (4, 0.9940674098702653),
INFO :      	              (5, 0.9941326031683942),
INFO :      	              (6, 0.9941326031683942),
INFO :      	              (7, 0.9941326031683942),
INFO :      	              (8, 0.9943933763609101),
INFO :      	              (9, 0.9943933763609101),
INFO :      	              (10, 0.9943933763609101),
INFO :      	              (11, 0.994588956255297),
INFO :      	              (12, 0.994458569659039),
INFO :      	              (13, 0.994523762957168),
INFO :      	              (14, 0.994523762957168),
INFO :      	              (15, 0.994523762957168)],
INFO :      	 'alpha': [(1, np.float64(0.9571864853011911)),
INFO :      	           (2, np.float64(0.968002926626721)),
INFO :      	           (3, np.float64(0.9684177179488715)),
INFO :      	           (4, np.float64(0.9685453249776196)),
INFO :      	           (5, np.float64(0.9686061554657831)),
INFO :      	           (6, np.float64(0.9686255350019891)),
INFO :      	           (7, np.float64(0.9686586427906843)),
INFO :      	           (8, np.float64(0.9686734190442833)),
INFO :      	           (9, np.float64(0.9686840558322698)),
INFO :      	           (10, np.float64(0.9686903967511783)),
INFO :      	           (11, np.float64(0.9687035687035312)),
INFO :      	           (12, np.float64(0.968711016187323)),
INFO :      	           (13, np.float64(0.9687208566240066)),
INFO :      	           (14, np.float64(0.9687211201248823)),
INFO :      	           (15, np.float64(0.9687377220019966))],
INFO :      	 'alpha_threshold': [(1, np.float64(0.938447882672844)),
INFO :      	                     (2, np.float64(0.9425425376938907)),
INFO :      	                     (3, np.float64(0.9425772609514336)),
INFO :      	                     (4, np.float64(0.9427957540942277)),
INFO :      	                     (5, np.float64(0.9428420939153064)),
INFO :      	                     (6, np.float64(0.9425272817931474)),
INFO :      	                     (7, np.float64(0.9426126345641066)),
INFO :      	                     (8, np.float64(0.9426253066765208)),
INFO :      	                     (9, np.float64(0.9429391878006486)),
INFO :      	                     (10, np.float64(0.942977206573142)),
INFO :      	                     (11, np.float64(0.9428263998933651)),
INFO :      	                     (12, np.float64(0.942872557403722)),
INFO :      	                     (13, np.float64(0.9431296612324402)),
INFO :      	                     (14, np.float64(0.9428472324107011)),
INFO :      	                     (15, np.float64(0.9429701782998702))],
INFO :      	 'benign_alpha_mean_round': [(1, 0.9571864853011911),
INFO :      	                             (2, 0.968002926626721),
INFO :      	                             (3, 0.9684177179488715),
INFO :      	                             (4, 0.9685453249776196),
INFO :      	                             (5, 0.9686061554657831),
INFO :      	                             (6, 0.9686255350019891),
INFO :      	                             (7, 0.9686586427906843),
INFO :      	                             (8, 0.9686734190442833),
INFO :      	                             (9, 0.9686840558322698),
INFO :      	                             (10, 0.9686903967511783),
INFO :      	                             (11, 0.9687035687035312),
INFO :      	                             (12, 0.968711016187323),
INFO :      	                             (13, 0.9687208566240066),
INFO :      	                             (14, 0.9687211201248823),
INFO :      	                             (15, 0.9687377220019966)],
INFO :      	 'ensemble_size': [(1, 1),
INFO :      	                   (2, 2),
INFO :      	                   (3, 3),
INFO :      	                   (4, 4),
INFO :      	                   (5, 5),
INFO :      	                   (6, 6),
INFO :      	                   (7, 7),
INFO :      	                   (8, 8),
INFO :      	                   (9, 9),
INFO :      	                   (10, 10),
INFO :      	                   (11, 11),
INFO :      	                   (12, 12),
INFO :      	                   (13, 13),
INFO :      	                   (14, 14),
INFO :      	                   (15, 15)],
INFO :      	 'f1_score': [(1, 0.9833372152167121),
INFO :      	              (2, 0.988273281787484),
INFO :      	              (3, 0.9897747696511492),
INFO :      	              (4, 0.990531698184725),
INFO :      	              (5, 0.9901098314956451),
INFO :      	              (6, 0.9898747895032058),
INFO :      	              (7, 0.9898737775684111),
INFO :      	              (8, 0.990130485957867),
INFO :      	              (9, 0.9901294495959037),
INFO :      	              (10, 0.9901294495959037),
INFO :      	              (11, 0.9903223268073903),
INFO :      	              (12, 0.990192370474729),
INFO :      	              (13, 0.9902563400632698),
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
(ClientAppActor pid=335989)
INFO :      	              (14, 0.9902563400632698),
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
(ClientAppActor pid=335990)
INFO :      	              (15, 0.9902563400632698)],
INFO :      	 'grad_divergence': [(1, np.float64(8.074235215038062)),
INFO :      	                     (2, np.float64(4.865785672143102)),
INFO :      	                     (3, np.float64(3.535773733444512)),
INFO :      	                     (4, np.float64(3.1237729139626027)),
INFO :      	                     (5, np.float64(2.9489956595003606)),
INFO :      	                     (6, np.float64(2.8603368926793338)),
INFO :      	                     (7, np.float64(2.7956233197823166)),
INFO :      	                     (8, np.float64(2.787477349117398)),
INFO :      	                     (9, np.float64(2.71394778508693)),
INFO :      	                     (10, np.float64(2.6866800635121764)),
INFO :      	                     (11, np.float64(2.650524316448718)),
INFO :      	                     (12, np.float64(2.650125104468316)),
INFO :      	                     (13, np.float64(2.6431637526489795)),
INFO :      	                     (14, np.float64(2.6478332159109415)),
INFO :      	                     (15, np.float64(2.576692725904286))],
INFO :      	 'loss': [(1, 0.06107503657018985),
INFO :      	          (2, 0.04955495954671221),
INFO :      	          (3, 0.04396794112419257),
INFO :      	          (4, 0.04104611581779516),
INFO :      	          (5, 0.03932692984654451),
INFO :      	          (6, 0.03787345135069238),
INFO :      	          (7, 0.03690231852602563),
INFO :      	          (8, 0.036210873466784324),
INFO :      	          (9, 0.035715447044904335),
INFO :      	          (10, 0.03528678634241189),
INFO :      	          (11, 0.035001817507318025),
INFO :      	          (12, 0.034647597439222334),
INFO :      	          (13, 0.034520573840584705),
INFO :      	          (14, 0.034274763862219115),
INFO :      	          (15, 0.03413522311198085)],
INFO :      	 'mal_alpha_count_round': [(1, 0),
INFO :      	                           (2, 0),
INFO :      	                           (3, 0),
INFO :      	                           (4, 0),
INFO :      	                           (5, 0),
INFO :      	                           (6, 0),
INFO :      	                           (7, 0),
INFO :      	                           (8, 0),
INFO :      	                           (9, 0),
INFO :      	                           (10, 0),
INFO :      	                           (11, 0),
INFO :      	                           (12, 0),
INFO :      	                           (13, 0),
INFO :      	                           (14, 0),
INFO :      	                           (15, 0)],
INFO :      	 'mal_alpha_mean_round': [(1, nan),
INFO :      	                          (2, nan),
INFO :      	                          (3, nan),
INFO :      	                          (4, nan),
INFO :      	                          (5, nan),
INFO :      	                          (6, nan),
INFO :      	                          (7, nan),
INFO :      	                          (8, nan),
INFO :      	                          (9, nan),
INFO :      	                          (10, nan),
INFO :      	                          (11, nan),
INFO :      	                          (12, nan),
INFO :      	                          (13, nan),
INFO :      	                          (14, nan),
INFO :      	                          (15, nan)],
INFO :      	 'num_examples': [(1, 25053),
INFO :      	                  (2, 25053),
INFO :      	                  (3, 25053),
INFO :      	                  (4, 25053),
INFO :      	                  (5, 25053),
INFO :      	                  (6, 25053),
INFO :      	                  (7, 25053),
INFO :      	                  (8, 25053),
INFO :      	                  (9, 25053),
INFO :      	                  (10, 25053),
INFO :      	                  (11, 25053),
INFO :      	                  (12, 25053),
INFO :      	                  (13, 25053),
INFO :      	                  (14, 25053),
INFO :      	                  (15, 25053)],
INFO :      	 'num_filtered': [(1, 3),
INFO :      	                  (2, 3),
INFO :      	                  (3, 3),
INFO :      	                  (4, 3),

[Round 15] learners=15 acc=0.9945 f1=0.9903

INFO :      	                  (5, 3),
INFO :      	                  (6, 3),
INFO :      	                  (7, 3),
INFO :      	                  (8, 3),
INFO :      	                  (9, 3),
INFO :      	                  (10, 3),
INFO :      	                  (11, 3),
INFO :      	                  (12, 3),
INFO :      	                  (13, 3),
INFO :      	                  (14, 3),
INFO :      	                  (15, 3)],
INFO :      	 'num_filtered_malicious': [(1, 3),
INFO :      	                            (2, 3),
INFO :      	                            (3, 3),
INFO :      	                            (4, 3),
INFO :      	                            (5, 3),
INFO :      	                            (6, 3),
INFO :      	                            (7, 3),
INFO :      	                            (8, 3),
INFO :      	                            (9, 3),
INFO :      	                            (10, 3),
INFO :      	                            (11, 3),
INFO :      	                            (12, 3),
INFO :      	                            (13, 3),
INFO :      	                            (14, 3),
INFO :      	                            (15, 3)],
INFO :      	 'precision': [(1, 0.9804064169654185),
INFO :      	               (2, 0.9870076243814057),
INFO :      	               (3, 0.9879423784480849),
INFO :      	               (4, 0.9884238635214306),
INFO :      	               (5, 0.9883558024652185),
INFO :      	               (6, 0.9878926524522069),
INFO :      	               (7, 0.9879352630218722),
INFO :      	               (8, 0.988235542664279),
INFO :      	               (9, 0.9882783408756106),
INFO :      	               (10, 0.9882783408756106),
INFO :      	               (11, 0.9884932095581594),
INFO :      	               (12, 0.9884072779539904),
INFO :      	               (13, 0.9884933451937423),
INFO :      	               (14, 0.9884933451937423),
INFO :      	               (15, 0.9884933451937423)],
INFO :      	 'recall': [(1, 0.9863374793682754),
INFO :      	            (2, 0.9895514919904392),
INFO :      	            (3, 0.9916350975598063),
INFO :      	            (4, 0.9926762582783725),
INFO :      	            (5, 0.9918878010862047),
INFO :      	            (6, 0.9918878010862047),
INFO :      	            (7, 0.9918421467609049),
INFO :      	            (8, 0.9920544677528713),
INFO :      	            (9, 0.9920088134275715),
INFO :      	            (10, 0.9920088134275715),
INFO :      	            (11, 0.9921794677528712),
INFO :      	            (12, 0.9920048257689384),
INFO :      	            (13, 0.992046492435605),
INFO :      	            (14, 0.992046492435605),
INFO :      	            (15, 0.992046492435605)],
INFO :      	 'residual_loss': [(1, np.float64(0.04472870475099404)),
INFO :      	                   (2, np.float64(0.033054762155919966)),
INFO :      	                   (3, np.float64(0.03261227285660499)),
INFO :      	                   (4, np.float64(0.03247622352625643)),
INFO :      	                   (5, np.float64(0.032411383395558414)),
INFO :      	                   (6, np.float64(0.03239072765109643)),
INFO :      	                   (7, np.float64(0.032355441318406744)),
INFO :      	                   (8, np.float64(0.0323396964673409)),
INFO :      	                   (9, np.float64(0.03232836008775143)),
INFO :      	                   (10, np.float64(0.0323216016508867)),
INFO :      	                   (11, np.float64(0.03230756444533413)),
INFO :      	                   (12, np.float64(0.03229962505153095)),
INFO :      	                   (13, np.float64(0.032289139512090045)),
INFO :      	                   (14, np.float64(0.032288860880332636)),
INFO :      	                   (15, np.float64(0.032271169976578376))]}
INFO :
WARNING :   DEPRECATED FEATURE: flwr.simulation.start_simulation() is deprecated.
	Instead, use the `flwr run` CLI command to start a local simulation in your Flower app, as shown for example below:

		$ flwr new  # Create a new Flower app from a template

		$ flwr run  # Run the Flower app in Simulation Mode

	Using `start_simulation()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.

INFO :      Starting Flower simulation, config: num_rounds=15, no round_timeout
(ClientAppActor pid=335990) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 7x across cluster]
(ClientAppActor pid=335990)             This is a deprecated feature. It will be removed [repeated 7x across cluster]
(ClientAppActor pid=335990)             entirely in future versions of Flower. [repeated 7x across cluster]

[Sweep] mal_frac=0.30 acc=0.9945 filtered_mal=45/45
[Poison] mal_frac=0.5, flip_prob=1.0, malicious_clients=[0, 4, 5, 7, 8]

2026-09-14 21:23:40,293	INFO worker.py:1771 -- Started a local Ray instance.
INFO :      Flower VCE: Ray initialized with resources: {'node:172.24.90.50': 1.0, 'accelerator_type:G': 1.0, 'node:__internal_head__': 1.0, 'CPU': 20.0, 'memory': 13481725134.0, 'object_store_memory': 6740862566.0, 'GPU': 1.0}
INFO :      Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
INFO :      Flower VCE: Resources for each Virtual Client: {'num_cpus': 10, 'num_gpus': 0.5}
INFO :      Flower VCE: Creating VirtualClientEngineActorPool with 2 actors
INFO :      [INIT]
INFO :      Using initial global parameters provided by strategy
INFO :      Starting evaluation of initial global parameters
INFO :      Evaluation returned no results (`None`)
INFO :
INFO :      [ROUND 1]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=338098) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context`
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)             This is a deprecated feature. It will be removed
(ClientAppActor pid=338098)             entirely in future versions of Flower.
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 6x across cluster]
(ClientAppActor pid=338097)             This is a deprecated feature. It will be removed [repeated 6x across cluster]
(ClientAppActor pid=338097)             entirely in future versions of Flower. [repeated 6x across cluster]
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
INFO :      aggregate_fit: received 10 results and 0 failures
INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)

[Round 1] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9259
[Alpha Filtering] Filtered client alpha=0.8947 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8947 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8948 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8947 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8947 (malicious=True)
[Alpha Filtering] Filtered 5 clients (5 malicious), kept 5
[Round 1] learners=1 acc=0.9903 f1=0.9860

(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 2]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=338098)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=338098)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
INFO :      aggregate_fit: received 10 results and 0 failures
INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)

[Round 2] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9257
[Alpha Filtering] Filtered client alpha=0.8811 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8840 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8834 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8836 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8843 (malicious=True)
[Alpha Filtering] Filtered 5 clients (5 malicious), kept 5
[Round 2] learners=2 acc=0.9919 f1=0.9880

(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 3]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=338098)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=338098)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
INFO :      aggregate_fit: received 10 results and 0 failures
INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)

[Round 3] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9258
[Alpha Filtering] Filtered client alpha=0.8828 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8833 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8824 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8834 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8836 (malicious=True)
[Alpha Filtering] Filtered 5 clients (5 malicious), kept 5
[Round 3] learners=3 acc=0.9936 f1=0.9904

(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 9x across cluster]
(ClientAppActor pid=338098)             This is a deprecated feature. It will be removed [repeated 9x across cluster]
(ClientAppActor pid=338098)             entirely in future versions of Flower. [repeated 9x across cluster]
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 4]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 17x across cluster]
(ClientAppActor pid=338097)             This is a deprecated feature. It will be removed [repeated 17x across cluster]
(ClientAppActor pid=338097)             entirely in future versions of Flower. [repeated 17x across cluster]
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 4] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9253
[Alpha Filtering] Filtered client alpha=0.8807 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8829 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8829 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8810 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8831 (malicious=True)
[Alpha Filtering] Filtered 5 clients (5 malicious), kept 5

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 5]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 4] learners=4 acc=0.9945 f1=0.9912

(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=338097)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=338097)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 5] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9257
[Alpha Filtering] Filtered client alpha=0.8826 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8825 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8834 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8824 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8835 (malicious=True)
[Alpha Filtering] Filtered 5 clients (5 malicious), kept 5

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 6]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 5] learners=5 acc=0.9943 f1=0.9902

(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=338097)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=338097)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 6] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9255
[Alpha Filtering] Filtered client alpha=0.8839 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8819 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8826 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8821 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8816 (malicious=True)
[Alpha Filtering] Filtered 5 clients (5 malicious), kept 5

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 7]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 6] learners=6 acc=0.9941 f1=0.9901

(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=338097)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=338097)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 7] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9255
[Alpha Filtering] Filtered client alpha=0.8826 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8830 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8808 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8817 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8836 (malicious=True)
[Alpha Filtering] Filtered 5 clients (5 malicious), kept 5

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 11x across cluster]
(ClientAppActor pid=338098)             This is a deprecated feature. It will be removed [repeated 11x across cluster]
(ClientAppActor pid=338098)             entirely in future versions of Flower. [repeated 11x across cluster]
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 8]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 7] learners=7 acc=0.9941 f1=0.9901

(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 15x across cluster]
(ClientAppActor pid=338097)             This is a deprecated feature. It will be removed [repeated 15x across cluster]
(ClientAppActor pid=338097)             entirely in future versions of Flower. [repeated 15x across cluster]
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 8] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9257
[Alpha Filtering] Filtered client alpha=0.8839 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8814 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8824 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8832 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8829 (malicious=True)
[Alpha Filtering] Filtered 5 clients (5 malicious), kept 5

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 9]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 8] learners=8 acc=0.9943 f1=0.9902

(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=338097)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=338097)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 9] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9253
[Alpha Filtering] Filtered client alpha=0.8824 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8820 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8801 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8820 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8829 (malicious=True)
[Alpha Filtering] Filtered 5 clients (5 malicious), kept 5

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 10]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 9] learners=9 acc=0.9941 f1=0.9899

(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=338097)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=338097)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 10] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9261
[Alpha Filtering] Filtered client alpha=0.8833 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8840 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8836 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8846 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8817 (malicious=True)
[Alpha Filtering] Filtered 5 clients (5 malicious), kept 5

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 11]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 10] learners=10 acc=0.9943 f1=0.9900

(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=338098)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=338098)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 11] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9258
[Alpha Filtering] Filtered client alpha=0.8832 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8838 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8822 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8830 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8828 (malicious=True)
[Alpha Filtering] Filtered 5 clients (5 malicious), kept 5

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 11x across cluster]
(ClientAppActor pid=338098)             This is a deprecated feature. It will be removed [repeated 11x across cluster]
(ClientAppActor pid=338098)             entirely in future versions of Flower. [repeated 11x across cluster]
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 12]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 11] learners=11 acc=0.9945 f1=0.9902

(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 15x across cluster]
(ClientAppActor pid=338098)             This is a deprecated feature. It will be removed [repeated 15x across cluster]
(ClientAppActor pid=338098)             entirely in future versions of Flower. [repeated 15x across cluster]
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 12] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9252
[Alpha Filtering] Filtered client alpha=0.8827 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8821 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8816 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8814 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8802 (malicious=True)
[Alpha Filtering] Filtered 5 clients (5 malicious), kept 5

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 13]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 12] learners=12 acc=0.9945 f1=0.9902

(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=338098)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=338098)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 13] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9258
[Alpha Filtering] Filtered client alpha=0.8836 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8828 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8831 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8832 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8816 (malicious=True)
[Alpha Filtering] Filtered 5 clients (5 malicious), kept 5

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 14]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 13] learners=13 acc=0.9945 f1=0.9902

(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=338098)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=338098)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 14] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9251
[Alpha Filtering] Filtered client alpha=0.8811 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8815 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8811 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8814 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8818 (malicious=True)
[Alpha Filtering] Filtered 5 clients (5 malicious), kept 5

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 15]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 14] learners=14 acc=0.9945 f1=0.9902

(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=338098)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=338098)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 15] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9260
[Alpha Filtering] Filtered client alpha=0.8830 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8827 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8840 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8843 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8828 (malicious=True)
[Alpha Filtering] Filtered 5 clients (5 malicious), kept 5

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [SUMMARY]
INFO :      Run finished 15 round(s) in 110.81s
INFO :      	History (loss, distributed):
INFO :      		round 1: 0.0
INFO :      		round 2: 0.0
INFO :      		round 3: 0.0
INFO :      		round 4: 0.0
INFO :      		round 5: 0.0
INFO :      		round 6: 0.0
INFO :      		round 7: 0.0
INFO :      		round 8: 0.0
INFO :      		round 9: 0.0
INFO :      		round 10: 0.0
INFO :      		round 11: 0.0
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098)
(ClientAppActor pid=338098) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 12x across cluster]
(ClientAppActor pid=338098)             This is a deprecated feature. It will be removed [repeated 12x across cluster]
(ClientAppActor pid=338098)             entirely in future versions of Flower. [repeated 12x across cluster]
INFO :      		round 12: 0.0
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
(ClientAppActor pid=338097)
INFO :      		round 13: 0.0
INFO :      		round 14: 0.0
INFO :      		round 15: 0.0
INFO :      	History (metrics, distributed, fit):
INFO :      	{'accuracy': [(1, 0.9902861985787861),
INFO :      	              (2, 0.9919160310320099),
INFO :      	              (3, 0.9936110567833627),
INFO :      	              (4, 0.994523762957168),
INFO :      	              (5, 0.9942629897646522),
INFO :      	              (6, 0.9941326031683942),
INFO :      	              (7, 0.9941326031683942),
INFO :      	              (8, 0.9942629897646522),
INFO :      	              (9, 0.9941326031683942),
INFO :      	              (10, 0.9942629897646522),
INFO :      	              (11, 0.994458569659039),
INFO :      	              (12, 0.994458569659039),
INFO :      	              (13, 0.994458569659039),
INFO :      	              (14, 0.994458569659039),
INFO :      	              (15, 0.994458569659039)],
INFO :      	 'alpha': [(1, np.float64(0.9571169356669451)),
INFO :      	           (2, np.float64(0.9680267134828521)),
INFO :      	           (3, np.float64(0.9684280398530498)),
INFO :      	           (4, np.float64(0.9685434638877654)),
INFO :      	           (5, np.float64(0.9686029162632958)),
INFO :      	           (6, np.float64(0.9686177141280595)),
INFO :      	           (7, np.float64(0.9686530820242079)),
INFO :      	           (8, np.float64(0.9686724717053661)),
INFO :      	           (9, np.float64(0.9686853566600648)),
INFO :      	           (10, np.float64(0.9686927114793342)),
INFO :      	           (11, np.float64(0.9686942048781846)),
INFO :      	           (12, np.float64(0.9687062156409085)),
INFO :      	           (13, np.float64(0.968716155776302)),
INFO :      	           (14, np.float64(0.9687141771289671)),
INFO :      	           (15, np.float64(0.9687248932543999))],
INFO :      	 'alpha_threshold': [(1, np.float64(0.9259184009125111)),
INFO :      	                     (2, np.float64(0.9256637863524737)),
INFO :      	                     (3, np.float64(0.925762139156733)),
INFO :      	                     (4, np.float64(0.9253256845147737)),
INFO :      	                     (5, np.float64(0.9257377559558139)),
INFO :      	                     (6, np.float64(0.9255069985181557)),
INFO :      	                     (7, np.float64(0.9255010210359854)),
INFO :      	                     (8, np.float64(0.9257144432883179)),
INFO :      	                     (9, np.float64(0.9252862396170791)),
INFO :      	                     (10, np.float64(0.9260652889751503)),
INFO :      	                     (11, np.float64(0.9258452052176128)),
INFO :      	                     (12, np.float64(0.9251586429604488)),
INFO :      	                     (13, np.float64(0.9257891684953113)),
INFO :      	                     (14, np.float64(0.9250521630652774)),
INFO :      	                     (15, np.float64(0.926038619280178))],
INFO :      	 'benign_alpha_mean_round': [(1, 0.9571169356669451),
INFO :      	                             (2, 0.9680267134828521),
INFO :      	                             (3, 0.9684280398530498),
INFO :      	                             (4, 0.9685434638877654),
INFO :      	                             (5, 0.9686029162632958),
INFO :      	                             (6, 0.9686177141280595),
INFO :      	                             (7, 0.9686530820242079),
INFO :      	                             (8, 0.9686724717053661),
INFO :      	                             (9, 0.9686853566600648),
INFO :      	                             (10, 0.9686927114793342),
INFO :      	                             (11, 0.9686942048781846),
INFO :      	                             (12, 0.9687062156409085),
INFO :      	                             (13, 0.968716155776302),
INFO :      	                             (14, 0.9687141771289671),
INFO :      	                             (15, 0.9687248932543999)],
INFO :      	 'ensemble_size': [(1, 1),
INFO :      	                   (2, 2),
INFO :      	                   (3, 3),
INFO :      	                   (4, 4),
INFO :      	                   (5, 5),
INFO :      	                   (6, 6),
INFO :      	                   (7, 7),
INFO :      	                   (8, 8),
INFO :      	                   (9, 9),
INFO :      	                   (10, 10),
INFO :      	                   (11, 11),
INFO :      	                   (12, 12),
INFO :      	                   (13, 13),
INFO :      	                   (14, 14),
INFO :      	                   (15, 15)],
INFO :      	 'f1_score': [(1, 0.9860184963217061),
INFO :      	              (2, 0.98802467800839),
INFO :      	              (3, 0.9903501383909469),
INFO :      	              (4, 0.99123119836745),
INFO :      	              (5, 0.9902395321891482),
INFO :      	              (6, 0.9901097063137441),
INFO :      	              (7, 0.9901086909345775),
INFO :      	              (8, 0.9902355102326795),
INFO :      	              (9, 0.9898726326841697),
INFO :      	              (10, 0.9900004683057568),
INFO :      	              (11, 0.990192308000858),
INFO :      	              (12, 0.990192308000858),
INFO :      	              (13, 0.990192308000858),
INFO :      	              (14, 0.990192308000858),
INFO :      	              (15, 0.990192308000858)],
INFO :      	 'grad_divergence': [(1, np.float64(7.447764042019844)),
INFO :      	                     (2, np.float64(5.56912761554122)),
INFO :      	                     (3, np.float64(4.518567334301769)),
INFO :      	                     (4, np.float64(4.2155549801886085)),
INFO :      	                     (5, np.float64(4.06161825619638)),
INFO :      	                     (6, np.float64(3.992630259692669)),
INFO :      	                     (7, np.float64(3.895887093432248)),
INFO :      	                     (8, np.float64(3.90732049504295)),
INFO :      	                     (9, np.float64(3.8439897258765994)),
INFO :      	                     (10, np.float64(3.736288638226688)),
INFO :      	                     (11, np.float64(3.7991263914853333)),
INFO :      	                     (12, np.float64(3.711691306531429)),
INFO :      	                     (13, np.float64(3.6800948369316755)),
INFO :      	                     (14, np.float64(3.8070077383425085)),
INFO :      	                     (15, np.float64(3.71560364048928))],
INFO :      	 'loss': [(1, 0.05953209658263676),
INFO :      	          (2, 0.04896236539146403),
INFO :      	          (3, 0.04376483754509217),
INFO :      	          (4, 0.04079475834313859),
INFO :      	          (5, 0.03906164719874409),
INFO :      	          (6, 0.037853170822341915),
INFO :      	          (7, 0.03694713857750828),
INFO :      	          (8, 0.0364313354377274),
INFO :      	          (9, 0.035739303849512676),
INFO :      	          (10, 0.03516064667253977),
INFO :      	          (11, 0.03490183559192992),
INFO :      	          (12, 0.03460761410500474),
INFO :      	          (13, 0.034505139690749115),
INFO :      	          (14, 0.034316973825447315),
INFO :      	          (15, 0.0341889047711666)],
INFO :      	 'mal_alpha_count_round': [(1, 0),
INFO :      	                           (2, 0),
INFO :      	                           (3, 0),
INFO :      	                           (4, 0),
INFO :      	                           (5, 0),
INFO :      	                           (6, 0),
INFO :      	                           (7, 0),
INFO :      	                           (8, 0),
INFO :      	                           (9, 0),
INFO :      	                           (10, 0),
INFO :      	                           (11, 0),
INFO :      	                           (12, 0),
INFO :      	                           (13, 0),
INFO :      	                           (14, 0),
INFO :      	                           (15, 0)],
INFO :      	 'mal_alpha_mean_round': [(1, nan),
INFO :      	                          (2, nan),
INFO :      	                          (3, nan),
INFO :      	                          (4, nan),
INFO :      	                          (5, nan),
INFO :      	                          (6, nan),
INFO :      	                          (7, nan),
INFO :      	                          (8, nan),
INFO :      	                          (9, nan),
INFO :      	                          (10, nan),
INFO :      	                          (11, nan),
INFO :      	                          (12, nan),
INFO :      	                          (13, nan),
INFO :      	                          (14, nan),
INFO :      	                          (15, nan)],
INFO :      	 'num_examples': [(1, 17895),
INFO :      	                  (2, 17895),
INFO :      	                  (3, 17895),
INFO :      	                  (4, 17895),
INFO :      	                  (5, 17895),
INFO :      	                  (6, 17895),
INFO :      	                  (7, 17895),
INFO :      	                  (8, 17895),
INFO :      	                  (9, 17895),
INFO :      	                  (10, 17895),
INFO :      	                  (11, 17895),
INFO :      	                  (12, 17895),
INFO :      	                  (13, 17895),
INFO :      	                  (14, 17895),
INFO :      	                  (15, 17895)],
INFO :      	 'num_filtered': [(1, 5),
INFO :      	                  (2, 5),
INFO :      	                  (3, 5),
INFO :      	                  (4, 5),
INFO :      	                  (5, 5),
INFO :      	                  (6, 5),
INFO :      	                  (7, 5),
INFO :      	                  (8, 5),
INFO :      	                  (9, 5),
INFO :      	                  (10, 5),
INFO :      	                  (11, 5),
INFO :      	                  (12, 5),
INFO :      	                  (13, 5),
INFO :      	                  (14, 5),
INFO :      	                  (15, 5)],
INFO :      	 'num_filtered_malicious': [(1, 5),
INFO :      	                            (2, 5),
INFO :      	                            (3, 5),
INFO :      	                            (4, 5),
INFO :      	                            (5, 5),
INFO :      	                            (6, 5),
INFO :      	                            (7, 5),
INFO :      	                            (8, 5),
INFO :      	                            (9, 5),
INFO :      	                            (10, 5),
INFO :      	                            (11, 5),
INFO :      	                            (12, 5),
INFO :      	                            (13, 5),
INFO :      	                            (14, 5),
INFO :      	                            (15, 5)],
INFO :      	 'precision': [(1, 0.9844699484285231),
INFO :      	               (2, 0.9858485005875228),
INFO :      	               (3, 0.9878808013247872),
INFO :      	               (4, 0.9886521530669506),
INFO :      	               (5, 0.9884417085243599),
INFO :      	               (6, 0.9883555238057389),
INFO :      	               (7, 0.988398113587581),
INFO :      	               (8, 0.9886124453576546),
INFO :      	               (9, 0.9879776840475929),
INFO :      	               (10, 0.9881492677249913),
INFO :      	               (11, 0.988407090339524),
INFO :      	               (12, 0.988407090339524),

[Round 15] learners=15 acc=0.9945 f1=0.9902

INFO :      	               (13, 0.988407090339524),
INFO :      	               (14, 0.988407090339524),
INFO :      	               (15, 0.988407090339524)],
INFO :      	 'recall': [(1, 0.9876136028983721),
INFO :      	            (2, 0.990242862793039),
INFO :      	            (3, 0.9928681350290728),
INFO :      	            (4, 0.9938623572901043),
INFO :      	            (5, 0.9920624430701376),
INFO :      	            (6, 0.9918878010862047),
INFO :      	            (7, 0.9918421467609049),
INFO :      	            (8, 0.9918798257689384),
INFO :      	            (9, 0.9917964924356051),
INFO :      	            (10, 0.9918798257689384),
INFO :      	            (11, 0.9920048257689384),
INFO :      	            (12, 0.9920048257689384),
INFO :      	            (13, 0.9920048257689384),
INFO :      	            (14, 0.9920048257689384),
INFO :      	            (15, 0.9920048257689384)],
INFO :      	 'residual_loss': [(1, np.float64(0.04480453514094864)),
INFO :      	                   (2, np.float64(0.033029364131923235)),
INFO :      	                   (3, np.float64(0.03260126674547791)),
INFO :      	                   (4, np.float64(0.0324782116391829)),
INFO :      	                   (5, np.float64(0.03241483857988246)),
INFO :      	                   (6, np.float64(0.032399067856105315)),
INFO :      	                   (7, np.float64(0.03236137256824544)),
INFO :      	                   (8, np.float64(0.03234071021101304)),
INFO :      	                   (9, np.float64(0.03232697520138962)),
INFO :      	                   (10, np.float64(0.032319138161838054)),
INFO :      	                   (11, np.float64(0.03231754542195371)),
INFO :      	                   (12, np.float64(0.0323047487371202)),
INFO :      	                   (13, np.float64(0.03229415490957243)),
INFO :      	                   (14, np.float64(0.032296263000794814)),
INFO :      	                   (15, np.float64(0.032284843820546354))]}
INFO :
WARNING :   DEPRECATED FEATURE: flwr.simulation.start_simulation() is deprecated.
	Instead, use the `flwr run` CLI command to start a local simulation in your Flower app, as shown for example below:

		$ flwr new  # Create a new Flower app from a template

		$ flwr run  # Run the Flower app in Simulation Mode

	Using `start_simulation()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.

INFO :      Starting Flower simulation, config: num_rounds=15, no round_timeout
(ClientAppActor pid=338097) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 5x across cluster]
(ClientAppActor pid=338097)             This is a deprecated feature. It will be removed [repeated 5x across cluster]
(ClientAppActor pid=338097)             entirely in future versions of Flower. [repeated 5x across cluster]

[Sweep] mal_frac=0.50 acc=0.9945 filtered_mal=75/75
[Poison] mal_frac=0.7, flip_prob=1.0, malicious_clients=[0, 1, 3, 4, 5, 7, 8]

2026-09-14 21:25:34,800	INFO worker.py:1771 -- Started a local Ray instance.
INFO :      Flower VCE: Ray initialized with resources: {'node:172.24.90.50': 1.0, 'accelerator_type:G': 1.0, 'node:__internal_head__': 1.0, 'CPU': 20.0, 'object_store_memory': 6741512601.0, 'memory': 13483025204.0, 'GPU': 1.0}
INFO :      Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
INFO :      Flower VCE: Resources for each Virtual Client: {'num_cpus': 10, 'num_gpus': 0.5}
INFO :      Flower VCE: Creating VirtualClientEngineActorPool with 2 actors
INFO :      [INIT]
INFO :      Using initial global parameters provided by strategy
INFO :      Starting evaluation of initial global parameters
INFO :      Evaluation returned no results (`None`)
INFO :
INFO :      [ROUND 1]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=340217) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context`
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)             This is a deprecated feature. It will be removed
(ClientAppActor pid=340217)             entirely in future versions of Flower.
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 6x across cluster]
(ClientAppActor pid=340217)             This is a deprecated feature. It will be removed [repeated 6x across cluster]
(ClientAppActor pid=340217)             entirely in future versions of Flower. [repeated 6x across cluster]
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
INFO :      aggregate_fit: received 10 results and 0 failures
INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)

[Round 1] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9135
[Alpha Filtering] Filtered client alpha=0.8947 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8947 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8948 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8947 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8946 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8946 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8947 (malicious=True)
[Alpha Filtering] Filtered 7 clients (7 malicious), kept 3
[Round 1] learners=1 acc=0.9896 f1=0.9837

(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 2]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=340218)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=340218)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
INFO :      aggregate_fit: received 10 results and 0 failures
INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)

[Round 2] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9084
[Alpha Filtering] Filtered client alpha=0.8829 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8830 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8832 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8819 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8818 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8829 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8840 (malicious=True)
[Alpha Filtering] Filtered 7 clients (7 malicious), kept 3
[Round 2] learners=2 acc=0.9919 f1=0.9888

(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 3]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=340218)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=340218)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
INFO :      aggregate_fit: received 10 results and 0 failures
INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)

[Round 3] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9083
[Alpha Filtering] Filtered client alpha=0.8827 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8829 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8816 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8833 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8821 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8832 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8816 (malicious=True)
[Alpha Filtering] Filtered 7 clients (7 malicious), kept 3
[Round 3] learners=3 acc=0.9929 f1=0.9896

(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 11x across cluster]
(ClientAppActor pid=340217)             This is a deprecated feature. It will be removed [repeated 11x across cluster]
(ClientAppActor pid=340217)             entirely in future versions of Flower. [repeated 11x across cluster]
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 4]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 15x across cluster]
(ClientAppActor pid=340217)             This is a deprecated feature. It will be removed [repeated 15x across cluster]
(ClientAppActor pid=340217)             entirely in future versions of Flower. [repeated 15x across cluster]
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 4] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9079
[Alpha Filtering] Filtered client alpha=0.8817 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8825 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8812 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8823 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8818 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8816 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8822 (malicious=True)
[Alpha Filtering] Filtered 7 clients (7 malicious), kept 3

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 5]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 4] learners=4 acc=0.9933 f1=0.9893

(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=340217)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=340217)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 5] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9085
[Alpha Filtering] Filtered client alpha=0.8832 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8831 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8836 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8825 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8814 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8824 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8830 (malicious=True)
[Alpha Filtering] Filtered 7 clients (7 malicious), kept 3

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 6]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 5] learners=5 acc=0.9939 f1=0.9899

(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=340218)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=340218)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 6] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9082
[Alpha Filtering] Filtered client alpha=0.8824 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8814 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8823 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8827 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8832 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8818 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8827 (malicious=True)
[Alpha Filtering] Filtered 7 clients (7 malicious), kept 3

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 7]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 6] learners=6 acc=0.9943 f1=0.9903

(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=340218)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=340218)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 7] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9084
[Alpha Filtering] Filtered client alpha=0.8809 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8821 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8822 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8831 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8826 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8840 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8835 (malicious=True)
[Alpha Filtering] Filtered 7 clients (7 malicious), kept 3

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 10x across cluster]
(ClientAppActor pid=340217)             This is a deprecated feature. It will be removed [repeated 10x across cluster]
(ClientAppActor pid=340217)             entirely in future versions of Flower. [repeated 10x across cluster]
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 8]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 7] learners=7 acc=0.9941 f1=0.9899

(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 16x across cluster]
(ClientAppActor pid=340218)             This is a deprecated feature. It will be removed [repeated 16x across cluster]
(ClientAppActor pid=340218)             entirely in future versions of Flower. [repeated 16x across cluster]
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 8] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9078
[Alpha Filtering] Filtered client alpha=0.8810 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8835 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8819 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8810 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8818 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8820 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8807 (malicious=True)
[Alpha Filtering] Filtered 7 clients (7 malicious), kept 3

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 9]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 8] learners=8 acc=0.9941 f1=0.9898

(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=340218)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=340218)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 9] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9084
[Alpha Filtering] Filtered client alpha=0.8826 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8816 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8821 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8829 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8830 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8829 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8832 (malicious=True)
[Alpha Filtering] Filtered 7 clients (7 malicious), kept 3

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 10]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 9] learners=9 acc=0.9943 f1=0.9901

(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 17x across cluster]
(ClientAppActor pid=340217)             This is a deprecated feature. It will be removed [repeated 17x across cluster]
(ClientAppActor pid=340217)             entirely in future versions of Flower. [repeated 17x across cluster]
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 10] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9088
[Alpha Filtering] Filtered client alpha=0.8842 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8825 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8841 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8826 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8832 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8830 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8823 (malicious=True)
[Alpha Filtering] Filtered 7 clients (7 malicious), kept 3

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 11x across cluster]
(ClientAppActor pid=340217)             This is a deprecated feature. It will be removed [repeated 11x across cluster]
(ClientAppActor pid=340217)             entirely in future versions of Flower. [repeated 11x across cluster]
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 11]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 10] learners=10 acc=0.9946 f1=0.9903

(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 14x across cluster]
(ClientAppActor pid=340218)             This is a deprecated feature. It will be removed [repeated 14x across cluster]
(ClientAppActor pid=340218)             entirely in future versions of Flower. [repeated 14x across cluster]
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 11] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9089
[Alpha Filtering] Filtered client alpha=0.8838 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8838 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8839 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8823 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8834 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8815 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8845 (malicious=True)
[Alpha Filtering] Filtered 7 clients (7 malicious), kept 3

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 12]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 11] learners=11 acc=0.9946 f1=0.9903

(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 16x across cluster]
(ClientAppActor pid=340217)             This is a deprecated feature. It will be removed [repeated 16x across cluster]
(ClientAppActor pid=340217)             entirely in future versions of Flower. [repeated 16x across cluster]
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 12] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9087
[Alpha Filtering] Filtered client alpha=0.8832 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8827 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8827 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8826 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8833 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8838 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8823 (malicious=True)
[Alpha Filtering] Filtered 7 clients (7 malicious), kept 3

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 13]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 12] learners=12 acc=0.9945 f1=0.9902

(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=340218)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=340218)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 13] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9078
[Alpha Filtering] Filtered client alpha=0.8821 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8815 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8806 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8815 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8812 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8812 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8834 (malicious=True)
[Alpha Filtering] Filtered 7 clients (7 malicious), kept 3

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 9x across cluster]
(ClientAppActor pid=340217)             This is a deprecated feature. It will be removed [repeated 9x across cluster]
(ClientAppActor pid=340217)             entirely in future versions of Flower. [repeated 9x across cluster]
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 14]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 13] learners=13 acc=0.9945 f1=0.9903

(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 17x across cluster]
(ClientAppActor pid=340218)             This is a deprecated feature. It will be removed [repeated 17x across cluster]
(ClientAppActor pid=340218)             entirely in future versions of Flower. [repeated 17x across cluster]
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 14] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9086
[Alpha Filtering] Filtered client alpha=0.8821 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8830 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8836 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8814 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8826 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8833 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8837 (malicious=True)
[Alpha Filtering] Filtered 7 clients (7 malicious), kept 3

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [ROUND 15]
INFO :      configure_fit: strategy sampled 10 clients (out of 10)

[Round 14] learners=14 acc=0.9946 f1=0.9901

(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217) WARNING :   DEPRECATED FEATURE: `client_fn` now expects a signature `def client_fn(context: Context)`.The provided `client_fn` has signature: {'cid': <Parameter "cid">}. You can import the `Context` like this: `from flwr.common import Context` [repeated 18x across cluster]
(ClientAppActor pid=340217)             This is a deprecated feature. It will be removed [repeated 18x across cluster]
(ClientAppActor pid=340217)             entirely in future versions of Flower. [repeated 18x across cluster]
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
INFO :      aggregate_fit: received 10 results and 0 failures

[Round 15] 10 clients succeeded, 0 failed
[Alpha Filtering] Mean alpha: 0.9091
[Alpha Filtering] Filtered client alpha=0.8840 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8826 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8840 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8833 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8832 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8839 (malicious=True)
[Alpha Filtering] Filtered client alpha=0.8835 (malicious=True)
[Alpha Filtering] Filtered 7 clients (7 malicious), kept 3

INFO :      configure_evaluate: strategy sampled 10 clients (out of 10)
INFO :      aggregate_evaluate: received 10 results and 0 failures
INFO :
INFO :      [SUMMARY]
INFO :      Run finished 15 round(s) in 111.51s
INFO :      	History (loss, distributed):
INFO :      		round 1: 0.0
INFO :      		round 2: 0.0
INFO :      		round 3: 0.0
INFO :      		round 4: 0.0
INFO :      		round 5: 0.0
INFO :      		round 6: 0.0
INFO :      		round 7: 0.0
INFO :      		round 8: 0.0
INFO :      		round 9: 0.0
INFO :      		round 10: 0.0
INFO :      		round 11: 0.0
INFO :      		round 12: 0.0
INFO :      		round 13: 0.0
INFO :      		round 14: 0.0
INFO :      		round 15: 0.0
INFO :      	History (metrics, distributed, fit):
INFO :      	{'accuracy': [(1, 0.9896342655974966),
INFO :      	              (2, 0.9918508377338809),
INFO :      	              (3, 0.9928939305039441),
INFO :      	              (4, 0.9932850902927179),
INFO :      	              (5, 0.9939370232740075),
INFO :      	              (6, 0.9943281830627811),
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340217)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
(ClientAppActor pid=340218)
INFO :      	              (7, 0.9941326031683942),
INFO :      	              (8, 0.9940674098702653),
INFO :      	              (9, 0.9943281830627811),
INFO :      	              (10, 0.994588956255297),
INFO :      	              (11, 0.994588956255297),
INFO :      	              (12, 0.994458569659039),
INFO :      	              (13, 0.994523762957168),
INFO :      	              (14, 0.994588956255297),
INFO :      	              (15, 0.994458569659039)],
INFO :      	 'alpha': [(1, np.float64(0.9572345150146765)),
INFO :      	           (2, np.float64(0.9680364244979387)),
INFO :      	           (3, np.float64(0.9684102274666714)),
INFO :      	           (4, np.float64(0.9685355582698519)),
INFO :      	           (5, np.float64(0.9685769326200099)),
INFO :      	           (6, np.float64(0.9686150760981453)),
INFO :      	           (7, np.float64(0.9686379783738069)),
INFO :      	           (8, np.float64(0.9686461530773576)),
INFO :      	           (9, np.float64(0.9686683961436279)),
INFO :      	           (10, np.float64(0.9686882529041649)),
INFO :      	           (11, np.float64(0.9686876778401775)),
INFO :      	           (12, np.float64(0.9686965184438862)),
INFO :      	           (13, np.float64(0.9686977092867414)),
INFO :      	           (14, np.float64(0.968705322059011)),
INFO :      	           (15, np.float64(0.968700794752159))],
INFO :      	 'alpha_threshold': [(1, np.float64(0.9134600464278206)),
INFO :      	                     (2, np.float64(0.9083829935984358)),
INFO :      	                     (3, np.float64(0.9082684165542464)),
INFO :      	                     (4, np.float64(0.9078935715066674)),
INFO :      	                     (5, np.float64(0.908480379160683)),
INFO :      	                     (6, np.float64(0.9082391504052157)),
INFO :      	                     (7, np.float64(0.9084203563132707)),
INFO :      	                     (8, np.float64(0.9077861933593144)),
INFO :      	                     (9, np.float64(0.9084349471099797)),
INFO :      	                     (10, np.float64(0.908805716105624)),
INFO :      	                     (11, np.float64(0.908930456397437)),
INFO :      	                     (12, np.float64(0.908662682041616)),
INFO :      	                     (13, np.float64(0.9077628397124926)),
INFO :      	                     (14, np.float64(0.9085790683437835)),
INFO :      	                     (15, np.float64(0.9090663199598662))],
INFO :      	 'benign_alpha_mean_round': [(1, 0.9572345150146765),
INFO :      	                             (2, 0.9680364244979387),
INFO :      	                             (3, 0.9684102274666714),
INFO :      	                             (4, 0.9685355582698519),
INFO :      	                             (5, 0.9685769326200099),
INFO :      	                             (6, 0.9686150760981453),
INFO :      	                             (7, 0.9686379783738069),
INFO :      	                             (8, 0.9686461530773576),
INFO :      	                             (9, 0.9686683961436279),
INFO :      	                             (10, 0.9686882529041649),
INFO :      	                             (11, 0.9686876778401775),
INFO :      	                             (12, 0.9686965184438862),
INFO :      	                             (13, 0.9686977092867414),
INFO :      	                             (14, 0.968705322059011),
INFO :      	                             (15, 0.968700794752159)],
INFO :      	 'ensemble_size': [(1, 1),
INFO :      	                   (2, 2),
INFO :      	                   (3, 3),
INFO :      	                   (4, 4),
INFO :      	                   (5, 5),
INFO :      	                   (6, 6),
INFO :      	                   (7, 7),
INFO :      	                   (8, 8),
INFO :      	                   (9, 9),
INFO :      	                   (10, 10),
INFO :      	                   (11, 11),
INFO :      	                   (12, 12),
INFO :      	                   (13, 13),
INFO :      	                   (14, 14),
INFO :      	                   (15, 15)],
INFO :      	 'f1_score': [(1, 0.9837086385670366),
INFO :      	              (2, 0.9888469405465927),
INFO :      	              (3, 0.989615823365314),
INFO :      	              (4, 0.9892771670368926),
INFO :      	              (5, 0.9899140573647284),
INFO :      	              (6, 0.9902976302620417),
INFO :      	              (7, 0.9898676867506847),
INFO :      	              (8, 0.989802610027691),
INFO :      	              (9, 0.9900624982345863),
INFO :      	              (10, 0.9903212584599264),
INFO :      	              (11, 0.9903212584599264),
INFO :      	              (12, 0.9901914097101868),
INFO :      	              (13, 0.9902553629484785),
INFO :      	              (14, 0.9900857845280823),
INFO :      	              (15, 0.9899568036260452)],
INFO :      	 'grad_divergence': [(1, np.float64(6.746232299506664)),
INFO :      	                     (2, np.float64(6.330510580167174)),
INFO :      	                     (3, np.float64(5.631668356060982)),
INFO :      	                     (4, np.float64(5.325635732710362)),
INFO :      	                     (5, np.float64(5.116712763905525)),
INFO :      	                     (6, np.float64(5.07743831332773)),
INFO :      	                     (7, np.float64(5.029558382183313)),
INFO :      	                     (8, np.float64(4.998278119973838)),
INFO :      	                     (9, np.float64(4.935971319302917)),
INFO :      	                     (10, np.float64(4.821718672849238)),
INFO :      	                     (11, np.float64(4.984422165248543)),
INFO :      	                     (12, np.float64(4.8454857396893205)),
INFO :      	                     (13, np.float64(5.006774018052965)),
INFO :      	                     (14, np.float64(4.840723161399365)),
INFO :      	                     (15, np.float64(4.706784433126449))],
INFO :      	 'loss': [(1, 0.05851137358822772),
INFO :      	          (2, 0.04769202885066478),
INFO :      	          (3, 0.04342130863040528),
INFO :      	          (4, 0.0406822868703531),
INFO :      	          (5, 0.03940017746006256),
INFO :      	          (6, 0.03813326217934069),
INFO :      	          (7, 0.037265940158840376),
INFO :      	          (8, 0.03669571930745258),
INFO :      	          (9, 0.035996162616805945),
INFO :      	          (10, 0.035475826392048486),
INFO :      	          (11, 0.03505014023683522),
INFO :      	          (12, 0.03475266746983328),
INFO :      	          (13, 0.03457510091456186),
INFO :      	          (14, 0.03427019365342175),
INFO :      	          (15, 0.03399859696473173)],
INFO :      	 'mal_alpha_count_round': [(1, 0),
INFO :      	                           (2, 0),
INFO :      	                           (3, 0),
INFO :      	                           (4, 0),
INFO :      	                           (5, 0),
INFO :      	                           (6, 0),
INFO :      	                           (7, 0),
INFO :      	                           (8, 0),
INFO :      	                           (9, 0),
INFO :      	                           (10, 0),
INFO :      	                           (11, 0),
INFO :      	                           (12, 0),
INFO :      	                           (13, 0),
INFO :      	                           (14, 0),
INFO :      	                           (15, 0)],
INFO :      	 'mal_alpha_mean_round': [(1, nan),

[Round 15] learners=15 acc=0.9945 f1=0.9900

INFO :      	                          (2, nan),
INFO :      	                          (3, nan),
INFO :      	                          (4, nan),
INFO :      	                          (5, nan),
INFO :      	                          (6, nan),
INFO :      	                          (7, nan),
INFO :      	                          (8, nan),
INFO :      	                          (9, nan),
INFO :      	                          (10, nan),
INFO :      	                          (11, nan),
INFO :      	                          (12, nan),
INFO :      	                          (13, nan),
INFO :      	                          (14, nan),
INFO :      	                          (15, nan)],
INFO :      	 'num_examples': [(1, 10737),
INFO :      	                  (2, 10737),
INFO :      	                  (3, 10737),
INFO :      	                  (4, 10737),
INFO :      	                  (5, 10737),
INFO :      	                  (6, 10737),
INFO :      	                  (7, 10737),
INFO :      	                  (8, 10737),
INFO :      	                  (9, 10737),
INFO :      	                  (10, 10737),
INFO :      	                  (11, 10737),
INFO :      	                  (12, 10737),
INFO :      	                  (13, 10737),
INFO :      	                  (14, 10737),
INFO :      	                  (15, 10737)],
INFO :      	 'num_filtered': [(1, 7),
INFO :      	                  (2, 7),
INFO :      	                  (3, 7),
INFO :      	                  (4, 7),
INFO :      	                  (5, 7),
INFO :      	                  (6, 7),
INFO :      	                  (7, 7),
INFO :      	                  (8, 7),
INFO :      	                  (9, 7),
INFO :      	                  (10, 7),
INFO :      	                  (11, 7),
INFO :      	                  (12, 7),
INFO :      	                  (13, 7),
INFO :      	                  (14, 7),
INFO :      	                  (15, 7)],
INFO :      	 'num_filtered_malicious': [(1, 7),
INFO :      	                            (2, 7),
INFO :      	                            (3, 7),
INFO :      	                            (4, 7),
INFO :      	                            (5, 7),
INFO :      	                            (6, 7),
INFO :      	                            (7, 7),
INFO :      	                            (8, 7),
INFO :      	                            (9, 7),
INFO :      	                            (10, 7),
INFO :      	                            (11, 7),
INFO :      	                            (12, 7),
INFO :      	                            (13, 7),
INFO :      	                            (14, 7),
INFO :      	                            (15, 7)],
INFO :      	 'precision': [(1, 0.9807511323880959),
INFO :      	               (2, 0.986876321741508),
INFO :      	               (3, 0.9872786583066276),
INFO :      	               (4, 0.9873737835120306),
INFO :      	               (5, 0.9882696299148613),
INFO :      	               (6, 0.9887852981104415),
INFO :      	               (7, 0.9881939682694243),
INFO :      	               (8, 0.9881510037863148),
INFO :      	               (9, 0.9883218014226953),
INFO :      	               (10, 0.9885360665281143),
INFO :      	               (11, 0.9885360665281143),
INFO :      	               (12, 0.9884506368480788),
INFO :      	               (13, 0.9885366616709699),
INFO :      	               (14, 0.9881182208317282),
INFO :      	               (15, 0.9879891908532067)],
INFO :      	 'recall': [(1, 0.9867403929787074),
INFO :      	            (2, 0.9908487026840076),
INFO :      	            (3, 0.9919989127680412),
INFO :      	            (4, 0.9912091714436386),
INFO :      	            (5, 0.9915801837850055),
INFO :      	            (6, 0.9918301837850054),
INFO :      	            (7, 0.9915682208091061),
INFO :      	            (8, 0.9914808998171396),
INFO :      	            (9, 0.9918301837850054),
INFO :      	            (10, 0.9921338134275716),
INFO :      	            (11, 0.9921338134275716),
INFO :      	            (12, 0.9919591714436387),
INFO :      	            (13, 0.9920008381103053),
INFO :      	            (14, 0.9920881591022717),
INFO :      	            (15, 0.9919591714436387)],
INFO :      	 'residual_loss': [(1, np.float64(0.04467624482654389)),
INFO :      	                   (2, np.float64(0.033019018319568466)),
INFO :      	                   (3, np.float64(0.03262027636658223)),
INFO :      	                   (4, np.float64(0.03248665632147874)),
INFO :      	                   (5, np.float64(0.03244255193996997)),
INFO :      	                   (6, np.float64(0.0324018928466276)),
INFO :      	                   (7, np.float64(0.032377483680223425)),
INFO :      	                   (8, np.float64(0.03236877165867814)),
INFO :      	                   (9, np.float64(0.0323450580305819)),
INFO :      	                   (10, np.float64(0.03232390203601902)),
INFO :      	                   (11, np.float64(0.032324516103558604)),
INFO :      	                   (12, np.float64(0.03231509475347896)),
INFO :      	                   (13, np.float64(0.03231382054232416)),
INFO :      	                   (14, np.float64(0.03230570892226838)),
INFO :      	                   (15, np.float64(0.03231053321533615))]}
INFO :

[Sweep] mal_frac=0.70 acc=0.9945 filtered_mal=105/105

,mode,mal_frac,flip_prob,final_accuracy,final_f1,final_precision,final_recall,final_loss,ensemble_size,mal_alpha_mean_last_round,mal_alpha_mean_over_rounds,benign_alpha_mean_last_round,benign_alpha_mean_over_rounds,total_filtered,total_filtered_malicious,avg_filtered_per_round,avg_filtered_malicious_per_round
0,random,0.1,1.0,0.994589,0.990321,0.988536,0.992134,0.034790,15,NaN,NaN,0.968742,0.967866,15,15,1.0,1.0
1,random,0.3,1.0,0.994524,0.990256,0.988493,0.992046,0.034135,15,NaN,NaN,0.968738,0.967846,45,45,3.0,3.0
2,random,0.5,1.0,0.994459,0.990192,0.988407,0.992005,0.034189,15,NaN,NaN,0.968725,0.967840,75,75,5.0,5.0
3,random,0.7,1.0,0.994459,0.989957,0.987989,0.991959,0.033999,15,NaN,NaN,0.968701,0.967836,105,105,7.0,7.0